### ISSUE TITLE
通过域名访问提问时提示1006

### ISSUE THREAD

**Issue by edmondsket** [moeakwak/chatgpt-web-share#10]
![image](https://user-images.githubusercontent.com/27561435/225698045-70cf5c5a-b9a6-4b14-81ed-2a7899c59ed0.png)
我把程序用docker部署在了服务器上，直接用ip+端口号访问可以正常提问。
但是我在宝塔将域名反代到该端口来访问之后，提问时就会提示「获取回复失败1006」，请问是什么原因呢？可以如何解决？

**Comment by edmondsket** [comment]
ChatGPT帮我解决了😅……是nginx反代配置问题，加上了下面这段代码就好了，感谢作者
```
    # WebSocket support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
```

**Comment by moeakwak** [comment]
解决了就好，欢迎使用

**Comment by perown** [comment]
> # WebSocket support
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "upgrade";

我也出现一摸一样的问题，我想问问这段配置加在哪个文件？我有点蒙了，加这/etc/nginx/nginx.conf好像不行

**Comment by perown** [comment]
> # WebSocket support
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "upgrade";

好吧，我也解决了，这里补充一下给小白朋友免得走弯路:

这段配置需要在反向代理的location段中加入。比如你要代理的目标网站是http://localhost:8000，那么在nginx的配置文件中，可以这样写：

perl
Copy code
server {
    listen       80;
    server_name  localhost;

    location / {
        proxy_pass http://localhost:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
这样，nginx就会将所有的请求都代理到http://localhost:8000上，并且启用WebSocket支持。





Regenerate response
