### ISSUE TITLE
这个项目是否支持多个代币？

### ISSUE THREAD

**Issue by Root-FTW** [moeakwak/chatgpt-web-share#101]
这个项目支持多个代币吗？我和我的同学一起有10个chatgpt Plus代币（感谢我的大学），我们希望能够在你的项目中结合所有10个代币并使用它们。

因此，当一个人无法使用或忙于工作时，我可以使用另一个可用的令牌。

**Comment by moeakwak** [comment]
Hi, it's not possible now to support multiple chatgpt accounts. You may consider delpoying multiple docker instances.
