### ISSUE TITLE
pnpm run build运行出错

### ISSUE THREAD

**Issue by iamsad3508** [moeakwak/chatgpt-web-share#103]
**Version**
v0.x.x

**What's your deploying environment?**
- [ ] Docker
- [x ] Caddy
- [ ] Other

**Describe the problem**
ubuntu20.04
node --version     v16.19.1
npm --version      8.19.3

执行
git clone
cd frontend
pnpm install
前面顺利，然后执行
pnpm run build
到这一步就卡了很久，然后就出现以下错误信息

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

root@cloud:~/chatgpt-web-share/frontend# pnpm run build

> chatgpt-share-frontend@0.3.8 build /root/chatgpt-web-share/frontend
> vue-tsc && vite build --config ./config/vite.config.prod.ts

<--- Last few GCs --->

[70325:0x6a98b50]    30776 ms: Mark-sweep (reduce) 490.0 (499.2) -> 489.3 (499.4) MB, 475.2 / 0.0 ms  (+ 60.2 ms in 16 steps since start of marking, biggest step 16.9 ms, walltime since start of marking 684 ms) (average mu = 0.526, current mu = 0.389) all[70325:0x6a98b50]    31712 ms: Mark-sweep (reduce) 490.5 (499.4) -> 489.8 (499.9) MB, 673.5 / 0.0 ms  (+ 54.3 ms in 14 steps since start of marking, biggest step 17.2 ms, walltime since start of marking 788 ms) (average mu = 0.385, current mu = 0.222) all

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb08f10 node::Abort() [node]
 2: 0xa1b70e  [node]
 3: 0xce19d0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xce1d77 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xe993e5  [node]
 6: 0xea90ad v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xeabdae v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xe6d2ea v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
 9: 0x11e60d6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x15d9d59  [node]
Aborted (core dumped)
 ELIFECYCLE  Command failed with exit code 134.

**Additional context**

**Comment by 18870** [comment]
> FATAL ERROR: Reached heap limit Allocation failed - **JavaScript heap out of memory**

你的机器内存不够了

**Comment by iamsad3508** [comment]
连cpu都占满了，这么卡，还是用docker算了
