### ISSUE TITLE
提问的时候提示“[1014] HTTP错误: Client error '403 Forbidden' for url '<chatgpt_base_url>conversation' For more information check: https://httpstatuses.com/403”

### ISSUE THREAD

**Issue by xubiaolin** [moeakwak/chatgpt-web-share#107]
**Version**
v0.x.x

**What's your deploying environment?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
提问的时候提示“[1014] HTTP错误: Client error '403 Forbidden' for url '<chatgpt_base_url>conversation' For more information check: https://httpstatuses.com/403”

**Expected behavior**

**Your config.yaml or other configurations**
```
print_sql: false
host: "127.0.0.1"
port: 8000
data_dir: /data # <------ v0.3.0 以上新增
database_url: "sqlite+aiosqlite:////data/database.db" # 特别注意：这里有四个斜杠，代表着文件位于 /data 目录，使用的是绝对路径
run_migration: false # 是否在启动时运行数据库迁移，目前没有必要启用

jwt_secret: "Go4txt3pWA5uuyV" # 用于生成 jwt token，自行填写随机字符串
jwt_lifetime_seconds: 86400 # jwt token 过期时间
cookie_max_age: 86400 # cookie 过期时间
user_secret: "Go4txt3pWA5uuyV" # 用于生成用户密码，自行填写随机字符串

sync_conversations_on_startup: true # 是否在启动时同步同步 ChatGPT 对话，建议启用。启用后，将会自动将 ChatGPT 中新增的对话同步到数据库中，并把已经不在 ChatGPT 中的对话标记为无效
create_initial_admin_user: true # 是否创建初始管理员用户
initial_admin_username: admin # 初始管理员用户名
initial_admin_password: Go4txt3pWA5uuyV # 初始管理员密码
ask_timeout: 600    # 用于限制对话的最长时间

chatgpt_access_token: "" # 需要从 ChatGPT 获取，见后文
chatgpt_paid: true # 是否为 ChatGPT Plus 用户

# 注意！如果你是 plus 用户，请取消下面的注释，并根据后文说明填写 reverse_proxy_puid
chatgpt_base_url: http://127.0.0.1:6060/api/
run_reverse_proxy: true
reverse_proxy_port: 6060
reverse_proxy_binary_path: /app/backend/ChatGPT-Proxy-V4
reverse_proxy_puid: ""
auto_refresh_reverse_proxy_puid: true # 是否自动更新 puid

log_dir: /app/logs # 日志存储位置，不要随意修改
console_log_level: INFO # 日志等级，设置为 DEBUG 能够获得更多信息

# 注意：以下为 v0.3.0 版本新增配置，用于统计
request_log_counter_time_window: 2592000 # 请求日志时间范围，默认为最近 30 天
request_log_counter_interval: 1800 # 请求日志统计粒度，默认为 30 分钟
ask_log_time_window: 2592000 # 对话日志时间范围，默认为最近 7 天
sync_conversations_regularly: yes # 是否定期（每隔12小时）从账号中同步一次对话
```

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.
![image](https://user-images.githubusercontent.com/51899048/232319846-8edc478e-524f-47a0-ae22-9202a730893f.png)
![image](https://user-images.githubusercontent.com/51899048/232319936-2b9625c2-a876-47ed-a7a8-3d8499e79323.png)

**Additional context**

**Comment by haimang** [comment]
俺也是这样，我只改了那个puid和access token

**Comment by haimang** [comment]
emmmm，我看了旁边那个日志，提示其实还是被CF封禁，但我明明就是用相同的节点在访问ChatGPT呀。为什么我通过VPN使用反而可以，而通过这个工具它自己代理反而不行了呢

**Comment by 1F357** [comment]
同样的问题，大佬们如何解决

**Comment by SirLpc** [comment]
同求大佬出个详细点的教程，昨天弄了一下午没好，今天早上又再试，还是不行~access-token和puid，怎么改都不行 :(

**Comment by ludashi2020** [comment]
token代理失效了，openai加了浏览器检测的限制

**Comment by scc97** [comment]
反代失效了，等待大佬解决这个问题 https://github.com/acheong08/ChatGPT-Proxy-V4/issues/54

**Comment by SirLpc** [comment]
> token代理失效了，openai加了浏览器检测的限制

好吧，感谢解答

**Comment by SirLpc** [comment]
> 反代失效了，等待大佬解决这个问题 [acheong08/ChatGPT-Proxy-V4#54](https://github.com/acheong08/ChatGPT-Proxy-V4/issues/54)

哦哦，好吧，感谢解答~

**Comment by reckonzzz** [comment]
可以用这个替代方案进行反代  https://github.com/moeakwak/chatgpt-web-share/issues/105#issuecomment-1510464954

**Comment by haimang** [comment]
咋说呢，我看ChatGPT-Proxy-V4的老板们正在更新代码，说不定我这个白嫖党再等两天就好了

**Comment by moeakwak** [comment]
目前通过使用go-chatgpt-api暂时解决了这个问题。请更新到最新版本，并且查看wiki的新内容。
