### ISSUE TITLE
Fetch conversation error (unknown): 'items'

### ISSUE THREAD

**Issue by faidev** [moeakwak/chatgpt-web-share#108]
**Version**
v0.3.8

**What's your deploying environment?**
- [*] Caddy
- [*] Other

**Describe the problem**
程序启动时获取会话列表失败
2023/04/17 11:51:03.009     INFO: [cws.utils.store_statistics] Requests statistics loaded.
2023/04/17 11:51:03.023     INFO: [cws.utils.create_user] Create User wayne Error: Username already exists
2023/04/17 11:51:03.027     INFO: [cws.__main__] Using https://bypass.fairydevil.com/backend-api/ as ChatGPT base url
2023/04/17 11:51:03.027     INFO: [cws.utils.sync_conversations] Syncing conversations...
2023/04/17 11:51:03.427    ERROR: [cws.utils.sync_conversations] Fetch conversation error (unknown): 'items'
2023/04/17 11:51:03.427  WARNING: [cws.utils.sync_conversations] Sync conversations on startup failed!
2023/04/17 11:51:03.429     INFO: [cws.__main__] Sync conversations regularly enabled, will sync conversations every 12 hours.
2023/04/17 11:51:03.430     INFO: [uvicorn.error] Application startup complete

重新打开旧会话窗口也会报错，导致继续提问出错
2023/04/17 11:44:13.402     INFO: [uvicorn.error] connection open
2023/04/17 11:44:13.404    DEBUG: [cws.api.routers.chat] wayne connected to websocket
2023/04/17 11:44:14.037    ERROR: [cws.api.routers.chat] 'items'
2023/04/17 11:44:14.037    DEBUG: [cws.api.routers.chat] terminated ask 063e1a05-322b-4470-9b71-2b19b834ec1a (ChatModels.default) because of error
2023/04/17 11:44:14.316     INFO: [uvicorn.error] connection closed
**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by moeakwak** [comment]
你是自己使用了一个公共代理吗？

更新到最新版本再试试，你那个代理应该失效了
