### ISSUE TITLE
Invalid port

### ISSUE THREAD

**Issue by scc97** [moeakwak/chatgpt-web-share#110]
**Version**
v0.3.10

**What's your deploying environment?**
- [√] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
报错端口无效

**Expected behavior**
正常登录并获取对话记录

**Your config.yaml or other configurations**
print_sql: false
host: "127.0.0.1"
port: 8000
data_dir: /data
database_url: "sqlite+aiosqlite:////data/database.db"
run_migration: false

jwt_secret:    # Used for generating JWT token, like a password
jwt_lifetime_seconds: 86400
cookie_max_age: 86400            # Login expiration time
user_secret:   # Used for generating user password, like a password

sync_conversations_on_startup: true # Whether to synchronize ChatGPT conversations on startup, recommended to enable
create_initial_admin_user: true     # Whether to create initial admin user
initial_admin_username:        # Initial admin username
initial_admin_password:     # Initial admin password
ask_timeout: 600

chatgpt_access_token:     # Need to get from ChatGPT
chatgpt_paid: true  # Whether you are a ChatGPT Plus user

log_dir: /app/logs  
console_log_level: INFO

request_log_counter_time_window: 2592000 
request_log_counter_interval: 1800 
ask_log_time_window: 2592000 
sync_conversations_regularly: yes
---------------------------------------------------------------------------------------
version: "3"

services:
  chatgpt-web-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:latest
    container_name: chatgpt-web-share
    restart: unless-stopped
    # network_mode: bridge
    ports:
      - 8080:80
    volumes:
      - ./data:/data
      - ./config.yaml:/app/backend/api/config/config.yaml
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080
    depends_on:
      - go-chatgpt-api

  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    # ports:
      # - 8080:8080 # 如果你需要暴露端口如一带多，可以取消注释
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
#      - NETWORK_PROXY_SERVER=http://host:port
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped
------------------------------------------------------------------------------------
**Screenshots or running logs**
网页日志：
2023/04/17 17:45:02.967    ERROR: [cws.utils.sync_conversations]	Fetch conversation error (unknown): Invalid port
2023/04/17 17:46:04.675    ERROR: [uvicorn.error]	Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_urlparse.py", line 339, in normalize_port
    port_as_int = int(port)
ValueError: invalid literal for int() with base 10: '8080conversation'

网页反代日志
File not found: /app/logs/reverse_proxy.log

**Additional context**

**Comment by moeakwak** [comment]
CHATGPT_BASE_URL最后要有一个斜杠
