### ISSUE TITLE
 ERROR: [cws.utils.sync_conversations] Fetch conversation error (httpx.HTTPError): All connection attempts failed

### ISSUE THREAD

**Issue by poctopus** [moeakwak/chatgpt-web-share#113]
**Version**
v0.3.10

**What's your deploying environment?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
docker-compose up启动后，出现
` ERROR: [cws.utils.sync_conversations] Fetch conversation error (httpx.HTTPError): All connection attempts failed`
报错信息

**Expected behavior**

**Your config.yaml or other configurations**
配置文件如下，基本没有修改。
`print_sql: false
host: "127.0.0.1"
port: 8000
data_dir: /data # <------ v0.3.0 以上新增
database_url: "sqlite+aiosqlite:////data/database.db" # 特别注意：这里有四个斜杠，代表着文件位于 /data 目录，使用的是绝对路径
run_migration: false # 是否在启动时运行数据库迁移，目前没有必要启用

jwt_secret: "eyJhbGciOiKep444zxkBHMJE" # 用于生成 jwt token，自行填写随机字符串
jwt_lifetime_seconds: 86400 # jwt token 过期时间
cookie_max_age: 86400 # cookie 过期时间
user_secret: "43534534" # 用于生成用户密码，自行填写随机字符串

sync_conversations_on_startup: true # 是否在启动时同步同步 ChatGPT 对话，建议启用。启用后，将会自动将 ChatGPT 中新增的对话同步到数据库中，并把已经不在 ChatGPT 中的对话标记为无效
create_initial_admin_user: true # 是否创建初始管理员用户
initial_admin_username: admin # 初始管理员用户名
initial_admin_password: admin # 初始管理员密码
ask_timeout: 600    # 用于限制对话的最长时间

chatgpt_access_token: "eyJhbGciOiJSUzI" # 需要从 ChatGPT 获取，见后文
chatgpt_paid: false # 是否为 ChatGPT Plus 用户

### chatgpt_base_url: http://127.0.0.1:6060/

log_dir: /app/logs # 日志存储位置，不要随意修改
console_log_level: DEBUG #INFO # 日志等级，设置为 DEBUG 能够获得更多信息

## 注意：以下为 v0.3.0 版本新增配置，用于统计
request_log_counter_time_window: 2592000 # 请求日志时间范围，默认为最近 30 天
request_log_counter_interval: 1800 # 请求日志统计粒度，默认为 30 分钟
ask_log_time_window: 2592000 # 对话日志时间范围，默认为最近 7 天
sync_conversations_regularly: yes # 是否定期（每隔12小时）从账号中同步一次对话
`

docker-compose.yml也没有做任何修改，直接使用。

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by scc97** [comment]
Same error, how to solve it?

**Comment by poctopus** [comment]
chatgpt_base_url: http://127.0.0.1:6060/

you can try to  change 127.0.0.1 to server ip.
