### ISSUE TITLE
 Fetch conversation error (httpx.HTTPError)  无法打开会话 。

### ISSUE THREAD

**Issue by JyozeenXuJun23** [moeakwak/chatgpt-web-share#114]
2023/04/18 10:30:46.498     INFO: [uvicorn.error]	Started server process [65937]
2023/04/18 10:30:46.498     INFO: [uvicorn.error]	Waiting for application startup.
2023/04/18 10:30:46.501     INFO: [cws.api.database]	database not exists, creating database...
2023/04/18 10:30:46.509     INFO: [cws.api.database]	database created!
2023/04/18 10:30:46.510     INFO: [alembic.runtime.migration]	Context impl SQLiteImpl.
2023/04/18 10:30:46.510     INFO: [alembic.runtime.migration]	Will assume non-transactional DDL.
2023/04/18 10:30:46.513     INFO: [cws.api.database]	stamped database to head
2023/04/18 10:30:46.514     INFO: [cws.__main__]	database initialized
2023/04/18 10:30:46.514    DEBUG: [cws.utils.store_statistics]	loading statistics from ./data/statistics.json
2023/04/18 10:30:46.514     INFO: [cws.utils.store_statistics]	File statistics.json not found, skip loading statistics.
2023/04/18 10:30:46.782     INFO: [cws.utils.create_user]	User created: <api.models.User object at 0x10d13fd50>
2023/04/18 10:30:46.787     INFO: [cws.__main__]	Using env: <default_bypass> as ChatGPT base url
2023/04/18 10:30:46.787     INFO: [cws.utils.sync_conversations]	Syncing conversations...
2023/04/18 10:30:47.177    ERROR: [cws.utils.sync_conversations]	Fetch conversation error (httpx.HTTPError): 
2023/04/18 10:30:47.177  WARNING: [cws.utils.sync_conversations]	Sync conversations on startup failed!
2023/04/18 10:30:47.181     INFO: [cws.__main__]	Sync conversations regularly enabled, will sync conversations every 12 hours.
2023/04/18 10:30:47.183     INFO: [uvicorn.error]	Application startup complete.
2023/04/18 10:30:47.183     INFO: [uvicorn.error]	Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2023/04/18 10:31:11.577     INFO: [uvicorn.error]	Shutting down
2023/04/18 10:31:11.680     INFO: [uvicorn.error]	Waiting for application shutdown.
2023/04/18 10:31:11.681     INFO: [cws.__main__]	On shutdown...
2023/04/18 10:31:11.681     INFO: [cws.utils.store_statistics]	Requests statistics dumped to ./data/statistics.json.
2023/04/18 10:31:11.682     INFO: [uvicorn.error]	Application shutdown complete.
2023/04/18 10:31:11.682     INFO: [uvicorn.error]	Finished server process [65937]
  以上为报错信息  。

**Comment by JyozeenXuJun23** [comment]
![image](https://user-images.githubusercontent.com/33715190/232655966-80d08192-caa0-4294-badc-604eb28dcb1e.png)
 更新这个包 好用了一天 ，又不好用了。是这个包的问题么

**Comment by moeakwak** [comment]
你这没用docker，也不是最新版本，日志也没有有用信息。这没法判断。先升级到最新版本，按wiki操作
