### ISSUE TITLE
发起对话后一直loading，最后提示获取回复失败 [1014] HTTP错误

### ISSUE THREAD

**Issue by Coolian-WH** [moeakwak/chatgpt-web-share#117]
v0.3.10

- [√ ] Docker
- [ ] Caddy
- [ ] Other

我利用AWS在国外的一台服务器上部署了项目，以前的反代理挂了以后，我按照说明更新了以后依旧无法使用

config.yml
`print_sql: false
host: "127.0.0.1"
port: 8000
data_dir: /data # <------ v0.3.0 以上新增
database_url: "sqlite+aiosqlite:////data/database.db" # 特别注意：这里有四个斜杠，代表着文件位于 /data 目录，使用的是绝对路径
run_migration: false # 是否在启动时运行数据库迁移，目前没有必要启用

jwt_secret: "jjj" # 用于生成 jwt token，自行填写随机字符串
jwt_lifetime_seconds: 86400 # jwt token 过期时间
cookie_max_age: 86400 # cookie 过期时间
user_secret: "jjj" # 用于生成用户密码，自行填写随机字符串

sync_conversations_on_startup: true # 是否在启动时同步同步 ChatGPT 对话，建议启用。启用后，将会自动将 ChatGPT 中新增的对话同步到数据库中，并把已经不在 ChatGPT 中的对>话标记为无效
create_initial_admin_user: true # 是否创建初始管理员用户
initial_admin_username: admin # 初始管理员用户名
initial_admin_password: admin # 初始管理员密码
ask_timeout: 600    # 用于限制对话的最长时间

chatgpt_access_token: #省略
chatgpt_paid: true # 是否为 ChatGPT Plus 用户

# 注意：如果你希望使用公共代理，或使用整合的 go-proxy-api，请保持注释；如果需要自定义，注意最后一定要有一个斜杠
# 在实际请求时，chatgpt_base_url 优先级为：config 内定义 > 环境变量 > revChatGPT 内置的公共代理
# chatgpt_base_url: http://chat.juntong.ai:6060/

log_dir: /app/logs # 日志存储位置，不要随意修改
console_log_level: DEBUG # 日志等级，设置为 DEBUG 能够获得更多信息

# 注意：以下为 v0.3.0 版本新增配置，用于统计
request_log_counter_time_window: 2592000 # 请求日志时间范围，默认为最近 30 天
request_log_counter_interval: 1800 # 请求日志统计粒度，默认为 30 分钟
ask_log_time_window: 2592000 # 对话日志时间范围，默认为最近 7 天
sync_conversations_regularly: yes # 是否定期（每隔12小时）从账号中同步一次对话`

docker-compose.yml
`version: "3"

services:
  chatgpt-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:latest
    restart: always
    ports:
      - 80:80 # web 端口号
    volumes:
      - ./data:/data # 存放数据库文件以及统计数据
      - ./config.yaml:/app/backend/api/config/config.yaml # 后端配置文件
      - ./logs:/app/logs # 存放日志文件
    environment:
      - TZ=Asia/Shanghai
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/
    depends_on:
      - go-chatgpt-api

  go-chatgpt-api:
    image: linweiyuan/go-chatgpt-api
    ports:
      - 6060:8080 # 如果你需要暴露端口如一带多，可以取消注释
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      # - NETWORK_PROXY_SERVER=http://host:port
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server:
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped
`

控制台信息
2023/04/19 17:34:12.952     INFO: [uvicorn.error] Started server process [1]
2023/04/19 17:34:12.953     INFO: [uvicorn.error] Waiting for application startup.
2023/04/19 17:34:12.964     INFO: [alembic.runtime.migration] Context impl SQLiteImpl.
2023/04/19 17:34:12.965     INFO: [alembic.runtime.migration] Will assume non-transactional DDL.
2023/04/19 17:34:12.970     INFO: [cws.main]  database initialized
2023/04/19 17:34:12.970    DEBUG: [cws.utils.store_statistics]  loading statistics from /data/statistics.json
2023/04/19 17:34:12.971     INFO: [cws.utils.store_statistics]  Requests statistics loaded.
2023/04/19 17:34:12.991     INFO: [cws.utils.create_user] Create User admin Error: Username already exists
2023/04/19 17:34:13.006     INFO: [cws.main]  Using env: http://go-chatgpt-api:8080/ as ChatGPT base url
2023/04/19 17:34:13.006     INFO: [cws.utils.sync_conversations]  Syncing conversations...
2023/04/19 17:34:13.025    ERROR: [cws.utils.sync_conversations]  Fetch conversation error (httpx.HTTPError): All connection attempts failed
2023/04/19 17:34:13.026  WARNING: [cws.utils.sync_conversations]  Sync conversations on startup failed!
2023/04/19 17:34:13.026     INFO: [cws.main]  Sync conversations regularly enabled, will sync conversations every 12 hours.
2023/04/19 17:34:13.028     INFO: [uvicorn.error] Application startup complete.
2023/04/19 17:34:13.029     INFO: [uvicorn.error] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2023/04/19 17:35:06.073     INFO: [cws.access]  199.230.105.54:0 | POST /auth/login HTTP/1.1 | 200 OK | 360 ms
2023/04/19 17:35:06.259     INFO: [cws.access]  199.230.105.54:0 | GET /user/me HTTP/1.1 | 200 OK | 10 ms
2023/04/19 17:35:06.549     INFO: [cws.access]  199.230.105.54:0 | GET /system/info HTTP/1.1 | 200 OK | 21 ms
2023/04/19 17:35:06.713     INFO: [cws.access]  199.230.105.54:0 | GET /system/request_statistics HTTP/1.1 | 200 OK | 26 ms
2023/04/19 17:35:06.722     INFO: [cws.access]  199.230.105.54:0 | GET /status HTTP/1.1 | 200 OK | 32 ms
2023/04/19 17:35:06.730     INFO: [cws.access]  199.230.105.54:0 | GET /user HTTP/1.1 | 200 OK | 38 ms
2023/04/19 17:35:12.022     INFO: [cws.access]  199.230.105.54:0 | GET /conv?fetch_all=false HTTP/1.1 | 200 OK | 17 ms
2023/04/19 17:35:19.711     INFO: [uvicorn.error] ('199.230.105.54', 0) - "WebSocket /conv" [accepted]
2023/04/19 17:35:19.715     INFO: [uvicorn.error] connection open
2023/04/19 17:35:19.721    DEBUG: [cws.api.routers.chat]  admin connected to websocket
2023/04/19 17:02:20.485    ERROR: [cws.api.routers.chat]  
2023/04/19 17:02:20.486    DEBUG: [cws.api.routers.chat]  terminated ask None (ChatModels.default) because of error
2023/04/19 17:02:20.661     INFO: [uvicorn.error] connection closed
2023/04/19 17:02:21.224     INFO: [cws.access]  199.230.105.54:0 | GET /user/me HTTP/1.1 | 200 OK | 5 ms
2023/04/19 17:04:06.545     INFO: [cws.access]  199.230.105.54:0 | GET /system/request_statistics HTTP/1.1 | 200 OK | 45 ms
2023/04/19 17:04:06.549     INFO: [cws.access]  199.230.105.54:0 | GET /status HTTP/1.1 | 200 OK | 59 ms
2023/04/19 17:04:06.555     INFO: [cws.access]  199.230.105.54:0 | GET /user HTTP/1.1 | 200 OK | 55 ms
2023/04/19 17:04:06.563     INFO: [cws.access]  199.230.105.54:0 | GET /system/info HTTP/1.1 | 200 OK | 64 ms
2023/04/19 17:04:08.626     INFO: [cws.access]  199.230.105.54:0 | GET /user HTTP/1.1 | 200 OK | 15 ms
2023/04/19 17:07:36.467     INFO: [cws.access]  199.230.105.54:0 | GET /conv?fetch_all=false HTTP/1.1 | 200 OK | 15 ms
2023/04/19 17:08:56.376     INFO: [uvicorn.error] Shutting down
2023/04/19 17:08:56.477     INFO: [uvicorn.error] Waiting for application shutdown.
2023/04/19 17:08:56.477     INFO: [cws.main]  On shutdown...
2023/04/19 17:08:56.478     INFO: [cws.utils.store_statistics]  Requests statistics dumped to /data/statistics.json.
2023/04/19 17:08:56.478     INFO: [uvicorn.error] Application shutdown complete.
2023/04/19 17:08:56.478     INFO: [uvicorn.error] Finished server process [1]

**Comment by leochen12-rgb** [comment]
access_token已经凉的差不多了，反代问题很多

**Comment by Coolian-WH** [comment]
> access_token已经凉的差不多了，反代问题很多

后续有考虑别的解决方案么？比如使用api-key

**Comment by moeakwak** [comment]
查看 wiki 中的 FAQ 以及问题排查指南。

**Comment by Coolian-WH** [comment]
go-chatgpt打印日志：
```
ERRO[0018] Access denied
You do not have access to chat.openai.com.
The site owner may have set restrictions that prevent you from accessing the site.
Ray ID: 7bb1c1939835fb48
Timestamp: 2023-04-21 01:11:59 UTC
Your IP address: 54.176.95.37
Requested URL: chat.openai.com/chat
Error reference number: 1020
Server ID: FL_467F119
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
```

访问反代
```
/app # curl http://go-chatgpt-api:8080/
{"errorMessage":"Missing accessToken."}

ubut@root:/cws$ nslookup go-chatgpt-api
Server:		127.0.0.53
Address:	127.0.0.53#53

** server can't find go-chatgpt-api: SERVFAIL

```
已经反复更换access_token尝试，并且在官网上确认了账号可用性

cws日志
```
{"level":"info","ts":1682039517.906637,"msg":"using provided configuration","config_file":"/app/Caddyfile","config_adapter":"caddyfile"}
{"level":"info","ts":1682039517.912621,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"warn","ts":1682039517.9143484,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
{"level":"info","ts":1682039517.920746,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00042b340"}
{"level":"info","ts":1682039517.9247272,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/root/.local/share/caddy"}
{"level":"info","ts":1682039517.9248536,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1682039517.9265893,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1682039517.9268823,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
{"level":"info","ts":1682039517.9270983,"msg":"serving initial configuration"}
Successfully started Caddy (pid=11) - Caddy is running in the background
2023/04/21 09:12:01.263     INFO: [uvicorn.error] Started server process [1]
2023/04/21 09:12:01.264     INFO: [uvicorn.error] Waiting for application startup.
2023/04/21 09:12:01.276     INFO: [alembic.runtime.migration] Context impl SQLiteImpl.
2023/04/21 09:12:01.277     INFO: [alembic.runtime.migration] Will assume non-transactional DDL.
2023/04/21 09:12:01.283     INFO: [cws.main] database initialized
2023/04/21 09:12:01.283    DEBUG: [cws.utils.store_statistics] loading statistics from /data/statistics.json
2023/04/21 09:12:01.285     INFO: [cws.utils.store_statistics] Requests statistics loaded.
2023/04/21 09:12:01.308     INFO: [cws.utils.create_user] Create User admin Error: Username already exists
2023/04/21 09:12:01.321     INFO: [cws.main] Using env: http://go-chatgpt-api:8080/ as ChatGPT base url
2023/04/21 09:12:01.321     INFO: [cws.utils.sync_conversations] Syncing conversations...
2023/04/21 09:12:01.337    ERROR: [cws.utils.sync_conversations] Fetch conversation error (httpx.HTTPError): All connection attempts failed
2023/04/21 09:12:01.338  WARNING: [cws.utils.sync_conversations] Sync conversations on startup failed!
2023/04/21 09:12:01.338     INFO: [cws.main] Sync conversations regularly enabled, will sync conversations every 12 hours.
2023/04/21 09:12:01.340     INFO: [uvicorn.error] Application startup complete.
2023/04/21 09:12:01.341     INFO: [uvicorn.error] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2023/04/21 09:12:07.787     INFO: [cws.access] 199.230.105.54:0 | POST /auth/login HTTP/1.1 | 200 OK | 358 ms
2023/04/21 09:12:07.973     INFO: [cws.access] 199.230.105.54:0 | GET /user/me HTTP/1.1 | 200 OK | 6 ms
2023/04/21 09:12:08.892     INFO: [cws.access] 199.230.105.54:0 | GET /system/request_statistics HTTP/1.1 | 200 OK | 35 ms
2023/04/21 09:12:08.899     INFO: [cws.access] 199.230.105.54:0 | GET /user HTTP/1.1 | 200 OK | 41 ms
2023/04/21 09:12:08.902     INFO: [cws.access] 199.230.105.54:0 | GET /status HTTP/1.1 | 200 OK | 50 ms
2023/04/21 09:12:08.911     INFO: [cws.access] 199.230.105.54:0 | GET /system/info HTTP/1.1 | 200 OK | 56 ms
2023/04/21 09:12:13.832     INFO: [cws.access] 199.230.105.54:0 | GET /conv?fetch_all=false HTTP/1.1 | 200 OK | 32 ms
2023/04/21 09:12:22.780     INFO: [uvicorn.error] ('199.230.105.54', 0) - "WebSocket /conv" [accepted]
2023/04/21 09:12:22.783     INFO: [uvicorn.error] connection open
2023/04/21 09:12:22.787    DEBUG: [cws.api.routers.chat] admin connected to websocket
2023/04/21 09:22:23.003    ERROR: [cws.api.routers.chat] 
2023/04/21 09:22:23.008    DEBUG: [cws.api.routers.chat] terminated ask None (ChatModels.default) because of error
2023/04/21 09:22:23.194     INFO: [uvicorn.error] connection closed
2023/04/21 09:22:23.623     INFO: [cws.access] 199.230.105.54:0 | GET /user/me HTTP/1.1 | 200 OK | 6 ms
```

proxy-server日志 太长了发一部分
```
[1682041815.537][INFO]: Waiting for pending navigations...
[1682041815.538][INFO]: Done waiting for pending navigations. Status: ok
[1682041815.544][INFO]: Waiting for pending navigations...
[1682041815.545][INFO]: Done waiting for pending navigations. Status: ok
[1682041815.545][INFO]: [2a34e35ccd471a148d1a415124e08480] RESPONSE FindElement ERROR no such element: Unable to locate element: {"method":"css selector","selector":"input"}
  (Session info: chrome=112.0.5615.121)
[1682041815.646][INFO]: [2a34e35ccd471a148d1a415124e08480] COMMAND FindElement {
   "using": "css selector",
   "value": "input"
}
[1682041815.646][INFO]: Waiting for pending navigations...
[1682041815.648][INFO]: Done waiting for pending navigations. Status: ok
[1682041815.654][INFO]: Waiting for pending navigations...
[1682041815.654][INFO]: Done waiting for pending navigations. Status: ok
[1682041815.655][INFO]: [2a34e35ccd471a148d1a415124e08480] RESPONSE FindElement ERROR no such element: Unable to locate element: {"method":"css selector","selector":"input"}
  (Session info: chrome=112.0.5615.121)
[1682041815.756][INFO]: [2a34e35ccd471a148d1a415124e08480] COMMAND FindElement {
   "using": "css selector",
   "value": "input"
}
[1682041815.756][INFO]: Waiting for pending navigations...
[1682041815.757][INFO]: Done waiting for pending navigations. Status: ok
[1682041815.764][INFO]: Waiting for pending navigations...
[1682041815.765][INFO]: Done waiting for pending navigations. Status: ok
[1682041815.765][INFO]: [2a34e35ccd471a148d1a415124e08480] RESPONSE FindElement ERROR no such element: Unable to locate element: {"method":"css selector","selector":"input"}
  (Session info: chrome=112.0.5615.121)
[1682041815.866][INFO]: [2a34e35ccd471a148d1a415124e08480] COMMAND FindElement {
   "using": "css selector",
   "value": "input"
}
[1682041815.866][INFO]: Waiting for pending navigations...
[1682041815.867][INFO]: Done waiting for pending navigations. Status: ok
[1682041815.873][INFO]: Waiting for pending navigations...
[1682041815.874][INFO]: Done waiting for pending navigations. Status: ok
[1682041815.874][INFO]: [2a34e35ccd471a148d1a415124e08480] RESPONSE FindElement ERROR no such element: Unable to locate element: {"method":"css selector","selector":"input"}
  (Session info: chrome=112.0.5615.121)
[1682041815.975][INFO]: [2a34e35ccd471a148d1a415124e08480] COMMAND FindElement {
   "using": "css selector",
   "value": "input"
}
[1682041815.976][INFO]: Waiting for pending navigations...
[1682041815.976][INFO]: Done waiting for pending navigations. Status: ok
[1682041815.983][INFO]: Waiting for pending navigations...
[1682041815.983][INFO]: Done waiting for pending navigations. Status: ok
[1682041815.983][INFO]: [2a34e35ccd471a148d1a415124e08480] RESPONSE FindElement ERROR no such element: Unable to locate element: {"method":"css selector","selector":"input"}
  (Session info: chrome=112.0.5615.121)
[1682041816.084][INFO]: [2a34e35ccd471a148d1a415124e08480] COMMAND FindElement {
   "using": "css selector",
   "value": "input"
}
[1682041816.085][INFO]: Waiting for pending navigations...
[1682041816.085][INFO]: Done waiting for pending navigations. Status: ok
[1682041816.097][INFO]: Waiting for pending navigations...
[1682041816.100][INFO]: Done waiting for pending navigations. Status: ok
[1682041816.100][INFO]: [2a34e35ccd471a148d1a415124e08480] RESPONSE FindElement ERROR no such element: Unable to locate element: {"method":"css selector","selector":"input"}
  (Session info: chrome=112.0.5615.121)
```

**Comment by moeakwak** [comment]
反代日志写的很清楚了，服务器ip被封禁了

**Comment by Coolian-WH** [comment]
```
ubuntu@root:/cws$ bash <(curl -Ls https://cpp.li/openai)
ubuntu@root:/cws$ 

ubuntu@ip-172-31-26-195:/cws$ bash <(curl -L https://cpp.li/openai)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: cpp.li
```
我使用wiki中的命令检查联通性输出这样信息
我ip真被封了？我试着手动调用api是可用的，还是说这个联通性不是一个东西
```
openai api chat_completions.create -m 'gpt-3.5-turbo-0301' -n 1 -M 1000 -t 0.1 -g user "你的名字叫什么"
....(回复的内容)
```

**Comment by xpyoung** [comment]
> 

检查链接失效了，用这个：
https://github.com/moeakwak/chatgpt-web-share/issues/117#issuecomment-1517244699

**Comment by Coolian-WH** [comment]
我用的aws，修改了IP地址还是说被封禁了QAQ

**Comment by Catker** [comment]
ERRO[0018] Access denied
毫无疑问服务器被ban了，正常可用会显示“welcome chatgpt”。换机器或者上warp可解

**Comment by Coolian-WH** [comment]
> ERRO[0018] Access denied 毫无疑问服务器被ban了，正常可用会显示“welcome chatgpt”。换机器或者上warp可解。另外api可以调用不代表access_token可用

大佬懂aws么？我在aws上重新创建了一个实例，运行检查还是报IP被ban，我认知上这应该算换机器了呀

**Comment by Catker** [comment]
> 

可能是aws的段被ban了，不用整这么麻烦，整合一下这个docker-compose就行了https://hub.docker.com/r/linweiyuan/chatgpt-proxy-server-warp

**Comment by Coolian-WH** [comment]
> > 
> 
> 可能是aws的段被ban了，不用整这么麻烦，整合一下这个docker-compose就行了https://hub.docker.com/r/linweiyuan/chatgpt-proxy-server-warp

感谢大佬，事情有了进展，现在go这边应该是正常了日志如下
```
INFO[0025] Welcome to ChatGPT                
```
但是好像于cws并没有联通，我访问go的时候报错Missing access token，使用wiki里检查方法也是找不到go
```
~/cws$ nslookup go-chatgpt-api
Server:		127.0.0.53
Address:	127.0.0.53#53

** server can't find go-chatgpt-api: SERVFAIL
```

我的docker-compose.yml
```
version: "3"

services:
  chatgpt-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:latest
    restart: always
    ports:
      - 8080:80 # web 端口号
    volumes:
      - ./data:/data # 存放数据库文件以及统计数据
      - ./config.yaml:/app/backend/api/config/config.yaml # 后端配置文件
      - ./logs:/app/logs # 存放日志文件
    environment:
      - TZ=Asia/Shanghai
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/
    depends_on:
      - go-chatgpt-api

  go-chatgpt-api:
    ports:
      - 6060:8080 # 如果你需要暴露端口如一带多，可以取消注释
    image: linweiyuan/go-chatgpt-api
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped
```

**Comment by Catker** [comment]
> > > 
> > 
> > 
> > 可能是aws的段被ban了，不用整这么麻烦，整合一下这个docker-compose就行了https://hub.docker.com/r/linweiyuan/chatgpt-proxy-server-warp
> 
> 感谢大佬，事情有了进展，现在go这边应该是正常了日志如下
> 
> ```
> INFO[0025] Welcome to ChatGPT                
> ```
> 
> 但是好像于cws并没有联通，我访问go的时候报错Missing access token，使用wiki里检查方法也是找不到go
> 
> ```
> ~/cws$ nslookup go-chatgpt-api
> Server:		127.0.0.53
> Address:	127.0.0.53#53
> 
> ** server can't find go-chatgpt-api: SERVFAIL
> ```
> 
> 我的docker-compose.yml
> 
> ```
> version: "3"
> 
> services:
>   chatgpt-share:
>     image: ghcr.io/moeakwak/chatgpt-web-share:latest
>     restart: always
>     ports:
>       - 8080:80 # web 端口号
>     volumes:
>       - ./data:/data # 存放数据库文件以及统计数据
>       - ./config.yaml:/app/backend/api/config/config.yaml # 后端配置文件
>       - ./logs:/app/logs # 存放日志文件
>     environment:
>       - TZ=Asia/Shanghai
>       - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/
>     depends_on:
>       - go-chatgpt-api
> 
>   go-chatgpt-api:
>     ports:
>       - 6060:8080 # 如果你需要暴露端口如一带多，可以取消注释
>     image: linweiyuan/go-chatgpt-api
>     environment:
>       - GIN_MODE=release
>       - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
>       - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
>     depends_on:
>       - chatgpt-proxy-server
>       - chatgpt-proxy-server-warp
>     restart: unless-stopped
> 
>   chatgpt-proxy-server:
>     container_name: chatgpt-proxy-server
>     image: linweiyuan/chatgpt-proxy-server
>     environment:
>       - LOG_LEVEL=INFO
>     restart: unless-stopped
> 
>   chatgpt-proxy-server-warp:
>     container_name: chatgpt-proxy-server-warp
>     image: linweiyuan/chatgpt-proxy-server-warp
>     environment:
>       - LOG_LEVEL=INFO
>     restart: unless-stopped
> ```
> 
> 我一开始以为我gpt的token没写，但是我看了下确实写了啊

你仔细看看：go-chatgpt-api:
    ports:
      - 6060:8080

映射的6060端口。

environment:
      - TZ=Asia/Shanghai
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/

chatgpt-share这边引用的是8080，你改成跟go-chatgpt-api的端口一致应该就行了。

**Comment by Coolian-WH** [comment]
> > > > 
> > > 
> > > 
> > > 可能是aws的段被ban了，不用整这么麻烦，整合一下这个docker-compose就行了https://hub.docker.com/r/linweiyuan/chatgpt-proxy-server-warp
> > 
> > 
> > 感谢大佬，事情有了进展，现在go这边应该是正常了日志如下
> > ```
> > INFO[0025] Welcome to ChatGPT                
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是好像于cws并没有联通，我访问go的时候报错Missing access token，使用wiki里检查方法也是找不到go
> > ```
> > ~/cws$ nslookup go-chatgpt-api
> > Server:		127.0.0.53
> > Address:	127.0.0.53#53
> > 
> > ** server can't find go-chatgpt-api: SERVFAIL
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我的docker-compose.yml
> > ```
> > version: "3"
> > 
> > services:
> >   chatgpt-share:
> >     image: ghcr.io/moeakwak/chatgpt-web-share:latest
> >     restart: always
> >     ports:
> >       - 8080:80 # web 端口号
> >     volumes:
> >       - ./data:/data # 存放数据库文件以及统计数据
> >       - ./config.yaml:/app/backend/api/config/config.yaml # 后端配置文件
> >       - ./logs:/app/logs # 存放日志文件
> >     environment:
> >       - TZ=Asia/Shanghai
> >       - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/
> >     depends_on:
> >       - go-chatgpt-api
> > 
> >   go-chatgpt-api:
> >     ports:
> >       - 6060:8080 # 如果你需要暴露端口如一带多，可以取消注释
> >     image: linweiyuan/go-chatgpt-api
> >     environment:
> >       - GIN_MODE=release
> >       - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
> >       - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
> >     depends_on:
> >       - chatgpt-proxy-server
> >       - chatgpt-proxy-server-warp
> >     restart: unless-stopped
> > 
> >   chatgpt-proxy-server:
> >     container_name: chatgpt-proxy-server
> >     image: linweiyuan/chatgpt-proxy-server
> >     environment:
> >       - LOG_LEVEL=INFO
> >     restart: unless-stopped
> > 
> >   chatgpt-proxy-server-warp:
> >     container_name: chatgpt-proxy-server-warp
> >     image: linweiyuan/chatgpt-proxy-server-warp
> >     environment:
> >       - LOG_LEVEL=INFO
> >     restart: unless-stopped
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我一开始以为我gpt的token没写，但是我看了下确实写了啊
> 
> 你仔细看看：go-chatgpt-api: ports: - 6060:8080
> 
> 映射的6060端口。
> 
> environment: - TZ=Asia/Shanghai - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/
> 
> chatgpt-share这边引用的是8080，你改成跟go-chatgpt-api的端口一致应该就行了。

端口映射应该是对的，8080是容器内部端口号，我试了下
```
如果你发现 docker-compose 配置中的 base_url 解析不了或者无法访问，尝试设置 config 中的 chatgpt_base_url 为 http://公网ip:6060。
```
这个以后就能用了，虽然控制台还报了这个错，但是起码能用了
```
2023/04/24 09:24:19.739    ERROR: [cws.utils.sync_conversations] Fetch conversation error (httpx.HTTPError): 
```
不管怎么说，还是十分感谢@Catker的，真心的
