### ISSUE TITLE
合并feat-api进入主线请求

### ISSUE THREAD

**Issue by caicaijiji** [moeakwak/chatgpt-web-share#118]
近期的反代方案极其不稳定而且消耗较多资源，有没有可能将api方案合并入主线作为暂时性的替代方案？

**Comment by moeakwak** [comment]
项目还是以共享账号为主，api只是辅助。api方案需要修改数据库，短时间内不会合并，会在下个大版本放出，请耐心等待。如果有需要可以自己先用。
