### ISSUE TITLE
注册api可以被无权限调用，而默认的对话限制是无限

### ISSUE THREAD

**Issue by dreamhunter2333** [moeakwak/chatgpt-web-share#119]
**Version**
v0.3.10

**What's your deploying method?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
注册api可以被无权限调用，而默认的对话限制是无限

**To Reproduce**
```bash
curl 'http://localhost:8000/api/auth/register' \
  -H 'Content-Type: application/json' \
  --data-raw '{"username":"test","nickname":"test","email":"test","password":"test","is_superuser":false}' \
  --compressed
```

**Expected behavior**

Options:
- 开放注册，可配置默认的 `available_ask_count`
- 注册 api 增加 auth

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by moeakwak** [comment]
感谢反馈，稍后会修复。
