### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by omarsamyi** [moeakwak/chatgpt-web-share#12]
Can you please guide me on how to implement this app on a DigitalOcean droplet? I am facing an issue of 401 unauthorized access. Can you help me troubleshoot this?

"httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://bypass.duti.tech/api/conversations?offset=0&limit=20'
For more information check: https://httpstatuses.com/401"

**Comment by moeakwak** [comment]
Hi there, It's mostly because you've configured chatgpt_access_token incorrectly, or your access_token expired. Please check your config.yaml. If still 401, try to re-login your OpenAI account and get a new access_token.

By the way, see #13 for risk info.

**Comment by omarsamyi** [comment]
Thank you for the information. I will check my config.yaml and try to re-login to my OpenAI account to resolve the issue.
