### ISSUE TITLE
现在最新版本不能渲染Latex数学公式了吗？

### ISSUE THREAD

**Issue by ludashi2020** [moeakwak/chatgpt-web-share#122]
之前的版本都可以自动渲染Latex数学公式，新版本怎么不渲染了？开启回复Markdown，一样不能渲染数学公式了。![WeChat截图_20230421114330.png](https://pic.shenbian.tv/2023/04/21/2d9b666e61db6.png)

**Comment by moeakwak** [comment]
这是chatgpt回复的问题，与项目无关

**Comment by ludashi2020** [comment]
> 这是chatgpt回复的问题，与项目无关

旧版本确实可以渲染latex公式，我当时特意看了一下官网的内容是没有被渲染的，项目输出来是渲染好的。类似https://github.com/Chanzhaoyu/chatgpt-web这个项目数学公式渲染。

**Comment by moeakwak** [comment]
有时候chatgpt回复时公式不会加美元符号，所以显示不了。你要求它公式使用markdown格式就行。项目本身一直可以显示公式。
