### ISSUE TITLE
是否可以增加多账号的支持，并支持对多队列的调度能力

### ISSUE THREAD

**Issue by purezhang** [moeakwak/chatgpt-web-share#123]
是否可以增加多账号的支持，并支持对多队列的调度能力
比如由3个账号，就可以支持至少3个用户同时提问，和应答。谢谢

**Comment by mydaoyuan** [comment]
给作者赞赏，让他爆肝🤣

**Comment by moeakwak** [comment]
目前go-chatgpt-api反代只支持同一时间一个对话，所以暂时没有办法做多账号

**Comment by JamesFlare1212** [comment]
go-chatgpt-api似乎更新了，好像有多回话功能了。

**Comment by moeakwak** [comment]
> go-chatgpt-api似乎更新了，好像有多回话功能了。

目前我测试还非常不稳定。后续如果能稳定会考虑，主要是对于大部分人来说，只会有一个plus账号。多账号可以使用多个实例。
