### ISSUE TITLE
移动端不兼容-没法正常对话和查看历史对话内容

### ISSUE THREAD

**Issue by huxngmail** [moeakwak/chatgpt-web-share#124]
**Version**
v0.3.14

**What's your deploying method?**
 Docker

**Describe the bug**
v0.3.13和v0.3.14版本界面改版后，电脑端的好用了很多，但手机浏览器上没法正常使用，新建了一个会话后，回复没有任何返回，查看历史会话也没法显示内容

**Comment by moeakwak** [comment]
这是safari的兼容性问题导致的，目前安卓正常，iOS会有问题。暂时没想好怎么解决，建议先用全屏按钮看消息。

**Comment by sola97** [comment]
好像对旧版的Chrome浏览器兼容性不太行，旧版PC的Chrome和安卓的Chrome更新之前都看不到历史对话内容
![image](https://user-images.githubusercontent.com/17388849/233815015-98e3f01e-b2f3-462e-9d15-1e99f0de6d99.png)
![image](https://user-images.githubusercontent.com/17388849/233815021-44e28e0e-3fec-4f65-b823-109f9f3b0923.png)
![image](https://user-images.githubusercontent.com/17388849/233815036-971888e8-4eb0-4d28-8a69-35b28a7a0ce7.png)

**Comment by yilin101** [comment]
同ios 没法正常使用

**Comment by nianzecong** [comment]
Ios可以先横屏使用
