### ISSUE TITLE
ERROR：Fetch conversation error (httpx.HTTPError):

### ISSUE THREAD

**Issue by helloqingsir** [moeakwak/chatgpt-web-share#125]
**Version**
v0.3.14

**What's your deploying environment?**
- [ ] Docker
- [ ] Caddy
- [x] 只运行后端
本地运行环境：win10，开启了代理，节点可以正常访问ChatGPT并进行对话

**Your config.yaml or other configurations**
```
print_sql: false
host: "127.0.0.1"
port: 8000
data_dir: ./data
database_url: "sqlite+aiosqlite:///data/database.db"
run_migration: false
jwt_secret: "SECRET"
jwt_lifetime_seconds: 86400
cookie_max_age: 86400
user_secret: "SECRET"

sync_conversations_on_startup: true
create_initial_admin_user: true
create_initial_user: false  
initial_admin_username: admin
initial_admin_password: adminadmin
initial_user_username: user
initial_user_password: useruser

chatgpt_access_token: "XXXXXXXXXXXNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9"
chatgpt_paid: false

# proxy configuration
# chatgpt_base_url: http://127.0.0.1:10809/
# run_reverse_proxy: true
# reverse_proxy_port: 6062
# reverse_proxy_binary_path: ChatGPT-Proxy-V4
# reverse_proxy_puid: "_puid value from cookie"

log_dir: ./logs
console_log_level: INFO


request_log_counter_time_window: 2592000  # 30 days
request_log_counter_interval: 1800  # 30 minutes
ask_log_time_window: 2592000  # 30 days
sync_conversations_regularly: yes
```

**Screenshots or running logs**

![image](https://user-images.githubusercontent.com/131521501/233774744-b4c07ec4-7940-4bdf-a2c2-47da593866d7.png)

**Comment by moeakwak** [comment]
你需要在docker-compose中为go-chatgpt-api设置网络代理。
以后这种问题求解尽量发到群里，不要提issue。

**Comment by helloqingsir** [comment]
好的，打扰了
&nbsp;


qing
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月22日(星期六) 下午5:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [moeakwak/chatgpt-web-share] ERROR：Fetch conversation error (httpx.HTTPError): (Issue #125)





 
 你需要在docker-compose中为go-chatgpt-api设置网络代理。
 以后这种问题求解尽量发到群里，不要提issue。
