### ISSUE TITLE
无法查看历史对话记录

### ISSUE THREAD

**Issue by RinCloud** [moeakwak/chatgpt-web-share#129]
在MacBook M1 pro芯片的Monterey系统上使用chrome浏览器。可以正常对话，但无法查看自己的历史对话框，左侧UI不会出现历史对话栏。同一账号使用其他人的windows电脑则没有这个情况

**Comment by moeakwak** [comment]
设备和你一样，但是没有遇到这个问题。使用的是最新版本么
