### ISSUE TITLE
使用iPhone访问聊天界面和发送新消息时界面空白，但电脑上正常

### ISSUE THREAD

**Issue by JIM353** [moeakwak/chatgpt-web-share#133]
使用docker部署
![Uploading DD3AD842-2A35-4D26-AA32-45640DB0134B.jpeg…]()

**Comment by JIM353** [comment]
![Uploading 9757273F-5519-45D5-92F3-1BF13EBF18F2.jpeg…]()

**Comment by JIM353** [comment]
![70CC520B-6BBD-4C53-B358-7AA08FF456C2](https://user-images.githubusercontent.com/53323241/234451812-7da909de-5e5b-4491-9e76-b5cb90dfc3a2.jpeg)

**Comment by JIM353** [comment]
进入全屏模式可以正常访问，但退出来就白屏
![A224B938-6581-4367-8B0D-3FF8238679FC](https://user-images.githubusercontent.com/53323241/234464449-22607190-ec6a-4ae2-a18e-542cec80f377.jpeg)
🤔

**Comment by JIM353** [comment]
iPhone只有横屏才能查看
![7D0101D8-EDF0-42EE-BA0C-99A5C04A62D8](https://user-images.githubusercontent.com/53323241/234466025-3bc78c8a-d724-4adf-850a-ca272856f0f3.jpeg)

**Comment by moeakwak** [comment]
重复问题 #124

**Comment by JIM353** [comment]
好的，谢谢

**Comment by moeakwak** [comment]
> 找到一篇文章，会不会是因为这个问题导致的，但我手机系统是iOS15：

与这个无关
