### ISSUE TITLE
卡在第一步

### ISSUE THREAD

**Issue by cyybaobao520** [moeakwak/chatgpt-web-share#134]
准小白

使用 Docker 部署
推荐使用 docker-compose 部署。首先，在你的服务器上新建一个目录 cws：

mkdir cws
cd cws
-------------------------------------------------------

这个指令输进去没反应啊

**Comment by xpyoung** [comment]
首先，你得明白这俩指令意思
mkdir cws : 创建目录cws
cd cws : 进入cws目录

现在你需要输入`cd`
然后输入`rm -rf cws` 将cws全删掉
另外先学习一些linux命令，边学习边操作比较好

**Comment by cyybaobao520** [comment]
> 首先，你得明白这俩指令意思 mkdir cws : 创建目录cws cd cws : 进入cws目录
> 
> 现在你需要输入`cd` 然后输入`rm -rf cws` 将cws全删掉 另外先学习一些linux命令，边学习边操作比较好

谢谢，问chatgpt搞定了，但是现在它回复信息报错HTTP错误: null}

![微信图片_20230427113438](https://user-images.githubusercontent.com/37211344/234753173-3efb733f-a10f-4c5b-9f88-5feb42691865.png)

**Comment by soyisou** [comment]
可能你的代理那部分没有配置好，建议你先查看一下你的IP地址是否可以访问OpenAI

**Comment by moeakwak** [comment]
建议先自行学习linux相关知识后再尝试部署，这边对于与项目本身不相关的其它基础问题没有能力回答。
