### ISSUE TITLE
输入的问题太长,会出现1001,希望能明确点

### ISSUE THREAD

**Issue by tanpengsccd** [moeakwak/chatgpt-web-share#135]
**Version**
v0.3.15

**What's your deploying method?**
- [ o] Docker

**Describe the bug**
输入的问题太长,会出现 
<img width="798" alt="image" src="https://user-images.githubusercontent.com/13959880/234621711-8f23c6ce-a1ff-49c2-bf63-4d190419f7c3.png">
实际是
![image](https://user-images.githubusercontent.com/13959880/234622549-00e50a1d-2b58-40d3-b265-5f9b9add4805.png)

**Comment by moeakwak** [comment]
上游请求没有给出错误原因，无法判断是什么原因，你这个需求暂时做不到
