### ISSUE TITLE
手机端的适配不是很好，操作不便

### ISSUE THREAD

**Issue by jiamin-lin** [moeakwak/chatgpt-web-share#139]
**Version**
v0.x.x

**What's your deploying method?**
- [ ] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by qfdk** [comment]
确实不如 Chanzhaoyu/chatgpt-web 有空也出分力了

**Comment by moeakwak** [comment]
后续会改进
