### ISSUE TITLE
api已更新，加入了登录，可能不需要token了，希望适配一下

### ISSUE THREAD

**Issue by aldington-david** [moeakwak/chatgpt-web-share#140]
**Is your feature request related to a problem? Please describe.**
api已更新，加入了登录，可能不需要token了，希望适配一下

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AKGO47** [comment]
你说的是什么api？ 哪个项目？

**Comment by r1172464137** [comment]
https://github.com/linweiyuan/go-chatgpt-api
这个吧

**Comment by superen7527** [comment]
我觉得 应该是两个方向，有的地方只有反代 还是需要token。这种内置，可能需要另外的判断。不能全部砍掉

**Comment by summersun2023** [comment]
如果不需要token，就没有考虑过google授权登录的用户吗？
