### ISSUE TITLE
能否使用自己的 Clash 代理来访问chatgpt

### ISSUE THREAD

**Issue by djkcyl** [moeakwak/chatgpt-web-share#141]
**Version**
v0.3.15

**What's your deploying environment?**
- [x] Docker
- [ ] Caddy
- [ ] Other

我用的是aio的docker compose
如题，如果可以的话要在compose的yaml里配置还是config里设置

因为用的是家里云，测试用路由器开代理是没问题的，但是路由器的openclash容易卡死出bug，所以想问问这个项目本身支不支持用自己的http proxy。

节点是 justmysocks 的，支持访问 ChatGPT
如果开了路由器的透明代理就一切正常，如果不开就会出现下面的报错

前端报错：
```
502 ChatGPT返回错误: OpenAI 500: {"errorMessage":"Get \"https://chat.openai.com/backend-api/conversation/6f629959-5a71-4379-ae6c-c3c2193ec8fb\": read tcp 172.16.0.2:52572-\u003e104.18.3.161:443: read: connection reset by peer"}
```

后端报错：
```
ERROR: [cws.api.routers.chat] OpenAI: {"errorMessage":"Get \"https://chat.openai.com/backend-api/conversations?offset=0\u0026limit=20\": read tcp 172.16.0.2:37304-\u003e104.18.2.161:443: read: connection reset by peer"} (code: 500)
```

**Comment by nianzecong** [comment]
go-chatgpt-api 可以设置http或者socks代理呀，我部署在家里，然后通过socks代理出国就没问题，ip本身可以访问gpt的话，也不用wrap，再把cws设置chatgpt_base_url为go-chatgpt-api 的地址就可以了

**Comment by moeakwak** [comment]
网络问题请自行解决，有关反代设置代理请移步go-chatgpt-api项目说明。
