### ISSUE TITLE
关于导出记录建议

### ISSUE THREAD

**Issue by superen7527** [moeakwak/chatgpt-web-share#142]
1.能不能支持全部记录导出，而不是单次对话
2.官网历史记录只有分配，能不能加上(全部)导出功能？

3.以后有没有可能做类似于官网的重新编辑功能？
感觉这样产生的记录不好导出，但是有一些情况又不得不重新问(比如回复不完全，只能说继续，但是有时候继续不会补全，可能要重新编辑多试几次，而不是新的回复里说继续)，不知道有没有好的办法想法？

**Comment by moeakwak** [comment]
1、2暂时不会支持。3的话，以后可能支持对话分支。
