### ISSUE TITLE
多账号思路

### ISSUE THREAD

**Issue by superen7527** [moeakwak/chatgpt-web-share#144]
有一个想法，既然单独一个账号回复拥挤，能不能每个账号绑定不同的官网账号直接分开? 毕竟账号不值钱。我注意到有一个issue是说以后会支持账号密码不需要token，我觉得那之后可以添加管理员添加原始账号功能。逻辑像现在分配历史一样，如果没有分配，就用创建docker的默认账号。

避免了多个账号写在run里不方便修改 写在config文件还需要重启，写在网页倒是最好的，当然写在文件里也能接受。这样的逻辑兼容最开始的一个默认账号token，在基础上新增账号功能。而不是推倒从来强制一个号对应一个号，感觉比较好实现。

如果会采纳建议是从有账号密码登录以后再实现 不然改token也没有辨识度 不会采纳就关闭一下issue吧 我也只是建议而已

**Comment by moeakwak** [comment]
历史issue里面有说，如果反代多账号稳定了会考虑，目前暂不考虑。
