### ISSUE TITLE
分离部署遇到的问题

### ISSUE THREAD

**Issue by jiashu1024** [moeakwak/chatgpt-web-share#145]
**Version**
latest

**What's your deploying environment?**
-  Docker

**Describe the problem**
proxy和web分开部署，好像是无法访问代理的异常

**Your config.yaml or other configurations**
**proxy的docker配置如下**
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: ddsderek/go-chatgpt-api
    ports:
      - 6060:8080 # 宿主机8080端口可按需改为其它端口
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      

**cws的docker配置如下**
services:
  chatgpt-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:latest
    restart: always
    ports:
      - 8080:80 # web 端口号
    volumes:
      - ./data:/data # 存放数据库文件以及统计数据
      - ./config.yaml:/app/backend/api/config/config.yaml # 后端配置文件
      - ./logs:/app/logs # 存放日志文件

**config.yml配置如下**
print_sql: false
host: "127.0.0.1"
port: 8000
data_dir: /data # <------ v0.3.0 以上新增
database_url: "sqlite+aiosqlite:////data/database.db" # 特别注意：这里有四个斜杠，代表着文件位于 /data 目录，使用的是绝对路径
run_migration: false # 是否在启动时运行数据库迁移，目前没有必要启用

jwt_secret: "zhangjiashu" # 用于生成 jwt token，自行填写随机字符串
jwt_lifetime_seconds: 86400 # jwt token 过期时间
cookie_max_age: 86400 # cookie 过期时间
user_secret: "jiashu" # 用于生成用户密码，自行填写随机字符串

sync_conversations_on_startup: true # 是否在启动时同步同步 ChatGPT 对话，建议启用。启用后，将会自动将 ChatGPT 中新增的对话同步到数据库中，并把已经不在 ChatGPT 中的对话标记为无效
create_initial_admin_user: true # 是否创建初始管理员用户
initial_admin_username: admin # 初始管理员用户名
initial_admin_password: password # 初始管理员密码
ask_timeout: 600    # 用于限制对话的最长时间

chatgpt_access_token: "****" # 需要从 ChatGPT 获取，见后文
chatgpt_paid: true # 是否为 ChatGPT Plus 用户

chatgpt_base_url: http://172.17.0.1:6060/

log_dir: /app/logs # 日志存储位置，不要随意修改
console_log_level: INFO # 日志等级，设置为 DEBUG 能够获得更多信息

request_log_counter_time_window: 2592000 # 请求日志时间范围，默认为最近 30 天
request_log_counter_interval: 1800 # 请求日志统计粒度，默认为 30 分钟
ask_log_time_window: 2592000 # 对话日志时间范围，默认为最近 7 天
sync_conversations_regularly: yes # 是否定期（每隔12小时）从账号中同步一次对话
**Screenshots or running logs**
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/67859663/235825669-22168926-8ac5-4673-9e2d-e9ba725564e2.png">

**Additional context**

**Comment by moeakwak** [comment]
chatgpt_base_url使用公网ip

**Comment by jiashu1024** [comment]
> chatgpt_base_url使用公网ip

试过了 还是不行，确认端口已经开放，我从浏览器用公网ip访问6060是能收到miss token

**Comment by jiashu1024** [comment]
> chatgpt_base_url使用公网ip

你好，有联系方式吗，如果方便可以登下我的服务器帮我看下吗

**Comment by moeakwak** [comment]
目前暂时没有精力提供单独的支持，你可以进入tg群组提问
