### ISSUE TITLE
English guide docker-compose.yml and config.yaml is deprecated 

### ISSUE THREAD

**Issue by ser-tec** [moeakwak/chatgpt-web-share#146]
if you follow english guide you will have " All connection attempts failed" error and never success to make chatgpt-web-share to work.

if you copy past docker-compose.yml and config.yaml from chinese guide it will works.

**Comment by moeakwak** [comment]
Thank you for your feedback. I haven’t updated the English guide in a while, and I'm currently working on some major updates. To avoid confusion and for convenience, I'll hold off on updating the English guide until the next version release.
