### ISSUE TITLE
docker cws-chatgpt-proxy-server 占用大量空间

### ISSUE THREAD

**Issue by jacywy** [moeakwak/chatgpt-web-share#148]
**Version**
v0.3.15

**What's your deploying method?**
- [x] Docker

**Describe the bug**
cws-chatgpt-proxy-server (path: /var/lib/docker/containers) huge log file.

**Your config.yaml or other configurations**
Default docker config

**Screenshots or running logs**
[root@x cb75ba913f69a446b20a8015a927b44bc47ffd6105eb544d35bc4f45b0e0beb2]# ls -lh
total 55G
-rw-r----- 1 root root  55G May  6 11:04 cb75ba913f69a446b20a8015a927b44bc47ffd6105eb544d35bc4f45b0e0beb2-json.log
drwx------ 2 root root 4.0K Apr 27 09:47 checkpoints
-rw------- 1 root root 3.5K Apr 27 10:04 config.v2.json
-rw------- 1 root root 1.5K Apr 27 10:04 hostconfig.json
-rw-r--r-- 1 root root   13 Apr 27 10:04 hostname
-rw-r--r-- 1 root root  174 Apr 27 10:04 hosts
drwx--x--- 2 root root 4.0K Apr 27 09:47 mounts
-rw-r--r-- 1 root root   38 Apr 27 10:04 resolv.conf
-rw-r--r-- 1 root root   71 Apr 27 10:04 resolv.conf.hash

**Comment by jacywy** [comment]
查看负载记录，此日志文件大约1天前开始异常变大，目前还在不断疯涨，最后几行：
{"log":"   \"script\": \"return conversationMap.get('2b1a1075-0502-4e08-bef5-a44                                                                                                                                                             2036de5a9');\"\n","stream":"stderr","time":"2023-05-06T03:12:22.136390232Z"}
{"log":"}\n","stream":"stderr","time":"2023-05-06T03:12:22.13639578Z"}
{"log":"[1683342742.145][INFO]: Waiting for pending navigations...\n","stream":"                                                                                                                                                             stderr","time":"2023-05-06T03:12:22.13658584Z"}
{"log":"[1683342742.145][INFO]: Done waiting for pending navigations. Status: ok                                                                                                                                                             \n","stream":"stderr","time":"2023-05-06T03:12:22.137338521Z"}
{"log":"[1683342742.147][INFO]: Waiting for pending navigations...\n","stream":"                                                                                                                                                             stderr","time":"2023-05-06T03:12:22.138650458Z"}
{"log":"[1683342742.147][INFO]: Done waiting for pending navigations. Status: ok                                                                                                                                                             \n","stream":"stderr","time":"2023-05-06T03:12:22.139371106Z"}
{"log":"[1683342742.148][INFO]: [2c4b44b9b26bcd9f53a9c2d0bd663635] RESPONSE Exec                                                                                                                                                             uteScript null\n","stream":"stderr","time":"2023-05-06T03:12:22.139613205Z"}
{"log":"[1683342742.148][INFO]: [2c4b44b9b26bcd9f53a9c2d0bd663635] COMMAND Execu                                                                                                                                                             teScript {\n","stream":"stderr","time":"2023-05-06T03:12:22.140253703Z"}
{"log":"   \"args\": [  ],\n","stream":"stderr","time":"2023-05-06T03:12:22.1402                                                                                                                                                             68465Z"}
{"log":"   \"script\": \"return conversationMap.get('2b1a1075-0502-4e08-bef5-a44                                                                                                                                                             2036de5a9');\"\n","stream":"stderr","time":"2023-05-06T03:12:22.14027473Z"}
{"log":"}\n","stream":"stderr","time":"2023-05-06T03:12:22.140280323Z"}
{"log":"[1683342742.149][INFO]: Waiting for pending navigations...\n","stream":"                                                                                                                                                             stderr","time":"2023-05-06T03:12:22.140517545Z"}
{"log":"[1683342742.150][INFO]: Done waiting for pending navigations. Status: ok                                                                                                                                                             \n","stream":"stderr","time":"2023-05-06T03:12:22.141681974Z"}
{"log":"[1683342742.151][INFO]: Waiting for pending navigations...\n","stream":"                                                                                                                                                             stderr","time":"2023-05-06T03:12:22.143009808Z"}
{"log":"[1683342742.152][INFO]: Done waiting for pending navigations. Status: ok                                                                                                                                                             \n","stream":"stderr","time":"2023-05-06T03:12:22.143737913Z"}
{"log":"[1683342742.152][INFO]: [2c4b44b9b26bcd9f53a9c2d0bd663635] RESPONSE Exec                                                                                                                                                             uteScript null\n","stream":"stderr","time":"2023-05-06T03:12:22.143930773Z"}
{"log":"[1683342742.153][INFO]: [2c4b44b9b26bcd9f53a9c2d0bd663635] COMMAND Execu                                                                                                                                                             teScript {\n","stream":"stderr","time":"2023-05-06T03:12:22.14462269Z"}
{"log":"   \"args\": [  ],\n","stream":"stderr","time":"2023-05-06T03:12:22.1446                                                                                                                                                             38845Z"}
{"log":"   \"script\": \"return conversationMap.get('2b1a1075-0502-4e08-bef5-a44                                                                                                                                                             2036de5a9');\"\n","stream":"stderr","time":"2023-05-06T03:12:22.144645367Z"}
{"log":"}\n","stream":"stderr","time":"2023-05-06T03:12:22.144651003Z"}
{"log":"[1683342742.153][INFO]: Waiting for pending navigations...\n","stream":"                                                                                                                                                             stderr","time":"2023-05-06T03:12:22.144847791Z"}
{"log":"[1683342742.154][INFO]: Done waiting for pending navigations. Status: ok                                                                                                                                                             \n","stream":"stderr","time":"2023-05-06T03:12:22.14556638Z"}
{"log":"[1683342742.155][INFO]: Waiting for pending navigations...\n","stream":"                                                                                                                                                             stderr","time":"2023-05-06T03:12:22.146903486Z"}
{"log":"[1683342742.156][INFO]: Done waiting for pending navigations. Status: ok                                                                                                                                                             \n","stream":"stderr","time":"2023-05-06T03:12:22.147609143Z"}
{"log":"[1683342742.156][INFO]: [2c4b44b9b26bcd9f53a9c2d0bd663635] RESPONSE Exec                                                                                                                                                             uteScript null\n","stream":"stderr","time":"2023-05-06T03:12:22.147798124Z"}
{"log":"[1683342742.157][INFO]: [2c4b44b9b26bcd9f53a9c2d0bd663635] COMMAND Execu                                                                                                                                                             teScript {\n","stream":"stderr","time":"2023-05-06T03:12:22.148434376Z"}
{"log":"   \"args\": [  ],\n","stream":"stderr","time":"2023-05-06T03:12:22.1484                                                                                                                                                             49026Z"}
{"log":"   \"script\": \"return conversationMap.get('2b1a1075-0502-4e08-bef5-a44                                                                                                                                                             2036de5a9');\"\n","stream":"stderr","time":"2023-05-06T03:12:22.148455497Z"}
{"log":"}\n","stream":"stderr","time":"2023-05-06T03:12:22.148460935Z"}
{"log":"[1683342742.157][INFO]: Waiting for pending navigations...\n","stream":"                                                                                                                                                             stderr","time":"2023-05-06T03:12:22.148680011Z"}
{"log":"[1683342742.157][INFO]: Done waiting for pending navigations. Status: ok                                                                                                                                                             \n","stream":"stderr","time":"2023-05-06T03:12:22.14935917Z"}

重启这个容器后停止疯涨了

**Comment by jiashu1024** [comment]
> 

这个是go-chatgpt-api那个项目有问题，我也遇到过，一个日志文件占了我13G，不过就遇到过那一次，后面重启几次没有遇到过。建议部署新版的go-chatgpt-api反代接口，不会有server这个容器启动。但新版的对机子的要求比较高，哪怕用了wrap也会有机会出现403，所以得自己试试新版本自己能用不。

**Comment by imtms** [comment]
#156 可以使用新版go-chatgpt-api

**Comment by moeakwak** [comment]
如果仍使用legacy，可以配置docker compose限制日志大小
