### ISSUE TITLE
获取回复失败 [1001] ChatGPT返回错误

### ISSUE THREAD

**Issue by BR1981** [moeakwak/chatgpt-web-share#154]
**Version**
v0.x.x

**What's your deploying environment?**
- [ ] Docker
- [ ] Caddy
- [ ] Other
![微信图片_20230425110726](https://github.com/moeakwak/chatgpt-web-share/assets/96570470/080987b5-03f3-4184-a9e8-2a2dea8b168b)

**Describe the problem**
A clear and concise description of your problem.

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by BR1981** [comment]
传错图片了，我擦

**Comment by Chris930101** [comment]
我也一样

**Comment by arang129** [comment]
+1

**Comment by Chris930101** [comment]
我发现换了token就好了，我明明token 月底才到期的
