### ISSUE TITLE
获取回复失败 [1001] ChatGPT返回错误

### ISSUE THREAD

**Issue by aantior** [moeakwak/chatgpt-web-share#157]
**Version**
v0.3.15

**What's your deploying environment?**
- [ √ ] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
A clear and concise description of your problem.
当前请求内容后返回  获取回复失败  [1001] ChatGPT返回错误

后台日志：
2023/05/16 09:03:25.933     INFO: [uvicorn.error]	connection open
2023/05/16 09:03:25.939    DEBUG: [cws.api.routers.chat]	antior connected to websocket
2023/05/16 09:03:26.143    ERROR: [cws.api.routers.chat]	OpenAI: 404 page not found (code: 404)
2023/05/16 09:03:26.144    DEBUG: [cws.api.routers.chat]	terminated ask None (ChatModels.default) because of error
2023/05/16 09:03:26.325     INFO: [uvicorn.error]	connection closed
2023/05/16 09:03:26.540     INFO: [cws.access]	113.68.237.98:0 | GET /user/me HTTP/1.1 | 200 OK | 9 ms

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

![image](https://github.com/moeakwak/chatgpt-web-share/assets/131586786/f870d536-8464-436e-b287-8b8bb8ff6541)
![image](https://github.com/moeakwak/chatgpt-web-share/assets/131586786/42106329-a18a-4df9-b81e-41cf0883b5f7)

**Comment by zzzerow** [comment]
如果用的是最新的go-chatgpt-api的镜像，那么你需要修改环境变量：CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/（相对于原来的多了一个chatgpt，注意以斜杠结尾）
