### ISSUE TITLE
前端问题反馈

### ISSUE THREAD

**Issue by edmondsket** [moeakwak/chatgpt-web-share#16]
![image](https://user-images.githubusercontent.com/27561435/226152218-e2cd0bd4-0145-4edf-997f-61ac01bf289c.png)
用了好几天，发现几个前端体验的问题想反馈一下，希望可以采纳。
1. **建议用户可直接删除自己的对话，而不只是设为无效。** 我发现即使用户自己删除了对话仅仅是在数据库里将对话标记为了无效，需要管理员在管理后台手动清除对话才能真正删除对话。在设定了用户对话数限制的情况下，一旦用户对话数超过限制，用户就无法再对话了，必定会弹出会话数量超出限制的提醒，即无论如何都要管理员登后台清除无效对话才行。
2. **提问出错时，发送的文字内容返回输入框**。 现在发送文字时如果出错，发出去的文字就直接消失了，如果编辑了一大段文字就直接没了，希望可以在提问出错时可以将发出去的文字返回到输入框里，避免文字丢失。

**Comment by moeakwak** [comment]
你好，感谢反馈。第一个问题是已知的bug，只是还没来得及改；第二个问题，如果遇到错误弹框，可以不用点击“撤回消息”按钮，直接关闭弹框，这样不会使得发送的消息消失。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月19日 11:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [moeakwak/chatgpt-web-share] 前端问题反馈 (Issue #16) |


用了好几天，发现几个前端体验的问题想反馈一下，希望可以采纳。

建议用户可直接删除自己的对话，而不只是设为无效。 我发现即使用户自己删除了对话仅仅是在数据库里将对话标记为了无效，需要管理员在管理后台手动清除对话才能真正删除对话。在设定了用户对话数限制的情况下，一旦用户对话数超过限制，用户就无法再对话了，必定会弹出会话数量超出限制的提醒，即无论如何都要管理员登后台清除无效对话才行。
提问出错时，发送的文字内容返回输入框。 现在发送文字时如果出错，发出去的文字就直接消失了，如果编辑了一大段文字就直接没了，希望可以在提问出错时可以将发出去的文字返回到输入框里，避免文字丢失。

**Comment by edmondsket** [comment]
感谢回复，想问一下有计划增加停止生成、清空对话历史的功能吗？

**Comment by moeakwak** [comment]
> 感谢回复，想问一下有计划增加停止生成、清空对话历史的功能吗？

有，不过优先级较为靠后，目前精力不多，想到啥做啥，可能要慢慢更新
