### ISSUE TITLE
容器`chatgpt-proxy-server`一直在重启

### ISSUE THREAD

**Issue by aantior** [moeakwak/chatgpt-web-share#160]
**Version**
v0.3.15

**What's your deploying environment?**
- [ √ ] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
容器`chatgpt-proxy-server`一直在重启，但是CWS是可用的。

**Screenshots or running logs**
![image](https://github.com/moeakwak/chatgpt-web-share/assets/131586786/08baf481-6db9-405c-b56f-d177250e432c)

**Additional context**
None

**Comment by moeakwak** [comment]
这与本项目无关，请自行解决
