### ISSUE TITLE
请问支持API的新版本最近会发布么

### ISSUE THREAD

**Issue by fusang1337** [moeakwak/chatgpt-web-share#162]
**Version**
v0.x.x

**What's your deploying environment?**
- [ ] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
A clear and concise description of your problem.

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by hunkjun** [comment]
貌似作者很久没有更新了，估计在策划下一个大版本.

**Comment by hunkjun** [comment]
我这边本地已经实现了key的访问，还有些bug, 如果需要可以si 我

**Comment by hunkjun** [comment]
> **Version** v0.x.x
> 
> **What's your deploying environment?**
> 
> * [ ]  Docker
> * [ ]  Caddy
> * [ ]  Other
> 
> **Describe the problem** A clear and concise description of your problem.
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Your config.yaml or other configurations** Provide your configurations. You may hide your secrets or access tokens.
> 
> **Screenshots or running logs** If applicable, add screenshots or logs to help explain your problem.
> 
> **Additional context** Add any other context about the problem here.

我这边已经实现了相关api的访问方式(有些许bug), 需要的话可以s我...

**Comment by fusang1337** [comment]
> > **Version** v0.x.x
> > **What's your deploying environment?**
> > 
> > * [ ]   Docker
> > * [ ]   Caddy
> > * [ ]   Other
> > 
> > **Describe the problem** A clear and concise description of your problem.
> > **Expected behavior** A clear and concise description of what you expected to happen.
> > **Your config.yaml or other configurations** Provide your configurations. You may hide your secrets or access tokens.
> > **Screenshots or running logs** If applicable, add screenshots or logs to help explain your problem.
> > **Additional context** Add any other context about the problem here.
> 
> 我这边已经实现了相关api的访问方式(有些许bug), 需要的话可以s我...

谢谢大佬 我该如何联系您？我有发邮件ik*yit*p@**.com

**Comment by moeakwak** [comment]
昨天已经发布了测试版本，但是使用说明尚未更新。可以再等待一下。

**Comment by fusang1337** [comment]
貌似现在还未发布？我可以自己摸索一下么？请问现在的[dev](https://github.com/moeakwak/chatgpt-web-share/tree/dev)是否支持api
