### ISSUE TITLE
求助：OpenAI: {"message":"Route not found"} (code: 404)

### ISSUE THREAD

**Issue by SirLpc** [moeakwak/chatgpt-web-share#164]
**Version**
v0.x.x

**What's your deploying environment?**
- [ ] Docker
- [ ] Caddy
- [ ] Other

之前还是好好的，有几天没用，上来运行报 OpenAI: {"message":"Route not found"} (code: 404) 错误，尝试更新了accesstoken和pull最新的仓库还是出这个问题。
![image](https://github.com/moeakwak/chatgpt-web-share/assets/17614861/e19b1e83-8f25-499c-be72-032fd238ad8b)

**Comment by moeakwak** [comment]
新版的go-chatgpt-api改了api，chatgpt base url需要在最后加上 `/chatgpt/`.

**Comment by SirLpc** [comment]
> 新版的go-chatgpt-api改了api，chatgpt base url需要在最后加上 `/chatgpt/`.

啊，谢谢大大，没留意到配置中的这个更改，调整之后可以啦，不好意思~感谢指点 ：）
