### ISSUE TITLE
不使用docker, 直接运行源码会提示找不到./config\credentials.yaml

### ISSUE THREAD

**Issue by needones** [moeakwak/chatgpt-web-share#165]
**Version**
v0.x.x

**What's your deploying environment?**
- [ ] Docker
- [ ] Caddy
- [*] Other

运行poetry run python main.py，会提示缺少文件，config.yaml文件文档已提供
请问这个credentials.yaml在哪里啊？

**Comment by moeakwak** [comment]
在项目目录运行 `python manage.py create_config ./data/config/` 可以创建

**Comment by pmd5** [comment]
在项目目录运行 `python manage.py create_config ./data/config/` 可以创建 仍然报找不到 Config file not found: ./data/config/config.yaml

**Comment by funny-cat-happy** [comment]
在__init__.py注释掉config.load()和credentials.load()，再运行python manage.py create_config ./data/config/就可以创建了
