### ISSUE TITLE
[BUG] dev alpha1 版本部分 bug 报告

### ISSUE THREAD

**Issue by LightningRS** [moeakwak/chatgpt-web-share#166]
**Version**
v0.4.0-alpha1

**What's your deploying method?**
- [√] Docker

**Describe the bug**
1. 历史对话内容中，用户输入的内容显示为 JSON
![bug1](https://github.com/moeakwak/chatgpt-web-share/assets/54468001/8f87fe7b-1699-44ef-945e-5bd702121132)

2. GPT-4 Browsing Chat 模型历史对话内容无法正确显示
![image](https://github.com/moeakwak/chatgpt-web-share/assets/54468001/b0043ec8-159f-40a7-8d55-24272db062b9)
官网显示效果：
![1684475108248](https://github.com/moeakwak/chatgpt-web-share/assets/54468001/0bf56406-1cb6-4808-83fb-a6d76abbf5e2)

3. 管理首页的对话次数统计，目前似乎都显示为普通模型
![image](https://github.com/moeakwak/chatgpt-web-share/assets/54468001/f5d44801-4177-4801-ae22-8fd9f6025d75)

**Comment by moeakwak** [comment]
1,3 已经解决。2等后续慢慢优化样式。
