### ISSUE TITLE
手机版网页适配问题

### ISSUE THREAD

**Issue by hiddow** [moeakwak/chatgpt-web-share#167]
**Version**
v0.3.15

**What's your deploying method?**
- Docker

**Describe the bug**
手机版网页好像没有适配，点击一个对话历史记录没有展示，全部是空白，发送提问，最新的回复也不会展示出来

![2023-05-19 18 30 44](https://github.com/moeakwak/chatgpt-web-share/assets/8944374/7784e925-f124-49d3-b3f9-69febbe70eaf)

**Comment by moeakwak** [comment]
这个兼容性问题在一次PR中修复了，但是还没有发布版本。

可以稍微等一下0.4版本，急需的话可以自行从v0.3分支上构建。
