### ISSUE TITLE
[Bug]界面重叠

### ISSUE THREAD

**Issue by ithou** [moeakwak/chatgpt-web-share#170]
安卓 chrome：
![Screenshot_20230521_230946](https://github.com/moeakwak/chatgpt-web-share/assets/39048771/703bf89e-2df0-4d1f-be74-5f214f20e895)

**Comment by moeakwak** [comment]
并不是bug，就是在这个位置。按钮本身设计成了透明，提问完了也会消失，没啥影响。

**Comment by ithou** [comment]
@moeakwak 好的，是否可以优化一下呢？😂
