### ISSUE TITLE
我想自定义一下问答, 在routes/ chat.py中 而不去调用 openai,但是每次发完一次消息就卡住

### ISSUE THREAD

**Issue by wayne-data** [moeakwak/chatgpt-web-share#171]
**Version**
v0.x.x

**What's your deploying environment?**
- [ ] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
A clear and concise description of your problem.

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by wayne-data** [comment]
我想自定义一下问答, 就是根据提问内容判断了一下
在routes/ chat.py中 而不去调用 openai,但是每次发完一次消息就卡住
必须要刷新页面 重建对话才可以使用
请教下是什么原因? 
![image](https://github.com/moeakwak/chatgpt-web-share/assets/104449006/f2377640-6a4a-41e8-82b2-63f56fdde308)

这里会卡住, 有什么解决办法吗?

**Comment by moeakwak** [comment]
你的意思是你修改了代码，然后遇到了卡在加载状态的情况？

**Comment by wayne-data** [comment]
> 你的意思是你修改了代码，然后遇到了卡在加载状态的情况？

是的 这是咋回事 我没连 chatgpt
