### ISSUE TITLE
近期遇到的几个bug

### ISSUE THREAD

**Issue by superen7527** [moeakwak/chatgpt-web-share#178]
github有时候上不了，不想魔法。有一些bug就积在一起。总结一下：
1.网络卡顿或者goapi出问题堵塞没回复出来，刷新页面也不会有回复，这个时候谁发消息都会提示有消息正在回答。
解决办法：重启容器
2.上一个问题进化版，不晓得什么原因触发的，也是消息飞出去回答一半卡住了，然后不回答，重启cws和goapi都没有效果。当时等了两天都无法使用一直说有消息正在回答。
解决办法：忘了好像是卸载重装解决的。
3.由于上面这些问题 经常需要重启cws。会发现有时候重启后写好的标题会被清空重置成默认标题(newchat by who)

另外想建议一下 删除对话能不能只在用户数据库移除回到为分配状态。不然有一些问题可能敏感还是干嘛需要排查的时候对话被删除，无法取证，应该都保留在账号上。

**Comment by moeakwak** [comment]
1, 2：尝试更新go-chatgpt-api到最新版本。3 是因为写标题请求不成功。
删除对话后的审计在新版本已经做了，等待下个版本即可。

**Comment by superen7527** [comment]
嗯，是最新版 有时候对话到一半发消息 会出现请选择对话，就觉得可能还有问题，最近也没触发，就提个issue记录一下。偶尔还会1001 刷新一下网页才正常

另外 token过期在gpt-web项目会提示token错误 但是cws只提示502和openai401。能不能优化一下？
