### ISSUE TITLE
docker All-In-One部署的时候go-chatgpt-api报错

### ISSUE THREAD

**Issue by xuepeilei** [moeakwak/chatgpt-web-share#179]
cws-go-chatgpt-api-1  | ERRO[0000] Health check failed: Get "https://chat.openai.com/backend-api/accounts/check": read tcp 172.x.x.x:49816->104.x.x.x:443: read: connection reset by peer 
cws-go-chatgpt-api-1 exited with code 1

**Comment by moeakwak** [comment]
1. 看上去是你ip的问题
2. 关于go-chatgpt-api的问题，请去那边仓库提issue
