### ISSUE TITLE
登录用户名和密码设置

### ISSUE THREAD

**Issue by brian-you98** [moeakwak/chatgpt-web-share#181]
**Version**
v0.x.x

**What's your deploying environment?**
- [√] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
可能问题有点低级，我不知道我的初始用户和密码是什么，在登录页面输入admin、password无法登录
我的初始管理员用户名就是默认的admin，密码就是password没有修改

**Expected behavior**
我需要怎么去设置初始密码或者在哪里能够看到

**Your config.yaml or other configurations**
jwt_secret: "kjds" # 用于生成 jwt token，自行填写随机字符串
jwt_lifetime_seconds: 86400 # jwt token 过期时间
cookie_max_age: 86400 # cookie 过期时间
user_secret: "kjds" # 用于生成用户密码，自行填写随机字符串

sync_conversations_on_startup: true # 是否在启动时同步同步 ChatGPT 对话，建议启用。启用后，将会自动将 ChatGPT 中新增的对话同步到数据库中，并把已经不在 ChatGPT 中的对话标记为无效
create_initial_admin_user: true # 是否创建初始管理员用户
initial_admin_username: admin # 初始管理员用户名
initial_admin_password: password # 初始管理员密码
ask_timeout: 600    # 用于限制对话的最长时间

**Screenshots or running logs**
2023-05-27 23:31:16 2023/05/27 23:31:16.248     INFO: [cws.access] 172.18.0.1:0 | POST /auth/login HTTP/1.1 | 200 OK | 215 ms

**Comment by 1ss4kIT** [comment]
你好，我也同样是这个问题。请问您怎么解决的？

**Comment by brian-you98** [comment]
重装一次就好了
