### ISSUE TITLE
账号被封禁

### ISSUE THREAD

**Issue by zimingzhong** [moeakwak/chatgpt-web-share#182]
这个项目非常好，只是使用这个repo账号被封了，想问有什么方法可以避免这个问题。比如添加多个账号一起使用？

**Comment by aldington-david** [comment]
根据TG统计，你应该首先怀疑账号绑卡的问题

**Comment by moeakwak** [comment]
本次大规模封禁应当与本项目无关，与你使用了虚拟信用卡进行购买有关。

此外，虽然目前没有观察到使用本项目导致封禁的情况，但是项目已经声明过了，风险自担。

**Comment by xpyoung** [comment]
我的号也是，确实是用了某宝商家提供的服务，应该是虚拟信用卡问题，我又去看这店家已经不搞了

**Comment by 6ccg** [comment]
我有在使用 但是没有封禁
