### ISSUE TITLE
希望添加类似官方web端”continue generating“按钮的功能

### ISSUE THREAD

**Issue by Lynnchiya** [moeakwak/chatgpt-web-share#184]
**Is your feature request related to a problem? Please describe.**
在回复长文本的时候经常遇到回复不完整/被打断的问题。 

**Describe the solution you'd like**
[cotinue](https://github.com/moeakwak/chatgpt-web-share/assets/114541165/2f0fb1c4-2fd8-4a8f-bc67-4cdfd651db86)
如图所示。
或者添加类似[KeepChatGPT](https://github.com/xcanwin/KeepChatGPT#%E5%85%B3%E4%BA%8E-%E8%A8%80%E6%97%A0%E4%B8%8D%E5%B0%BD-%E5%8A%9F%E8%83%BD)中”言无不尽“的功能。

**Additional context**
上述插件里“取消审计”“拦截跟踪”以及为对话添加时间戳的功能都相当实用，如果能考虑添加类似功能的话感激不尽。

**Comment by moeakwak** [comment]
现在已经支持合并连续的被断开的消息。你说的“言无不尽”后续会支持。至于取消审计，目前本来就是没有经过审计的api，因此可以算是已经实现的功能。显示消息时间也有了。
