### ISSUE TITLE
分享一份nginx配置代码

### ISSUE THREAD

**Issue by ludashi2020** [moeakwak/chatgpt-web-share#19]
感谢作者的提示，目前这份配置代码在nginx下正常可用。
```
    location /api/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        root /home/wwwroot/chatgpt-web-share/frontend/dist;
        try_files $uri $uri/ /index.html;
    }
```

**Comment by moeakwak** [comment]
谢谢分享。顺便问一下，使用nginx部署，管理后台日志中能否看到真实的请求IP？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月20日 12:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [moeakwak/chatgpt-web-share] 分享一份nginx配置代码 (Issue #19) |

感谢作者的提示，目前这份配置代码在nginx下正常可用。

    location /api/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        root /home/wwwroot/chatgpt-web-share/frontend/dist;
        try_files $uri $uri/ /index.html;
    }

**Comment by ludashi2020** [comment]
> 

可用看到真实的请求ip

**Comment by aldington-david** [comment]
问一下pnpm 构建时提示内存不足崩了前端打包不了怎么办

**Comment by turfintl** [comment]
> 问一下pnpm 构建时提示内存不足崩了前端打包不了怎么办

我乞丐版vps也内存不足，我选择在本地建个高配虚拟机分分钟打包好了上传dist到云端

**Comment by itcuihao** [comment]
启动完，首页我该访问哪个路径呢？http://127.0.0.1:8000/index.html?
