### ISSUE TITLE
最新的代码尝试编译报错 

### ISSUE THREAD

**Issue by caicaicai** [moeakwak/chatgpt-web-share#190]
src/utils/user.ts(34,12): error TS2769: No overload matches this call.
  The last overload gave the following error.

**Comment by caicaicai** [comment]
应该是 https://github.com/moeakwak/chatgpt-web-share/commit/ea0f95fd7f98dad9318d2fb16bd7db4950e6f6d4 提交导致的，我回滚到前一个提交就可以正常编译了。

**Comment by moeakwak** [comment]
最新分支编译失败是正常的，我也不会每次提交都试一下能不能build成功。使用最新的release即可。
