### ISSUE TITLE
Bugs exist in v0.4.0 alpha3.1

### ISSUE THREAD

**Issue by oooldking** [moeakwak/chatgpt-web-share#191]
**Version**
v0.4.0 alpha3.1

**What's your deploying method?**
Docker

**Describe the bug**
1.In GPT-4 browsing mode, the source links of the content are not displayed correctly.

Browsing 的链接显示不正确

2. After deleting the conversation, the content remains stored in MongoDB, but it cannot be displayed in the audit. Upon examining the logic, it appears that the synchronization of the conversation is attempted first, and if it is not found, an error is reported. In actuality, it should first check if the conversation exists in the database.

删除对话后，mongodb里面存有内容，但是管理员账号在面板点击这个对话的时候无法显示，看了一下逻辑是先同步一下这个对话，找不到就报错了，实际应该先查一下db有没有这个对话，这符合审计的逻辑

**To Reproduce**
1. Go to GPT-4 Browsing mode
2. Click a article link
4. See the results

1. Delete a conversation
2. when it was invalid in the admin's dashboard
4. Click the conversation in the admin's dashboard
5. See the error

**Expected behavior**
1. With the right source links as chat.openai.com
2. Check the database first

**Comment by moeakwak** [comment]
此前已修复此问题，谢谢提出，后来忘记回复了
