### ISSUE TITLE
希望在后端中提供一系列可以继承的基类用于对 chatgpt 以外的语言模型进行灵活的二次开发支持

### ISSUE THREAD

**Issue by LuneZ99** [moeakwak/chatgpt-web-share#192]
这个项目可以说是目前使用过的里面体验最好的语言模型 web 应用，所以想提一些功能需求。

现有的各种对话模型项目中有不少模型可以提供相较于 gpt-3.5 更强的对话能力，且没有 gpt-4 的条数限制，其中部分模型还可以在本地部署，开发者也可以在私有数据上进行微调得到非公开模型，相较于 openai 提供的单一服务，这些模型拥有更强的竞争力和安全性。而其他服务商提供的对话 api 例如 google bard、chatglm-130B 等也有各自的优势。

因此，我认为在这个项目中支持其他模型的接入是很有必要的。一种可能的接入其他模型的方案是对目前的 [api](https://github.com/moeakwak/chatgpt-web-share/tree/dev/backend/api/) 等文件夹下的 Chatgpt 相关类进行抽象，编写一个标准的基类（BaseChatManager）并在这个基类中，定义多个需要继承实现的函数，比如 ask / get_conversations 等。然后，OpenAIChatManager、RevChatGPTManager 等类可以继承这个基类，并实现相应的方法。当开发者在该项目基础上接入新的模型时，只需要继承这些基类并实现相应的方法即可。这样就可以非常方便地进行自定义模型的接入。

本人水平较低，提出的方案仅供参考，但这个功能还是很希望作者能实现的，这会极大地拓宽这个项目的应用前景。

**Comment by moeakwak** [comment]
谢谢建议，确实有计划支持多种模型，后续会慢慢完善。

**Comment by LuneZ99** [comment]
看了看，似乎可以直接使用 [langchain](https://github.com/hwchase17/langchain) 来统一不同模型，这个框架很完善而且有比较高热度的社区支持
