### ISSUE TITLE
web端请求路径固定为ip？是否可以修改？

### ISSUE THREAD

**Issue by BlackUsteak** [moeakwak/chatgpt-web-share#194]
当我部署在服务器上时，web端请求路径始终是ip地址，如果我拥有自己域名，我该如何修改请求路径？

**Comment by moeakwak** [comment]
请使用正确的反向代理，如nginx或者caddy进行配置

**Comment by BlackUsteak** [comment]
我已经配置了nginx，能够正常的从域名进入网页，但是进入网页后登录请求路径是ip地址。

**Comment by moeakwak** [comment]
前端默认是向 /api/ 进行请求，并没有硬编码ip地址。你这种情况可能是反代配置不正确。

如果使用docker，应该不会有这种情况。
