### ISSUE TITLE
502ChatGPT返回错误:OpenAI 401

### ISSUE THREAD

**Issue by itgoyo** [moeakwak/chatgpt-web-share#195]
**Version**
v0.4.0-alpha2

**What's your deploying method?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**

之前还好好的，现在已进入会话窗口就报错

![image](https://github.com/moeakwak/chatgpt-web-share/assets/23348551/f40c890d-e95e-4ab6-901f-a46666100d2d)

自己的账号在`https://chat.openai.com/`

上面的表现是好的

**Comment by moeakwak** [comment]
你的 access token 过期了

**Comment by itgoyo** [comment]
好嘞感谢小伙伴
