### ISSUE TITLE
OpenaiWebException: 403 {"detail":"Our systems have detected unusual activity from your system. Please try again later."}

### ISSUE THREAD

**Issue by tongxinrang** [moeakwak/chatgpt-web-share#198]
版本：**v0.4.0-alpha3.1**
你使用的部署方式是？
- [x]  Docker
- [ ] Caddy
- [ ] 其他

**描述问题**
服务器是在推荐的**Racknerd**，
使用GPT4出现 OpenaiWebException: 403 {"detail":"Our systems have detected unusual activity from your system. Please try again later."}
但是使用GPT3.5没有问题

1.尝试使用chatgpt-proxy-server-warp，情况也是一样。
2.尝试重新登录获取accessToken，情况也是一样。
3.尝试等待超过12小时，情况也是一样。
4.直接登录到ChatGPT官网，能够正常使用。

屏幕截图或运行日志
![image](https://github.com/moeakwak/chatgpt-web-share/assets/135097736/2efe83a9-6221-403b-85c7-fb3c41f11278)

**Comment by jk1ash** [comment]
昨天碰到类似问题，排查了应该是go-chatgpt-api的问题，把docker-compose的CHATGPT_BASE_URL留空，使用内置的公共代理可暂时恢复。

**Comment by tongxinrang** [comment]
@jk1ash 谢谢帮助，已经尝试，问题仍存在
![image](https://github.com/moeakwak/chatgpt-web-share/assets/135097736/deb8e85b-11bf-48c2-a596-e467bdda8e03)
![image](https://github.com/moeakwak/chatgpt-web-share/assets/135097736/81253b17-dab6-433d-9f12-0d2535a2e43c)

**Comment by moeakwak** [comment]
目前，使用 moeakwak/go-chatgpt-api 正常，最新版的 go-chatgpt-api 也应当能够使用。

**Comment by HLiamso** [comment]
> > 目前，使用 moeakwak/go-chatgpt-api 正常，最新版的 go-chatgpt-api 也应当能够使用。
> 
> 刚刚拉取CWS-DEV-latest和go-api-latest，无法正常使用 ![image](https://user-images.githubusercontent.com/45396667/247543368-beadc7f1-32e7-4ae3-b065-4b50152348be.png)

![image](https://github.com/moeakwak/chatgpt-web-share/assets/45396667/0e8b5923-64b0-45c3-80c6-2fa9f9dbe53a)
看起来需要cws需要做新版本的适配，或者使用旧版本的goapi
