### ISSUE TITLE
部署完后提示错误 1006

### ISSUE THREAD

**Issue by 517325862** [moeakwak/chatgpt-web-share#2]
![image](https://user-images.githubusercontent.com/76882395/224471991-ac8727a1-ae20-485e-8d5d-96595b0d2e71.png)

**Comment by moeakwak** [comment]
提供一下容器日志和config.yaml

**Comment by 517325862** [comment]
容器日志：
{"level":"info","ts":1678522486.0057504,"msg":"using provided configuration","config_file":"/app/Caddyfile","config_adapter":"caddyfile"}
{"level":"info","ts":1678522486.0083666,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"warn","ts":1678522486.0091918,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
{"level":"info","ts":1678522486.0093608,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00034b1f0"}
{"level":"info","ts":1678522486.0097861,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1678522486.0098536,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/root/.local/share/caddy"}
{"level":"info","ts":1678522486.0100465,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1678522486.0100863,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
{"level":"info","ts":1678522486.0100968,"msg":"serving initial configuration"}
Successfully started Caddy (pid=22) - Caddy is running in the background
INFO:     Started server process [36]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
User 1 has registered.
User created: 
对话同步完成
INFO:     192.168.2.183:0 - "POST /auth/login HTTP/1.1" 200 OK
INFO:     192.168.2.183:0 - "GET /user/me HTTP/1.1" 200 OK
INFO:     192.168.2.183:0 - "GET /user HTTP/1.1" 200 OK
User 2 has registered.
INFO:     192.168.2.183:0 - "POST /auth/register HTTP/1.1" 201 Created
INFO:     192.168.2.183:0 - "GET /user HTTP/1.1" 200 OK
INFO:     192.168.2.183:0 - "POST /auth/logout HTTP/1.1" 200 OK
INFO:     192.168.2.183:0 - "POST /auth/login HTTP/1.1" 200 OK
INFO:     192.168.2.183:0 - "GET /user/me HTTP/1.1" 200 OK
INFO:     192.168.2.183:0 - "GET /conv?valid_only=true HTTP/1.1" 200 OK
{"level":"info","ts":1678620201.2314718,"msg":"using provided configuration","config_file":"/app/Caddyfile","config_adapter":"caddyfile"}
{"level":"info","ts":1678620201.2374525,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"info","ts":1678620201.241082,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000468d90"}
{"level":"warn","ts":1678620201.241241,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
{"level":"info","ts":1678620201.2471445,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1678620201.2558334,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/root/.local/share/caddy"}
{"level":"info","ts":1678620201.2559276,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1678620201.2559986,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
{"level":"info","ts":1678620201.2560308,"msg":"serving initial configuration"}
Successfully started Caddy (pid=23) - Caddy is running in the background
INFO:     Started server process [39]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
Create User admin Error: 用户名已存在
对话同步完成
INFO:     192.168.2.183:0 - "POST /auth/login HTTP/1.1" 200 OK
INFO:     192.168.2.183:0 - "POST /auth/login HTTP/1.1" 200 OK
INFO:     192.168.2.183:0 - "GET /user/me HTTP/1.1" 200 OK
INFO:     192.168.2.183:0 - "GET /conv?valid_only=true HTTP/1.1" 200 OK

config.yaml：
![image](https://user-images.githubusercontent.com/76882395/224541744-ee61eb6b-a0d9-4864-9331-693b1fab2cd2.png)

**Comment by moeakwak** [comment]
试试 ghcr.io/moeakwak/chatgpt-web-share:0.1.2版本的镜像，应该已修复。

**Comment by 517325862** [comment]
问题已解决
