### ISSUE TITLE
chatgpt回复大量文字中断回复时,能够继续未完成的回答

### ISSUE THREAD

**Issue by RexLee0929** [moeakwak/chatgpt-web-share#203]
在提出的问题时chatgpt应该回复大量文本的时候在webshare中将会直接中断
![image](https://github.com/moeakwak/chatgpt-web-share/assets/62170324/c35db531-2c27-447a-b578-c68c87e684bf)

在官方的和潘多拉都能够出现一个继续回答的按钮
![image](https://github.com/moeakwak/chatgpt-web-share/assets/62170324/c4a82dc0-21b7-4707-995f-b9ee1f65624d)

希望可以增加继续回复的功能

**Comment by moeakwak** [comment]
alpha 版本已支持
