### ISSUE TITLE
Auto renaming conversations just like ChatGPT web

### ISSUE THREAD

**Issue by i207M** [moeakwak/chatgpt-web-share#204]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
ChatGPT will name the conversation after one or two questions. Is it viable to fetch the new name and apply it?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by spammenotinoz** [comment]
This should be closed, as it is implemented in Alpha7

**Comment by i207M** [comment]
Cool, thanks
