### ISSUE TITLE
go-chatgpt-api 破坏性更新，接口改了，需要同步更新本项目接口

### ISSUE THREAD

**Issue by colin4k** [moeakwak/chatgpt-web-share#206]
2023-06-18 破坏性更新
原接口： http://go-chatgpt-api:8080/chatgpt/conversation

更新后： http://go-chatgpt-api:8080/chatgpt/backend-api/conversation

常用的 ChatGPT 接口主要是加了 /backend-api 的配置，另外添加了 /public-api 的支持（虽然这种 API 目前来看可以直连，也不知有何用）

收费 API 则不受影响

**Comment by Li-Lab-SJTU** [comment]
你好，请问这个更新的意思是把CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/改为CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/backend-api/吗？
目前改完并docker-compose重启之后，依然不能通过web share使用GPT4模型，会报错”获取回复失败 [1001] ChatGPT返回错误“。在服务器测试nslookup go-chatgpt-api也会返回”** server can't find go-chatgpt-api: NXDOMAIN“错误，请问该怎么解决呢？
![image](https://github.com/moeakwak/chatgpt-web-share/assets/46808768/fd0a391e-3ee5-42e7-8532-4e9138b75d5b)

**Comment by colin4k** [comment]
> 你好，请问这个更新的意思是把CHATGPT_BASE_URL=[http://go-chatgpt-api:8080/chatgpt/改为CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/backend-api/吗？](http://go-chatgpt-api:8080/chatgpt/%E6%94%B9%E4%B8%BACHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/backend-api/%E5%90%97%EF%BC%9F) 目前改完并docker-compose重启之后，依然不能通过web share使用GPT4模型，会报错”获取回复失败 [1001] ChatGPT返回错误“。在服务器测试nslookup go-chatgpt-api也会返回”** server can't find go-chatgpt-api: NXDOMAIN“错误，请问该怎么解决呢？ ![image](https://user-images.githubusercontent.com/46808768/247039741-fd0a391e-3ee5-42e7-8532-4e9138b75d5b.png)

建议你把go-chatgpt-api回退到之前的版本

**Comment by Li-Lab-SJTU** [comment]
谢谢，我又查找到了正在讨论的相同问题，GPT4目前使用go-chatgpt-api会有异常报错，可能确实需要更换其它的api代理
#https://github.com/linweiyuan/go-chatgpt-api/issues/161
#https://github.com/moeakwak/chatgpt-web-share/issues/198

**Comment by 6ccg** [comment]
个人测试 go-chatgpt-api 6.18以前的版本可以正常使用gpt4和4m
但是browsing和plugin用不了 提示403 Our systems have detected unusual activity from your system. Please try again later.

如果用的是docker-compose 可以考虑不更新这个镜像

**Comment by colin4k** [comment]
> 个人测试 go-chatgpt-api 6.18以前的版本可以正常使用gpt4和4m 但是browsing和plugin用不了 提示403 Our systems have detected unusual activity from your system. Please try again later.
> 
> 如果用的是docker-compose 可以考虑不更新这个镜像

是的，我就是回退到了之前的版本

**Comment by Oliva630** [comment]
你好，请问已经更新之后发现出了问题，该怎么回退linweiyuan/go-chatgpt-api的版本呢？现在查看之前版本的tag是none，在docker hub上搜索也只剩latest版本了，在docker-compose.yml 中改为之前的版本会报错如：
docker-compose up -d
  Creating network "cws_default" with the default driver
  Pulling go-chatgpt-api (linweiyuan/go-chatgpt-api:05acd16484fe)...
  ERROR: manifest for linweiyuan/go-chatgpt-api:05acd16484fe not found: manifest unknown: manifest unknown
感谢你的帮助！

**Comment by colin4k** [comment]
> 你好，请问已经更新之后发现出了问题，该怎么回退linweiyuan/go-chatgpt-api的版本呢？现在查看之前版本的tag是none，在docker hub上搜索也只剩latest版本了，在docker-compose.yml 中改为之前的版本会报错如： docker-compose up -d Creating network "cws_default" with the default driver Pulling go-chatgpt-api (linweiyuan/go-chatgpt-api:05acd16484fe)... ERROR: manifest for linweiyuan/go-chatgpt-api:05acd16484fe not found: manifest unknown: manifest unknown 感谢你的帮助！

先通过`docker tag`命令为tag为none的镜像打上标签（可自己任意指定一个），然后再docker-compose.yml中指定使用你前面定义的tag即可

**Comment by linweiyuan** [comment]
@Li-Lab-SJTU 很明显你发出来的文字写的是 `/chatgpt/backend-api/`，但是图片里的配置用的是 `chatgpt/public-api/`，改为前者即可，GPT-4 的 403 不知道怎么处理
