### ISSUE TITLE
配置cdn导致账号和聊天记录的问题

### ISSUE THREAD

**Issue by dxlxxx** [moeakwak/chatgpt-web-share#207]
会出现我已经删除的内容，有时候又会登录到admin账号去
![image](https://github.com/moeakwak/chatgpt-web-share/assets/67138758/9426ce58-ffe2-4255-b9ba-e5d333b826d4)

**Comment by moeakwak** [comment]
一般来说不会出现这种情况。你提供的信息有限，我无法进一步分析原因。

**Comment by dxlxxx** [comment]
> 一般来说不会出现这种情况。你提供的信息有限，我无法进一步分析原因。
嗯，我用ip访问没有cdn加速就不会出现这个问题，就是cdn缓存的问题，这个项目是不是不能支持cdn还是说我cdn没有配置正确
