### ISSUE TITLE
有人成功在免费容器平台部署吗

### ISSUE THREAD

**Issue by souvenp** [moeakwak/chatgpt-web-share#210]
**Is your feature request related to a problem? Please describe.**
Render，flyio，koyeb....我试着直接部署显然易见地失败了🥰
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by h1xy** [comment]
容器平台都需要开发者做适配才行的，不能直接上

**Comment by moeakwak** [comment]
项目其实不太适合容器平台，不建议使用
