### ISSUE TITLE
增加一个配置项，可以传入js代码

### ISSUE THREAD

**Issue by V1V1rus** [moeakwak/chatgpt-web-share#214]
希望在设置中添加一个输入框，可以用户自定义插入js代码。

方便在web端放入类似Umami的探针，记录网络请求数据。

**Comment by cmlibo** [comment]
可以改代码，自己build的

**Comment by V1V1rus** [comment]
> 可以改代码，自己build的

docker部署的。。。每次更新都是痛苦折磨。。。

**Comment by cmlibo** [comment]
我也是docker部署的，自己build，然后改下dockerfile就可以了

Virus ***@***.***> 于2023年6月27日周二 21:03写道：

**Comment by moeakwak** [comment]
前端是静态的，因此没有办法在后端动态增加js代码。这种情况只能够自己定制自己编译了。
