### ISSUE TITLE
('xxx.xxx.xxx.xxx', 0) - "WebSocket /chat" [accepted]

### ISSUE THREAD

**Issue by huoshicang** [moeakwak/chatgpt-web-share#222]
**Version**
0.4.0-alpha4.2

**What's your deploying method?**
- [ √ ] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
![image](https://github.com/moeakwak/chatgpt-web-share/assets/74391377/9b75cdcd-2520-48bd-bb7d-5d0f23c964be)

**To Reproduce**
1. 转到页面，发起对话
2. 没有返回
3. 查看日志

**Expected behavior**
能够正常对话即可

**Your config.yaml or other configurations**
![image](https://github.com/moeakwak/chatgpt-web-share/assets/74391377/700a1c6d-5d96-42e0-befa-b66bd2a4c1fb)
![image](https://github.com/moeakwak/chatgpt-web-share/assets/74391377/020f4717-9115-433b-9193-4f9bae761083)

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by moeakwak** [comment]
chatgpt_base_url 使用外部能直接访问到的 ip 地址，不要使用 http://go-chatgpt-api 这样的地址。

还有问题的话请在群里提问。
