### ISSUE TITLE
通过ip正常访问但是caddy配置不对

### ISSUE THREAD

**Issue by Nothingness-Void** [moeakwak/chatgpt-web-share#223]
**Version**
最新版

**What's your deploying environment?**
- [ X] Docker
- [ X] Caddy
- [ ] Other

**Describe the problem**
无法配置caddy ，已正常部署web-share，通过ip能够访问，docker-compose.yml参考了之前issue里大佬分享的带caddy的配置，配置文件如下
![image](https://github.com/moeakwak/chatgpt-web-share/assets/55913486/b8f9561d-ab36-41a3-855f-f652ccb12c9b)
但是无法通过配置的域名访问，域名已通过cf A记录到ip

**Screenshots or running logs**
docker-compose logs命令看到的caddy报错如下
![image](https://github.com/moeakwak/chatgpt-web-share/assets/55913486/c3b077f6-bac9-4a20-a31f-cfa5ed60e15a)
希望各位大佬指点一下

**Additional context**

**Comment by moeakwak** [comment]
关于外部 caddy 的配置请自行解决，或在群里询问，
