### ISSUE TITLE
AssertionError: model_ask_count is None

### ISSUE THREAD

**Issue by ser-tec** [moeakwak/chatgpt-web-share#225]
**Version**
v0.4.0-alpha4.4 (with last change from github db74d2dd7d28f34e7872553fce75c4f0b3cae211)

**What's your deploying method?**
- [X] Docker
- [X] Caddy
- [ ] Other

**Describe the bug**
when you send a message you get the reply but after a few seconds it appears WebSocket error 1006: unknown mistake

**To Reproduce**
- message in a chat

**Your config.yaml or other configurations**
config.yaml
```
openai_web:
  is_plus_account: true
  chatgpt_base_url: http://go-chatgpt-api:8080/chatgpt/backend-api/
  proxy:
  common_timeout: 10
  ask_timeout: 600
openai_api:
  openai_base_url: https://api.openai.com/v1/
  proxy:
  connect_timeout: 10
  read_timeout: 20
common:
  print_sql: false
  create_initial_admin_user: true
  initial_admin_user_username: admin
  initial_admin_user_password: **********
  sync_conversations_on_startup: true
  sync_conversations_regularly: true
http:
  host: 127.0.0.1
  port: 8000
  cors_allow_origins:
  - http://localhost
  - http://127.0.0.1
  - http://192.168.1.77
data:
  data_dir: ./data
  database_url: sqlite+aiosqlite:///data/database.db
  mongodb_url: mongodb://cws:**********@mongo:27017
  run_migration: false
auth:
  jwt_secret: **********
  jwt_lifetime_seconds: 86400
  cookie_max_age: 86400
  cookie_name: user_auth
  user_secret: **********
stats:
  ask_stats_ttl: 7776000
  request_stats_ttl: 2592000
  request_stats_filter_keywords:
  - /status
log:
  console_log_level: INFO
```

docker-compose
```
services:
  chatgpt-share:
    image: giuliogpt:4.4
    container_name: cws
    restart: unless-stopped
    ports:
      - 8000:80 # web
    volumes:
      - ./data:/app/backend/data
      - ./Caddyfile:/app/Caddyfile
    environment:
      - TZ=Europe/Rome
      - CWS_CONFIG_DIR=/app/backend/data/config
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/backend-api/
    depends_on:
      - mongo
      - go-chatgpt-api

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - 27012:27012
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cws
      MONGO_INITDB_ROOT_USERNAME: cws
      MONGO_INITDB_ROOT_PASSWORD: ***********

  go-chatgpt-api:
    image: linweiyuan/go-chatgpt-api:latest
    ports:
      - 6060:8080
    environment:
      - GIN_MODE=release
      - GO_CHATGPT_API_ARKOSE_TOKEN_URL=https://arkose-token.linweiyuan.com
    restart: unless-stopped
```

Caddyfile 
```:80 {
        handle_path /api/* {
                reverse_proxy localhost:8000
        }
        handle /* {
                file_server
                root * /app/dist
                try_files {path} /index.html
        }
}
```

**Screenshots or running logs**
```
2023/07/11 11:45:17.384     INFO: [uvicorn.error]	Started server process [1]
2023/07/11 11:45:17.384     INFO: [uvicorn.error]	Waiting for application startup.
2023/07/11 11:45:17.386     INFO: [alembic.runtime.migration]	Context impl SQLiteImpl.
2023/07/11 11:45:17.386     INFO: [alembic.runtime.migration]	Will assume non-transactional DDL.
2023/07/11 11:45:17.388     INFO: [cws.api.database.sqlalchemy]	database initialized
2023/07/11 11:45:17.403     INFO: [cws.api.database.mongodb]	MongoDB initialized. dataSize: 0.01 MB, objects: 16
2023/07/11 11:45:17.419     INFO: [cws.main]	admin already exists, skip creating admin user
2023/07/11 11:45:17.422     INFO: [cws.main]	Using http://go-chatgpt-api:8080/chatgpt/backend-api/ as ChatGPT base url
2023/07/11 11:45:17.423     INFO: [cws.utils.admin.sync_conv]	Syncing conversations...
2023/07/11 11:45:18.067     INFO: [cws.utils.admin.sync_conv]	Fetched 1 conversations from ChatGPT account.
2023/07/11 11:45:18.069  WARNING: [cws.utils.admin.sync_conv]	Cannot fetch conversation [Aggiungi configurazione proxy Caddy.](a3221c47-5e75-46dc-a1f8-61c6aaa0bc7d)
2023/07/11 11:45:18.069  WARNING: [cws.utils.admin.sync_conv]	Cannot fetch conversation [Configurazione Caddy per WebSocket](51643210-a18e-4d9b-a6b6-9f94977ee7d4)
2023/07/11 11:45:18.070     INFO: [cws.utils.admin.sync_conv]	Conversation [Check Syslog](f1ac8fee-830f-49be-97be-37278b675f73) not recorded, added to database
2023/07/11 11:45:18.081     INFO: [cws.utils.admin.sync_conv]	Sync conversations finished.
2023/07/11 11:45:18.081     INFO: [cws.main]	Sync conversations regularly enabled, will sync conversations every 12 hours.
2023/07/11 11:45:18.082     INFO: [uvicorn.error]	Application startup complete.
2023/07/11 11:45:18.082     INFO: [uvicorn.error]	Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2023/07/11 11:46:14.625     INFO: [cws.access]	192.168.4.4:0 | GET /user/me HTTP/1.1 | 200 OK | 6 ms
2023/07/11 11:46:14.661     INFO: [cws.access]	192.168.4.4:0 | POST /auth/logout HTTP/1.1 | 200 OK | 3 ms
2023/07/11 11:46:37.275     INFO: [cws.access]	192.168.4.4:0 | POST /auth/login HTTP/1.1 | 200 OK | 194 ms
2023/07/11 11:46:37.300     INFO: [cws.access]	192.168.4.4:0 | GET /user/me HTTP/1.1 | 200 OK | 18 ms
2023/07/11 11:46:37.542     INFO: [cws.access]	192.168.4.4:0 | GET /system/info HTTP/1.1 | 200 OK | 56 ms
2023/07/11 11:46:37.560     INFO: [cws.access]	192.168.4.4:0 | GET /system/stats/request?granularity=1800 HTTP/1.1 | 200 OK | 72 ms
2023/07/11 11:46:37.585     INFO: [cws.access]	192.168.4.4:0 | GET /user HTTP/1.1 | 200 OK | 95 ms
2023/07/11 11:46:37.594     INFO: [cws.access]	192.168.4.4:0 | GET /system/stats/ask?granularity=1800 HTTP/1.1 | 200 OK | 105 ms
2023/07/11 11:46:44.298     INFO: [cws.access]	192.168.4.4:0 | GET /user HTTP/1.1 | 200 OK | 16 ms
2023/07/11 11:46:46.028     INFO: [cws.access]	192.168.4.4:0 | GET /conv/all?valid_only=false HTTP/1.1 | 200 OK | 16 ms
2023/07/11 11:46:50.146     INFO: [cws.access]	192.168.4.4:0 | GET /conv HTTP/1.1 | 200 OK | 16 ms
2023/07/11 11:47:03.159     INFO: [uvicorn.error]	('192.168.4.4', 0) - "WebSocket /chat" [accepted]
2023/07/11 11:47:03.160     INFO: [uvicorn.error]	connection open
2023/07/11 11:47:03.162     INFO: [cws.api.routers.chat]	admin connected to websocket
2023/07/11 11:47:23.482    DEBUG: [cws.api.routers.chat]	finished ask 26950ac7-4dbe-4278-b2c1-ee1b182a5d25 (gpt_3_5), user: 1, ask: 20.268s, total: 20.268s
2023/07/11 11:47:25.234    ERROR: [uvicorn.error]	Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/app/backend/api/middlewares/asgi_logger/middleware.py", line 47, in __call__
    return await self.app(scope, receive, send)  # pragma: no cover
  File "/app/backend/api/middlewares/request_statistics.py", line 59, in __call__
    raise exc
  File "/app/backend/api/middlewares/request_statistics.py", line 57, in __call__
    await self.app(scope, receive, send_with_inspecting_body)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/app/backend/api/routers/chat.py", line 510, in chat
    assert model_ask_count, "model_ask_count is None"
AssertionError: model_ask_count is None
2023/07/11 11:47:25.235    ERROR: [uvicorn.error]	closing handshake failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/server.py", line 248, in handler
    await self.close()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 766, in close
    await self.write_close_frame(Close(code, reason))
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1232, in write_close_frame
    await self.write_frame(True, OP_CLOSE, data, _state=State.CLOSING)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1205, in write_frame
    await self.drain()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1194, in drain
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
2023/07/11 11:47:25.236     INFO: [uvicorn.error]	connection closed
2023/07/11 11:47:25.269     INFO: [cws.access]	192.168.4.4:0 | GET /user/me HTTP/1.1 | 200 OK | 15 ms
2023/07/11 11:47:31.095     INFO: [cws.access]	192.168.4.4:0 | GET /system/stats/request?granularity=1800 HTTP/1.1 | 200 OK | 35 ms
2023/07/11 11:47:31.104     INFO: [cws.access]	192.168.4.4:0 | GET /user HTTP/1.1 | 200 OK | 44 ms
2023/07/11 11:47:31.106     INFO: [cws.access]	192.168.4.4:0 | GET /system/info HTTP/1.1 | 200 OK | 48 ms
2023/07/11 11:47:31.137     INFO: [cws.access]	192.168.4.4:0 | GET /system/stats/ask?granularity=1800 HTTP/1.1 | 200 OK | 76 ms
```

![image](https://github.com/moeakwak/chatgpt-web-share/assets/113360845/04885363-1f79-45fe-8fb4-4af99d3184d2)

**Comment by moeakwak** [comment]
Did you upgrade directly from the previous version? If so, you need to delete database.db to clear data.

**Comment by ser-tec** [comment]
it's not an upgrade, i clone github repo, docker built, and then docker compose. 
Anyway i try to delate all data (database and mongo folder)
from log it says 
DEBUG: [cws.api.routers.chat]	finished ask 4e965e0a-d8eb-43d4-91b5-aa34c5bd3c40 (gpt_3_5), user: 1, ask: 3.654s, total: 3.654s
and then ERROR: [uvicorn.error]	Exception in ASGI application.
it seems linked to File "/app/backend/api/routers/chat.py", line 510, in chat assert model_ask_count, "model_ask_count is None"

**Comment by ser-tec** [comment]
ValueError: model_ask_count is None. Model: gpt_3_5 may not exist.

**Comment by zekripedia** [comment]
I experienced the same thing

**Comment by ser-tec** [comment]
moreover, in the chat management it cannot identify the model. it seems related

![image](https://github.com/moeakwak/chatgpt-web-share/assets/113360845/b961f1e9-c7ac-4723-b223-6d05f7d8da6d)

**Comment by ser-tec** [comment]
if i roolback to the Commits on Jul 2, 2023 [fix: message row right margin](https://github.com/ser-tec/chatgpt-web-share/commit/bf21f65de1a43adbcc525d4a370d01551f35a780) it works  
From the next commit [feat: set global enabled models and model codes](https://github.com/ser-tec/chatgpt-web-share/commit/64d1d226f0c9c2e141f84868639a34a3ed2868b0) it returns error 
in particular it initially says Failed to get reply errors.userNotAllowToUseModel and and continuing with subsequent commits leads to the error assert model_ask_count, "model_ask_count is None"

**Comment by maxduke** [comment]
> if i roolback to the Commits on Jul 2, 2023 [fix: message row right margin](https://github.com/ser-tec/chatgpt-web-share/commit/bf21f65de1a43adbcc525d4a370d01551f35a780) it works From the next commit [feat: set global enabled models and model codes](https://github.com/ser-tec/chatgpt-web-share/commit/64d1d226f0c9c2e141f84868639a34a3ed2868b0) it returns error in particular it initially says Failed to get reply errors.userNotAllowToUseModel and and continuing with subsequent commits leads to the error assert model_ask_count, "model_ask_count is None"

I also rollbacked to this commit, it works now.

**Comment by maxduke** [comment]
I've created PR https://github.com/moeakwak/chatgpt-web-share/pull/242 to fix this

**Comment by ser-tec** [comment]
i'm testing, it seems to work. Thanks you

**Comment by ser-tec** [comment]
> I've created PR #242 to fix this
i'm testing, it seems to work. Thanks you

**Comment by ser-tec** [comment]
> I've created PR #242 to fix this

i'm testing, it seems to work. Thanks you

**Comment by tyhunter** [comment]
have the same issue, i checked logs it's the same error https://github.com/moeakwak/chatgpt-web-share/issues/255
Currently, using the default admin account allows for saving conversations without errors. However, when a new user initiates a conversation, they can communicate successfully. Still, after ChatGPT replies, it prompts “WebSocket 1006: Unknown Error,” and refreshing the page does not save the conversation.

2023/09/09 15:22:56.741     INFO: [cws.api.routers.chat]	tyhunter connected to websocket
2023/09/09 15:23:05.524    DEBUG: [cws.api.routers.chat]	finished ask aff7a19c-7dd1-415e-92ee-97fc44f5dadb (gpt_3_5), user: 2, ask: 8.52s, total: 8.52s
2023/09/09 15:23:05.643    ERROR: [uvicorn.error]	Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/app/backend/api/middlewares/asgi_logger/middleware.py", line 47, in __call__
    return await self.app(scope, receive, send)  # pragma: no cover
  File "/app/backend/api/middlewares/request_statistics.py", line 59, in __call__
    raise exc
  File "/app/backend/api/middlewares/request_statistics.py", line 57, in __call__
    await self.app(scope, receive, send_with_inspecting_body)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/app/backend/api/routers/chat.py", line 510, in chat
    assert model_ask_count, "model_ask_count is None"
AssertionError: model_ask_count is None
2023/09/09 15:23:05.645    ERROR: [uvicorn.error]	closing handshake failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/server.py", line 248, in handler
    await self.close()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 766, in close
    await self.write_close_frame(Close(code, reason))
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1232, in write_close_frame
    await self.write_frame(True, OP_CLOSE, data, _state=State.CLOSING)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1205, in write_frame
    await self.drain()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1194, in drain
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
2023/09/09 15:23:05.645     INFO: [uvicorn.error]	connection closed
2023/09/09 15:23:05.914     INFO: [cws.access]	158.101.28.136:0 | GET /user/me HTTP/1.1 | 200 OK | 21 ms
2023/09/09 15:25:01.422     INFO: [cws.access]	158.101.28.136:0 | GET /user/me HTTP/1.1 | 200 OK | 21 ms
2023/09/09 15:25:02.769     INFO: [cws.access]	158.101.28.136:0 | GET /conv HTTP/1.1 | 200 OK | 24 ms
2023/09/09 15:25:03.059     INFO: [cws.access]	158.101.28.136:0 | GET /user/me HTTP/1.1 | 200 OK | 20 ms
2023/09/09 15:25:03.362     INFO: [cws.access]	158.101.28.136:0 | GET /conv HTTP/1.1 | 200 OK | 22 ms
2023/09/09 15:25:05.286     INFO: [cws.access]	158.101.28.136:0 | GET /conv/d4eb925a-5e06-41a2-93b0-778ae6294e66 HTTP/1.1 | 200 OK | 299 ms
2023/09/09 15:25:09.133     INFO: [uvicorn.error]	('158.101.28.136', 0) - "WebSocket /chat" [accepted]
2023/09/09 15:25:09.135     INFO: [uvicorn.error]	connection open
2023/09/09 15:25:09.139     INFO: [cws.api.routers.chat]	admin connected to websocket
2023/09/09 15:25:18.815    DEBUG: [cws.api.routers.chat]	finished ask d4eb925a-5e06-41a2-93b0-778ae6294e66 (gpt_3_5), user: 1, ask: 9.409s, total: 9.409s
2023/09/09 15:25:19.061     INFO: [uvicorn.error]	connection closed
2023/09/09 15:25:19.342     INFO: [cws.access]	158.101.28.136:0 | GET /conv HTTP/1.1 | 200 OK | 23 ms
2023/09/09 15:25:19.734     INFO: [cws.access]	158.101.28.136:0 | GET /user/me HTTP/1.1 | 200 OK | 32 ms

**Comment by tyhunter** [comment]
may i ask have solved this problem in finally
