### ISSUE TITLE
Arm的服务器无法部署

### ISSUE THREAD

**Issue by just-wkj** [moeakwak/chatgpt-web-share#233]
**Version**
v0.x.x

**What's your deploying environment?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
A clear and concise description of your problem.

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by moeakwak** [comment]
项目暂时不会出arm的docker镜像。可以自己从源码编译和部署。
