### ISSUE TITLE
fakeopen 已支持 ChatGPT 转 Turbo API  大佬们看看咋弄能对接一下啊

### ISSUE THREAD

**Issue by jonntd** [moeakwak/chatgpt-web-share#237]
https://github.com/pengzhile/pandora/issues/837
这个服务旨在模拟 Turbo API，免费且使用的是ChatGPT的8k模型。
首先到 https://ai.fakeopen.com/token 去生成一个fk-开头的Share Token。
然后用这个fk-xxx去请求 https://ai.fakeopen.com/v1/chat/completions 即可用免费体验Turbo API了。
请求和返回参数完全兼容。ChatGPT同时只有1条会话的限制也是存在的。
Share Token当然不只是可以这么用，还可以在使用ChatGPT时当作Access Token使用，这个自己去探索吧。
https://ai.fakeopen.com/v1/chat/completions 是完整反代，还可用sk-xxx或Access Token请求，会扣OpenAI额度。
对于相同的Unique Name和相同用户的Access Token，生成的Share Token总是相同的。这点对于续期非常方便。
新推出Share Token池服务：https://ai.fakeopen.com/pool，多账号来解决并发问题。
这里还有个自动生成的脚本：https://gist.github.com/pengzhile/448bfcfd548b3ae4e665a84cc86c4694
Pandora的API模式也已支持Share Token和Pool Token，这次API免费了。
其中ChatGPT和Turbo API模型映射关系为：

image
2023-06-19 更新：Share Token 已支持会话隔离。 https://github.com/pengzhile/pandora/issues/927
2023-06-24 更新：Share Token 日生成数扩充至 100 个。
2023-06-24 更新：Pool Token 容量已扩充至 100 个，且可 Share Token 和官方 Api Key 混排。
2023-06-24 更新：两个免费用 Pool Token，感谢群里用自己号组池子的热心网友。
pk-this-is-a-real-free-pool-token-for-everyone 很多 Share Token 组成的池子。
pk-this-is-a-real-free-api-key-pk-for-everyone 一些120刀 Api Key组成的池子。

**Comment by Rodert** [comment]
moeakwak/chatgpt-web-share 和 /pengzhile/pandora 如何整合起来呢？

**Comment by 0xNekoo** [comment]
> commented

请问这个pk-this-is-a-real-free-pool-token-for-everyone 很多 Share Token 组成的池子。
在哪能获取到这个api-key呢
