### ISSUE TITLE
docker4.4版本，安卓手机网页使用不适配，对话记录网页被写死了，不能上下滑动对话

### ISSUE THREAD

**Issue by soyisou** [moeakwak/chatgpt-web-share#241]
docker4.4版本，安卓手机网页使用不适配，对话记录网页被写死了，不能上下滑动对话

**Comment by RogerPu** [comment]
我用安卓webview也是同样问题

**Comment by moeakwak** [comment]
在最新版本以及最新的webview没有此问题。旧版本的程序，以及较老版本的webview或者safari浏览器可能会有问题，这个就没有办法了。
