### ISSUE TITLE
OpenAI: {} (code: 403)

### ISSUE THREAD

**Issue by tb2-sy** [moeakwak/chatgpt-web-share#244]
**Version**
v0.3.15

**What's your deploying method?**
- [1] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
gpt3.5正常使用，无法使用gpt4，log文件报错 **OpenAI: {} (code: 403)**
web-share界面报错 **[1001] ChatGPT返回错误**
**To Reproduce**

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by funny-cat-happy** [comment]
主要问题是原文档chatgpt_base_url不对，不过就算你输入对了也会因为sse接口改了无法使用，按照我在 https://github.com/moeakwak/chatgpt-web-share/issues/240 提出的临时镜像重新用吧
