### ISSUE TITLE
How are conversations stored?

### ISSUE THREAD

**Issue by ser-tec** [moeakwak/chatgpt-web-share#246]
Hi,
Can someone explain to me how conversation storage in db works?
I would like to keep them even if they are deleted from chat.openai.com

Thanks you.

**Comment by jurieo** [comment]
> Hi, Can someone explain to me how conversation storage in db works? I would like to keep them even if they are deleted from chat.openai.com
> 
> Thanks you.

Stored in mongodb

**Comment by spammenotinoz** [comment]
> > Hi, Can someone explain to me how conversation storage in db works? I would like to keep them even if they are deleted from chat.openai.com
> > Thanks you.
> 
> Stored in mongodb

Do you have any suggestions on cleaning up invalid conversations?
I have tried;
- Conversation Management
     Destroy invalid conversations
     Clear all conversations
     Mark Invalid (error: conversation does not exist)
     Delete (error: 500)
Heck I have even deleted the entire MongoDB database, but they remain in conversation history.
If they are in the sqllite DB any tips on how to clean-up?
