### ISSUE TITLE
web对话无法使用, OpenAI Web插件设置报错。

### ISSUE THREAD

**Issue by wyq282** [moeakwak/chatgpt-web-share#248]
v0.4.0-alpha4版本，对话选web无法使用，报错“httpx.ConnectError: All connection attempts failed”，选API可以使用。
OpenAI Web插件设置报错Request Error。

**Comment by huoshenw** [comment]
同样的问题

**Comment by moeakwak** [comment]
内测版本可能会出现破坏性更新，关注群内消息以及在群内提问即可，此类问题无需提issue
