### ISSUE TITLE
当CHATGPT网页版提示无法获取历史记录时，DOCKER版本无法正常启动

### ISSUE THREAD

**Issue by ZzxDDDDDD** [moeakwak/chatgpt-web-share#25]
当CHATGPT官方网页版的历史记录侧提示
History is temporarily unavailable. We're working to restore this feature as soon as possible.

使用docker-compose up无法正常启动，日志如下：
chatgpt-web-share | During handling of the above exception, another exception occurred:
chatgpt-web-share | 
chatgpt-web-share | Traceback (most recent call last):
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
chatgpt-web-share |     yield
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
chatgpt-web-share |     resp = await self._pool.handle_async_request(req)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
chatgpt-web-share |     raise exc
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
chatgpt-web-share |     response = await connection.handle_async_request(request)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
chatgpt-web-share |     return await self._connection.handle_async_request(request)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 112, in handle_async_request
chatgpt-web-share |     raise exc
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 91, in handle_async_request
chatgpt-web-share |     ) = await self._receive_response_headers(**kwargs)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers
chatgpt-web-share |     event = await self._receive_event(timeout=timeout)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 191, in _receive_event
chatgpt-web-share |     data = await self._network_stream.read(
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 31, in read
chatgpt-web-share |     with map_exceptions(exc_map):
chatgpt-web-share |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
chatgpt-web-share |     self.gen.throw(typ, value, traceback)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
chatgpt-web-share |     raise to_exc(exc)
chatgpt-web-share | httpcore.ReadTimeout
chatgpt-web-share | 
chatgpt-web-share | The above exception was the direct cause of the following exception:
chatgpt-web-share | 
chatgpt-web-share | Traceback (most recent call last):
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
chatgpt-web-share |     async with self.lifespan_context(app) as maybe_state:
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
chatgpt-web-share |     await self._router.startup()
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 654, in startup
chatgpt-web-share |     await handler()
chatgpt-web-share |   File "/app/backend/main.py", line 164, in on_startup
chatgpt-web-share |     raise e
chatgpt-web-share |   File "/app/backend/main.py", line 119, in on_startup
chatgpt-web-share |     result = await g.chatgpt_manager.get_conversations()
chatgpt-web-share |   File "/app/backend/api/chatgpt.py", line 21, in get_conversations
chatgpt-web-share |     conversations = await self.chatbot.get_conversations()
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/revChatGPT/V1.py", line 868, in get_conversations
chatgpt-web-share |     response = await self.session.get(url)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1757, in get
chatgpt-web-share |     return await self.request(
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
chatgpt-web-share |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
chatgpt-web-share |     response = await self._send_handling_auth(
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
chatgpt-web-share |     response = await self._send_handling_redirects(
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
chatgpt-web-share |     response = await self._send_single_request(request)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
chatgpt-web-share |     response = await transport.handle_async_request(request)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
chatgpt-web-share |     with map_httpcore_exceptions():
chatgpt-web-share |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
chatgpt-web-share |     self.gen.throw(typ, value, traceback)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
chatgpt-web-share |     raise mapped_exc(message) from exc
chatgpt-web-share | httpx.ReadTimeout
chatgpt-web-share | 
chatgpt-web-share | 2023/03/22 06:16:39.046    ERROR: [uvicorn.error] Application startup failed. Exiting.

**Comment by moeakwak** [comment]
已修复，将在下个版本 v0.2.14 中发布

**Comment by ZzxDDDDDD** [comment]
升级0.2.14及0.2.15版本后出现新问题...chatgpt网页端可以同步对话记录但是chatgpt-web-share不行..
Logs:
chatgpt-web-share | 2023/03/23 02:16:44.575     INFO: [cws.utils.proxy] Reverse proxy started!
chatgpt-web-share | 2023/03/23 02:16:51.591    ERROR: [cws.__main__] Fetch conversation error (httpx.HTTPError):
chatgpt-web-share | 2023/03/23 02:16:51.592  WARNING: [cws.__main__] Sync conversations on startup failed!
chatgpt-web-share | 2023/03/23 02:16:51.592     INFO: [uvicorn.error] Application startup complete.
chatgpt-web-share | 2023/03/23 02:16:51.592     INFO: [uvicorn.error] Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)

经检查reverse proxy的Puid是最新的.

**Comment by ZzxDDDDDD** [comment]
chatgpt-web-share | 2023/03/23 02:22:40.522     INFO: [uvicorn.access] 192.168.X.X:0 - "GET /conv/ed4dde9d-d332-4fc6-b151-8d880f794c5c HTTP/1.1" 500
chatgpt-web-share | 2023/03/23 02:22:40.523    ERROR: [uvicorn.error] Exception in ASGI application
chatgpt-web-share |
chatgpt-web-share | Traceback (most recent call last):
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
chatgpt-web-share |     result = await app(  # type: ignore[func-returns-value]
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
chatgpt-web-share |     return await self.app(scope, receive, send)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
chatgpt-web-share |     raise exc from None
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
chatgpt-web-share |     await self.app(scope, inner_receive, inner_send)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
chatgpt-web-share |     await super().__call__(scope, receive, send)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
chatgpt-web-share |     await self.middleware_stack(scope, receive, send)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
chatgpt-web-share |     raise exc
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
chatgpt-web-share |     await self.app(scope, receive, _send)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
chatgpt-web-share |     await self.app(scope, receive, send)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
chatgpt-web-share |     raise exc
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
chatgpt-web-share |     await self.app(scope, receive, sender)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
chatgpt-web-share |     raise e
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
chatgpt-web-share |     await self.app(scope, receive, send)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
chatgpt-web-share |     await route.handle(scope, receive, send)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
chatgpt-web-share |     await self.app(scope, receive, send)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
chatgpt-web-share |     response = await func(request)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
chatgpt-web-share |     raw_response = await run_endpoint_function(
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
chatgpt-web-share |     return await dependant.call(**values)
chatgpt-web-share |   File "/app/backend/api/routers/chat.py", line 63, in get_conversation_history
chatgpt-web-share |     result = await g.chatgpt_manager.get_conversation_messages(conversation.conversation_id)
chatgpt-web-share |   File "/app/backend/api/chatgpt.py", line 26, in get_conversation_messages
chatgpt-web-share |     messages = await self.chatbot.get_msg_history(conversation_id)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/revChatGPT/V1.py", line 879, in get_msg_history
chatgpt-web-share |     response = await self.session.get(url)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1757, in get
chatgpt-web-share |     return await self.request(
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
chatgpt-web-share |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
chatgpt-web-share |     response = await self._send_handling_auth(
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
chatgpt-web-share |     response = await self._send_handling_redirects(
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
chatgpt-web-share |     response = await self._send_single_request(request)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
chatgpt-web-share |     response = await transport.handle_async_request(request)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
chatgpt-web-share |     with map_httpcore_exceptions():
chatgpt-web-share |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
chatgpt-web-share |     self.gen.throw(typ, value, traceback)
chatgpt-web-share |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
chatgpt-web-share |     raise mapped_exc(message) from exc
chatgpt-web-share | httpx.ReadTimeout
chatgpt-web-share | 2023/03/23 02:22:48.419     INFO: [uvicorn.error] ('192.168.100.133', 0) - "WebSocket /conv" [accepted]
chatgpt-web-share | 2023/03/23 02:22:48.421     INFO: [uvicorn.error] connection open
chatgpt-web-share | 2023/03/23 02:22:53.811    ERROR: [cws.api.routers.chat]
chatgpt-web-share | 2023/03/23 02:22:54.028     INFO: [uvicorn.error] connection closed
chatgpt-web-share | 2023/03/23 02:22:54.042     INFO: [uvicorn.access] 192.168.X.X:0 - "GET /user/me HTTP/1.1" 200

发送消息后前端网页会提示[1014] HTTP错误，后端日志如上

**Comment by moeakwak** [comment]
这种超时的情况可能是网络问题，或openai服务挂了，可以去 status.openai.com 看一下有没有新的故障
