### ISSUE TITLE
ERROR: [uvicorn.error] Application startup failed. Exiting.

### ISSUE THREAD

**Issue by 1371030** [moeakwak/chatgpt-web-share#250]
配置如下：
version: "3"

services:
  chatgpt-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:latest
    restart: always
    ports:
      - 8180:80 # web 端口号
    volumes:
      - ./data:/data # 存放数据库文件以及统计数据
      - ./config.yaml:/app/backend/api/config/config.yaml # 后端配置文件
      - ./logs:/app/logs # 存放日志文件
    environment:
      - TZ=Asia/Shanghai
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/
    depends_on:
      - go-chatgpt-api

  go-chatgpt-api:
    image: linweiyuan/go-chatgpt-api:latest
    ports:
      - 6060:8080 # 如果你需要暴露端口如一带多，可以取消注释
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      # - NETWORK_PROXY_SERVER=http://host:port
    restart: unless-stopped

config.yaml中
chatgpt_base_url: http://124.71.28.193:6060/
或者
#chatgpt_base_url: http://124.71.28.193:6060/
都不成功

2023/08/24 14:28:18.908     INFO: [uvicorn.error]	Started server process [1]
2023/08/24 14:28:18.908     INFO: [uvicorn.error]	Waiting for application startup.
2023/08/24 14:28:18.913     INFO: [alembic.runtime.migration]	Context impl SQLiteImpl.
2023/08/24 14:28:18.913     INFO: [alembic.runtime.migration]	Will assume non-transactional DDL.
2023/08/24 14:28:18.917     INFO: [cws.main]	database initialized
2023/08/24 14:28:18.918    DEBUG: [cws.utils.store_statistics]	loading statistics from /data/statistics.json
2023/08/24 14:28:18.918     INFO: [cws.utils.store_statistics]	Requests statistics loaded.
2023/08/24 14:28:18.931     INFO: [cws.utils.create_user]	Create User admin Error: Username already exists
2023/08/24 14:28:18.935     INFO: [cws.main]	Using http://124.71.28.193:6060/ as ChatGPT base url
2023/08/24 14:28:18.935     INFO: [cws.utils.sync_conversations]	Syncing conversations...
2023/08/24 14:28:18.945    ERROR: [cws.utils.sync_conversations]	Fetch conversation error (httpx.HTTPError): All connection attempts failed
2023/08/24 14:28:18.946  WARNING: [cws.utils.sync_conversations]	Sync conversations on startup failed!
2023/08/24 14:28:18.946     INFO: [cws.main]	Sync conversations regularly enabled, will sync conversations every 12 hours.
2023/08/24 14:28:18.947     INFO: [uvicorn.error]	Application startup complete.
2023/08/24 14:28:18.948     INFO: [uvicorn.error]	Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2023/08/24 14:28:22.747     INFO: [cws.access]	183.214.227.137:0 | GET /user/me HTTP/1.1 | 200 OK | 4 ms
2023/08/24 14:28:33.641     INFO: [cws.access]	183.214.227.137:0 | GET /conv?fetch_all=false HTTP/1.1 | 200 OK | 16 ms
2023/08/24 14:28:38.212     INFO: [uvicorn.error]	('183.214.227.137', 0) - "WebSocket /conv" [accepted]
2023/08/24 14:28:38.214     INFO: [uvicorn.error]	connection open
2023/08/24 14:28:38.217    DEBUG: [cws.api.routers.chat]	admin connected to websocket
2023/08/24 14:28:38.278    ERROR: [cws.api.routers.chat]	All connection attempts failed
2023/08/24 14:28:38.279    DEBUG: [cws.api.routers.chat]	terminated ask None (ChatModels.gpt4) because of error
2023/08/24 14:28:38.314     INFO: [uvicorn.error]	connection closed
2023/08/24 14:28:38.353     INFO: [cws.access]	183.214.227.137:0 | GET /user/me HTTP/1.1 | 200 OK | 4 ms
2023/08/24 14:28:45.960     INFO: [cws.access]	183.214.227.137:0 | GET /system/info HTTP/1.1 | 200 OK | 22 ms
2023/08/24 14:28:45.983     INFO: [cws.access]	183.214.227.137:0 | GET /system/request_statistics HTTP/1.1 | 200 OK | 17 ms
2023/08/24 14:28:45.993     INFO: [cws.access]	183.214.227.137:0 | GET /user HTTP/1.1 | 200 OK | 25 ms
2023/08/24 14:28:47.903     INFO: [cws.access]	183.214.227.137:0 | GET /conv?fetch_all=true HTTP/1.1 | 200 OK | 14 ms

**Comment by ser-tec** [comment]
CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/backend-api/
