### ISSUE TITLE
有点尬，类似于被xss攻击了，只是这一次攻击人是gpt

### ISSUE THREAD

**Issue by langren1353** [moeakwak/chatgpt-web-share#252]
**Version**
v0.3.15

**What's your deploying method?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
预览的效果：
![image](https://github.com/moeakwak/chatgpt-web-share/assets/14857127/90fb29f9-47be-425d-b269-9d9d42328271)
真实的内容如下：
![image](https://github.com/moeakwak/chatgpt-web-share/assets/14857127/c424f611-02cc-4bbf-911d-3d0cad0d8adc)

**Comment by moeakwak** [comment]
这样的html渲染不会对后端造成危害，顶多可能影响页面渲染。如果出现markdown渲染问题可以关闭markdown渲染。

**Comment by moeakwak** [comment]
已经使用 dompurify 来预防 xss 攻击。也可配置跨站规则以增强安全性。
