### ISSUE TITLE
本地部署web，利用国外VPS的gochatapi---获取回复失败 [1001] ChatGPT返回错误

### ISSUE THREAD

**Issue by walkchen9** [moeakwak/chatgpt-web-share#253]
**Version**
ghcr.io/moeakwak/chatgpt-web-share:0.4.0-alpha4.4

**What's your deploying environment?**
- [*] Docker
- [ ] Caddy
- [ ] Other

无法跑成功

docker-compose.yml
`version: "3"

services:
  chatgpt-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:0.4.0-alpha4.4
    container_name: chatgpt-web-share
    restart: always
    network_mode: bridge
    ports:
      - 8080:80
    volumes:
      - ./data:/data
      - ./config.yaml:/app/backend/api/config/config.yaml
      - ./logs:/app/logs`

config.yaml

`print_sql: false
host: "127.0.0.1"
port: 8000
data_dir: /data
database_url: "sqlite+aiosqlite:////data/database.db"
run_migration: false

jwt_secret: "MODIFY_THIS_TO_RANDOM_SECRET"
jwt_lifetime_seconds: 86400
cookie_max_age: 86400
user_secret: "MODIFY_THIS_TO_RANDOM_SECRET"

sync_conversations_on_startup: true
create_initial_admin_user: true
initial_admin_username: admin
initial_admin_password: password
ask_timeout: 600

chatgpt_access_token: "eyJhbG***u8GujKBjw" 
chatgpt_paid: false 

chatgpt_base_url: http://172.107.*.*:8080/

log_dir: /app/logs
console_log_level: INFO

request_log_counter_time_window: 2592000
request_log_counter_interval: 1800
ask_log_time_window: 2592000
sync_conversations_regularly: yes`

然后docker-compose up -d

**Comment by walkchen9** [comment]
获取回复失败
[1001] ChatGPT返回错误

**Comment by spammenotinoz** [comment]
This config isn't recommend, but I did test this and it worked.
On the VPS running gochatapi, you need to expose the ports within docker, you also better be running a firewall and only allowing inbound from your local machine.
Alternatively consider a VPN style tunnel, such as a Cloudflare Tunnel, or just run warp locally and forget the VPS.
Have you checked your VPS isn't blocked?

**Comment by walkchen9** [comment]
{"level":"info","ts":1693916304.9040513,"msg":"using provided configuration","config_file":"/app/Caddyfile","config_adapter":"caddyfile"}
{"level":"info","ts":1693916304.910175,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"warn","ts":1693916304.9107714,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
{"level":"info","ts":1693916304.9115596,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1693916304.9115705,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00059ec40"}
{"level":"info","ts":1693916304.9120677,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
{"level":"info","ts":1693916304.9121056,"msg":"serving initial configuration"}
{"level":"info","ts":1693916304.912151,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/root/.local/share/caddy"}
{"level":"info","ts":1693916304.912218,"logger":"tls","msg":"finished cleaning storage units"}
Successfully started Caddy (pid=17) - Caddy is running in the background
2023/09/05 12:18:26.408     INFO: [uvicorn.error] Started server process [1]
2023/09/05 12:18:26.408     INFO: [uvicorn.error] Waiting for application startup.
2023/09/05 12:18:26.418     INFO: [alembic.runtime.migration] Context impl SQLiteImpl.
2023/09/05 12:18:26.418     INFO: [alembic.runtime.migration] Will assume non-transactional DDL.
2023/09/05 12:18:26.428     INFO: [cws.main] database initialized
2023/09/05 12:18:26.429     INFO: [cws.utils.store_statistics] Requests statistics loaded.
2023/09/05 12:18:26.448     INFO: [cws.utils.create_user] Create User admin Error: Username already exists
2023/09/05 12:18:26.457     INFO: [cws.main] Using **_http://*.*.*:8080/chatgpt/_** as ChatGPT base url
2023/09/05 12:18:26.457     INFO: [cws.utils.sync_conversations] Syncing conversations...
2023/09/05 12:18:27.105    ERROR: [cws.utils.sync_conversations] **_Fetch conversation error (ChatGPTError): OpenAI 403: {}_**
2023/09/05 12:18:27.107  WARNING: [cws.utils.sync_conversations] Sync conversations on startup failed!
/usr/local/lib/python3.10/site-packages/tzlocal/unix.py:183: UserWarning: Can not find any timezone configuration, defaulting to UTC.

**Comment by walkchen9** [comment]
Successfully started Caddy (pid=17) - Caddy is running in the background
2023/09/05 12:13:17.974     INFO: [uvicorn.error] Started server process [1]
2023/09/05 12:13:17.975     INFO: [uvicorn.error] Waiting for application startup.
2023/09/05 12:13:17.984     INFO: [cws.api.database] database not exists, creating database...
2023/09/05 12:13:18.011     INFO: [cws.api.database] database created!
2023/09/05 12:13:18.033     INFO: [alembic.runtime.migration] Context impl SQLiteImpl.
2023/09/05 12:13:18.033     INFO: [alembic.runtime.migration] Will assume non-transactional DDL.
2023/09/05 12:13:18.052     INFO: [cws.api.database] stamped database to head
2023/09/05 12:13:18.054     INFO: [cws.main] database initialized
2023/09/05 12:13:18.054     INFO: [cws.utils.store_statistics] File statistics.json not found, skip loading statistics.
2023/09/05 12:13:18.426     INFO: [cws.utils.create_user] User created: <api.models.User object at 0x7f7e8a7bfaf0>
2023/09/05 12:13:18.435     INFO: [cws.main] Using **_http://*.*.*.*:8080/_** as ChatGPT base url
2023/09/05 12:13:18.435     INFO: [cws.utils.sync_conversations] Syncing conversations...
2023/09/05 12:13:18.954    ERROR: [cws.utils.sync_conversations] **_Fetch conversation error (ChatGPTError): OpenAI 500: {"errorMessage":"Get \"/conversations?limit=80\u0026offset=0\": invalid URL scheme: []"}_**

**Comment by walkchen9** [comment]
> 



> This config isn't recommend, but I did test this and it worked. On the VPS running gochatapi, you need to expose the ports within docker, you also better be running a firewall and only allowing inbound from your local machine. Alternatively consider a VPN style tunnel, such as a Cloudflare Tunnel, or just run warp locally and forget the VPS. Have you checked your VPS isn't blocked?

这个api是可以的，我难过是正确的

[root@racknerd-69d5e2 ~]# bash <(curl -Ls https://raw.githubusercontent.com/missuo/OpenAI-Checker/main/openai.sh)
OpenAI Access Checker. Made by Vincent
https://github.com/missuo/OpenAI-Checker
-------------------------------------
[IPv4]
Your IPv4: 107.172.*.* - ColoCrossing
Your IP supports access to OpenAI. Region: US
-------------------------------------
[IPv6]
IPv6 is not supported on the current host. Skip...
-------------------------------------

**Comment by update757** [comment]
我的错误与你一样，都无法对话，报错。
2023-09-08 20:46:04 2023/09/08 20:46:04.103    ERROR: [cws.utils.sync_conversations] Fetch conversation error (ChatGPTError): OpenAI 500: {"errorMessage":"Get \"/conversations?limit=80\u0026offset=0\": invalid URL scheme: []"}
2023-09-08 20:46:04 2023/09/08 20:46:04.104  WARNING: [cws.utils.sync_conversations] Sync conversations on startup failed!

INFO: [cws.main] Using env: http://go-chatgpt-api:8080/chatgpt/ as ChatGPT base url
2023-09-08 20:56:21 2023/09/08 20:56:21.123     INFO: [cws.utils.sync_conversations] Syncing conversations...
2023-09-08 20:56:26 2023/09/08 20:56:26.135    ERROR: [cws.utils.sync_conversations] Fetch conversation error (httpx.HTTPError): 
2023-09-08 20:56:26 2023/09/08 20:56:26.135  WARNING: [cws.utils.sync_conversations] Sync conversations on startup failed!

**Comment by fir3workX** [comment]
[1014] HTTP错误

2023/09/12 12:38:15.070     INFO: [uvicorn.error]	connection open
2023/09/12 12:38:15.073    DEBUG: [cws.api.routers.chat]	admin connected to websocket
2023/09/12 12:38:15.136    ERROR: [cws.api.routers.chat]	All connection attempts failed
2023/09/12 12:38:15.137    DEBUG: [cws.api.routers.chat]	terminated ask None (ChatModels.default) because of error
2023/09/12 12:38:15.179     INFO: [uvicorn.error]	connection closed

**Comment by moeakwak** [comment]
0.3.15 版本已不推荐使用，请等待 0.4.0 更新。

OpenAI 403、500 等错误，与 go-chatgpt-api 的使用有关，请自行解决。

如果使用 http://go-chatgpt-api:8080/chatgpt/ 作为地址，需要确保容器内能够 dns 查询到 go-chatgpt-api 这个主机名，需要正确的 docker 配置。
