### ISSUE TITLE
[General Question] Will there be a plugin feature be added?

### ISSUE THREAD

**Issue by TheButterbrotMan** [moeakwak/chatgpt-web-share#254]
Hello, i am using the All-In-One Docker. Currently there is no plugin feature for GPT-4, will this be added?

Regards.

**Comment by TheButterbrotMan** [comment]
How can i update to "docker pull ghcr.io/moeakwak/chatgpt-web-share:0.4.0-alpha4.4" from All-In-One?

**Comment by moeakwak** [comment]
Please wait for the 0.4.0 document
