### ISSUE TITLE
默认管理账户正常回复和保存，新建用户无法保存回话，回复完成后提示WebSocket 1006: 未知错误

### ISSUE THREAD

**Issue by tyhunter** [moeakwak/chatgpt-web-share#255]
目前使用默认的admin账户能够保存对话也不报错，但是新建用户进行对话，能完成交流，但在ChatGPT回复完之后会提示：“WebSocket 1006: 未知错误”，并且刷新页面后对话不会被保存，
登录网页版ChatGPT看了下，其实新建了很多个相关会话出来了，不清楚为什么没有被同步上

**Comment by spammenotinoz** [comment]
I had these symptoms, but not entirely sure what fixed it.
I believe it could be changes I made to my proxy config, as I have been making proxy changes to diagnose some 404 errors and help maintain user sessions.  The below headers, may not be optimal but seem to have helped reliability and conversations seem to stay synced.

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            add_header Cache-Control "no-cache, private";
            proxy_set_header Keep-Alive "timeout=600s, max=1000";

**Comment by tyhunter** [comment]
> I had these symptoms, but not entirely sure what fixed it. I believe it could be changes I made to my proxy config, as I have been making proxy changes to diagnose some 404 errors and help maintain user sessions. The below headers, may not be optimal but seem to have helped reliability and conversations seem to stay synced.
> 
> ```
>         proxy_set_header Host $host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>         add_header Cache-Control "no-cache, private";
>         proxy_set_header Keep-Alive "timeout=600s, max=1000";
> ```

Thanks for the reply, but i use ip:port to direct link, have the same issue

**Comment by tyhunter** [comment]
好像知道是什么问题了，如果给用户分配了会话数量限制就会出现这个bug，如果取消掉将会话设置/分模型限制都取消掉，问题就自动消失了，有点迷，暂时先不管了，等后面大佬来更新

**Comment by SivanLaai** [comment]
1006 这个错误，感觉是超时设置，如果会编译前端代码的话，

改一下文件：```frontend/src/views/conversation/index.vue```349行

把
```
 webSocket.onclose = async (event: CloseEvent) => {
    aborter = null;
    canAbort.value = false;
    console.log('WebSocket connection is closed', event, isAborted.value);
    if (!hasError && (event.code == 1000 || isAborted.value)) {
```
改成
```
 webSocket.onclose = async (event: CloseEvent) => {
    aborter = null;
    canAbort.value = false;
    console.log('WebSocket connection is closed', event, isAborted.value);
    if (!hasError && (event.code == 1000 || event.code == 1006 || isAborted.value)) {
```

实际不影响任何，1006也是没有指定的错误

**Comment by Oliverwqcwrw** [comment]
> 好像知道是什么问题了，如果给用户分配了会话数量限制就会出现这个bug，如果取消掉将会话设置/分模型限制都取消掉，问题就自动消失了，有点迷，暂时先不管了，等后面大佬来更新

你好，我分模型限制一栏选择不限之后还是报这个错，请问您这边是怎么解决的呢
