### ISSUE TITLE
启动后无法使用，查看日志疑似启动后Mongo数据库错误

### ISSUE THREAD

**Issue by tyhunter** [moeakwak/chatgpt-web-share#257]
尝试了删除所有文件重新安装，还是如下报错，实在找不到头绪

日志如下：
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id 
WHERE user.id = ?
2023/09/23 19:08:09.812     INFO: [sqlalchemy.engine.Engine]	[cached since 0.7492s ago] (1,)
2023/09/23 19:08:09.817     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
2023/09/23 19:08:09.819     INFO: [sqlalchemy.engine.Engine]	SELECT conversation.id, conversation.source, conversation.conversation_id, conversation.current_model, conversation.title, conversation.user_id, conversation.is_valid, conversation.create_time, conversation.update_time 
FROM conversation 
WHERE conversation.source IN (?)
2023/09/23 19:08:09.820     INFO: [sqlalchemy.engine.Engine]	[generated in 0.00055s] ('openai_web',)
2023/09/23 19:08:09.823     INFO: [sqlalchemy.engine.Engine]	UPDATE user SET last_active_time=? WHERE user.id = ?
2023/09/23 19:08:09.823     INFO: [sqlalchemy.engine.Engine]	[cached since 0.7468s ago] ('2023-09-23 11:08:09.822637', 1)
2023/09/23 19:08:09.825     INFO: [sqlalchemy.engine.Engine]	ROLLBACK
2023/09/23 19:08:09.832     INFO: [sqlalchemy.engine.Engine]	COMMIT
2023/09/23 19:08:09.832     INFO: [sqlalchemy.engine.Engine]	ROLLBACK
2023/09/23 19:08:09.836     INFO: [sqlalchemy.engine.Engine]	ROLLBACK
2023/09/23 19:08:09.839     INFO: [sqlalchemy.engine.Engine]	ROLLBACK
2023/09/23 19:08:09.844     INFO: [sqlalchemy.engine.Engine]	ROLLBACK
2023/09/23 19:08:09.845     INFO: [cws.access]	120.244.128.60:0 | GET /system/stats/ask?granularity=1800 HTTP/1.1 | 200 OK | 224 ms
2023/09/23 19:08:09.913     INFO: [sqlalchemy.engine.Engine]	COMMIT
2023/09/23 19:08:09.917     INFO: [cws.access]	120.244.128.60:0 | GET /system/info HTTP/1.1 | 200 OK | 499 ms
2023/09/23 19:08:09.918     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id
2023/09/23 19:08:09.919     INFO: [sqlalchemy.engine.Engine]	[cached since 20.08s ago] ()
2023/09/23 19:08:09.925     INFO: [sqlalchemy.engine.Engine]	ROLLBACK
2023/09/23 19:08:09.929     INFO: [sqlalchemy.engine.Engine]	ROLLBACK
2023/09/23 19:08:09.934     INFO: [sqlalchemy.engine.Engine]	ROLLBACK
2023/09/23 19:08:09.937     INFO: [cws.access]	120.244.128.60:0 | GET /system/stats/request?granularity=1800 HTTP/1.1 | 200 OK | 512 ms
2023/09/23 19:08:09.940     INFO: [cws.access]	120.244.128.60:0 | GET /user HTTP/1.1 | 200 OK | 301 ms
2023/09/23 19:08:11.191     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id 
WHERE user.id = ?
2023/09/23 19:08:11.193     INFO: [sqlalchemy.engine.Engine]	[cached since 2.14s ago] (1,)
2023/09/23 19:08:11.200     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id 
WHERE user.id = ?
2023/09/23 19:08:11.201     INFO: [sqlalchemy.engine.Engine]	[cached since 2.148s ago] (1,)
2023/09/23 19:08:11.202     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id 
WHERE user.id = ?
2023/09/23 19:08:11.204     INFO: [sqlalchemy.engine.Engine]	[cached since 2.141s ago] (1,)
2023/09/23 19:08:11.209     INFO: [sqlalchemy.engine.Engine]	UPDATE user SET last_active_time=? WHERE user.id = ?
2023/09/23 19:08:11.210     INFO: [sqlalchemy.engine.Engine]	[cached since 2.133s ago] ('2023-09-23 11:08:11.209131', 1)
2023/09/23 19:08:11.211     INFO: [sqlalchemy.engine.Engine]	COMMIT
2023/09/23 19:08:11.215     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id 
WHERE user.id = ?
2023/09/23 19:08:11.216     INFO: [sqlalchemy.engine.Engine]	[cached since 2.153s ago] (1,)
2023/09/23 19:08:11.225     INFO: [sqlalchemy.engine.Engine]	ROLLBACK
2023/09/23 19:08:11.229     INFO: [sqlalchemy.engine.Engine]	UPDATE user SET last_active_time=? WHERE user.id = ?
2023/09/23 19:08:11.229     INFO: [sqlalchemy.engine.Engine]	[cached since 2.153s ago] ('2023-09-23 11:08:11.228389', 1)
2023/09/23 19:08:11.231     INFO: [sqlalchemy.engine.Engine]	COMMIT
2023/09/23 19:08:11.238     INFO: [cws.access]	120.244.128.60:0 | GET /system/credentials HTTP/1.1 | 200 OK | 50 ms
2023/09/23 19:08:11.244     INFO: [sqlalchemy.engine.Engine]	ROLLBACK
2023/09/23 19:08:11.247     INFO: [cws.access]	120.244.128.60:0 | GET /system/config HTTP/1.1 | 200 OK | 53 ms
2023/09/23 19:08:11.737     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id 
WHERE user.id = ?
2023/09/23 19:08:11.738     INFO: [sqlalchemy.engine.Engine]	[cached since 2.685s ago] (1,)
2023/09/23 19:08:11.743     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id 
WHERE user.id = ?
2023/09/23 19:08:11.744     INFO: [sqlalchemy.engine.Engine]	[cached since 2.681s ago] (1,)
2023/09/23 19:08:11.747     INFO: [sqlalchemy.engine.Engine]	UPDATE user SET last_active_time=? WHERE user.id = ?
2023/09/23 19:08:11.747     INFO: [sqlalchemy.engine.Engine]	[cached since 2.671s ago] ('2023-09-23 11:08:11.746747', 1)
2023/09/23 19:08:11.749     INFO: [sqlalchemy.engine.Engine]	COMMIT
2023/09/23 19:08:11.758     INFO: [sqlalchemy.engine.Engine]	ROLLBACK
2023/09/23 19:08:16.733     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id 
WHERE user.id = ?
2023/09/23 19:08:16.735     INFO: [sqlalchemy.engine.Engine]	[cached since 7.681s ago] (1,)
2023/09/23 19:08:16.739     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id 
WHERE user.id = ?
2023/09/23 19:08:16.740     INFO: [sqlalchemy.engine.Engine]	[cached since 7.677s ago] (1,)
2023/09/23 19:08:16.744     INFO: [sqlalchemy.engine.Engine]	UPDATE user SET last_active_time=? WHERE user.id = ?
2023/09/23 19:08:16.744     INFO: [sqlalchemy.engine.Engine]	[cached since 7.667s ago] ('2023-09-23 11:08:16.743377', 1)
2023/09/23 19:08:16.746     INFO: [sqlalchemy.engine.Engine]	COMMIT
2023/09/23 19:08:16.755     INFO: [sqlalchemy.engine.Engine]	ROLLBACK
2023/09/23 19:08:21.725     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id 
WHERE user.id = ?
2023/09/23 19:08:21.727     INFO: [sqlalchemy.engine.Engine]	[cached since 12.67s ago] (1,)
2023/09/23 19:08:21.732     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id 
WHERE user.id = ?
2023/09/23 19:08:21.733     INFO: [sqlalchemy.engine.Engine]	[cached since 12.67s ago] (1,)
2023/09/23 19:08:21.736     INFO: [sqlalchemy.engine.Engine]	UPDATE user SET last_active_time=? WHERE user.id = ?
2023/09/23 19:08:21.736     INFO: [sqlalchemy.engine.Engine]	[cached since 12.66s ago] ('2023-09-23 11:08:21.735506', 1)
2023/09/23 19:08:21.737     INFO: [sqlalchemy.engine.Engine]	COMMIT
2023/09/23 19:08:21.747     INFO: [sqlalchemy.engine.Engine]	ROLLBACK
2023/09/23 19:08:26.726     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id 
WHERE user.id = ?
2023/09/23 19:08:26.727     INFO: [sqlalchemy.engine.Engine]	[cached since 17.67s ago] (1,)
2023/09/23 19:08:26.732     INFO: [sqlalchemy.engine.Engine]	BEGIN (implicit)
FROM user LEFT OUTER JOIN user_setting AS user_setting_1 ON user.id = user_setting_1.user_id 
WHERE user.id = ?
2023/09/23 19:08:26.733     INFO: [sqlalchemy.engine.Engine]	[cached since 17.67s ago] (1,)
2023/09/23 19:08:26.736     INFO: [sqlalchemy.engine.Engine]	UPDATE user SET last_active_time=? WHERE user.id = ?
2023/09/23 19:08:26.737     INFO: [sqlalchemy.engine.Engine]	[cached since 17.66s ago] ('2023-09-23 11:08:26.735946', 1)

**Comment by hehan-wang** [comment]
老哥怎么解决的？我也遇到了一样的问题
