### ISSUE TITLE
 V0.4.0-alpha7 上传文件报错

### ISSUE THREAD

**Issue by Alfred212121** [moeakwak/chatgpt-web-share#263]
文件 2AF5A6F5-6D28-4480-937C-6E83626A770A.png 上传失败: {"message":"Request failed with status code 500","name":"AxiosError","stack":"AxiosError: Request failed with status code 500\n at cs (https://XXXXXX.XX/assets/index-833880a4.js:3:1040)\n at XMLHttpRequest.h (https://XXXXXX.XX/assets/index-833880a4.js:3:4319)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*"},"baseURL":"/api/","method":"post","url":"/files/local/upload","data":{}},"code":"ERR_BAD_RESPONSE","status":500}

**Comment by ser-tec** [comment]
I think you are missing the upload table on database.db
Are you using docker compose ? Try delete database.db and let the app create a correct new one.
Or create manually in the existing db. I think the issue is in the alambic migration.

Anyway personally with last release 7.0 and clean installation I don't have upload error but file are not pass to gpt.

**Comment by spammenotinoz** [comment]
> I think you are missing the upload table on database.db Are you using docker compose ? Try delete database.db and let the app create a correct new one. Or create manually in the existing db. I think the issue is in the alambic migration.
> 
> Anyway personally with last release 7.0 and clean installation I don't have upload error but file are not pass to gpt.

Ensure you have the latest go-chatgpt-api, earlier ones do not support upload, you may need to clean out your old images.

**Comment by ser-tec** [comment]
> > I think you are missing the upload table on database.db Are you using docker compose ? Try delete database.db and let the app create a correct new one. Or create manually in the existing db. I think the issue is in the alambic migration.
> > Anyway personally with last release 7.0 and clean installation I don't have upload error but file are not pass to gpt.
> 
> Ensure you have the latest go-chatgpt-api, earlier ones do not support upload, you may need to clean out your old images.

oh that's true, thanks you.

**Comment by Alfred212121** [comment]
I've pinpointed the issue: a table was missing in our SQLite database (`database.db`). To address this, create the table using the following SQL:

```sql
CREATE TABLE uploaded_files (
    id TEXT NOT NULL PRIMARY KEY,
    original_filename TEXT NOT NULL,
    size INTEGER NOT NULL,
    content_type TEXT,
    storage_path TEXT,
    upload_time DATETIME NOT NULL,
    uploader_id INTEGER NOT NULL,
    openai_web_info TEXT,
    FOREIGN KEY (uploader_id) REFERENCES user(id)
);
```

After running the SQL, the problem should be resolved. This solution should assist others facing a similar issue. Closing this now. Thanks!
