### ISSUE TITLE
v0.4.0-alpha7 修复上传问题后，但是在对话里无法显示图片

### ISSUE THREAD

**Issue by xixi-furry** [moeakwak/chatgpt-web-share#267]
按照 #263 最后一楼的语法执行完后，确实可以上传图片不报错，gpt也收到了正确的消息，但是无法在前端看见图片，但是在gpt官网侧是能够看到图片的，想问问有没有大佬也遇到了一样的问题，有没有解决办法

**Comment by xixi-furry** [comment]
![image](https://github.com/moeakwak/chatgpt-web-share/assets/59167815/22bb1f0f-cd96-42d8-aef7-e27a7b145a09)

**Comment by moeakwak** [comment]
检查一下控制台日志以及网络请求

**Comment by xixi-furry** [comment]
突然又好了= =，不知道为啥
