### ISSUE TITLE
其他用户使用dall·e 3在同一个对话ID下的多轮对话，在管理员的“会话管理”里只能看到首次加载时的轮次（后续其他用户在同一对话ID下有新的对话时不会更新，手动同步也没有用），而官网可以看到全部的轮次

### ISSUE THREAD

**Issue by Alfred212121** [moeakwak/chatgpt-web-share#268]
![image](https://github.com/moeakwak/chatgpt-web-share/assets/58665898/6f01ac51-1e37-4944-b549-7d1e4642a8ae)
![image](https://github.com/moeakwak/chatgpt-web-share/assets/58665898/02374e44-be1b-4dc5-9544-a8360c5a8831)

**Comment by moeakwak** [comment]
这是因为，管理员在后台看到的是会话缓存。用户如果刷新页面并重新加载该对话，缓存就会被刷新，管理员就可以看到更新后的对话。

后续会针对这一点进行优化，提供手动更新缓存的功能。
