### ISSUE TITLE
两个功能建议：1. 希望能添加一个对话文件夹管理功能。2. 希望能让用户自己保存对话目录

### ISSUE THREAD

**Issue by DaisyHunter** [moeakwak/chatgpt-web-share#270]
**Is your feature request related to a problem? Please describe.**
1. 对话太多了，找起来有点慢，也不大方便。
2. 破坏式更新（大版本更新）过程中容易丢失用户的对话目录，如果要找回则需要管理员手动一个个的操作。

**Describe the solution you'd like**
1. 提供一个文件夹样式的对话目录管理功能。如果有条件的话，最好能提供一个tag功能。tag与目录都要支持检索。
2. 用户对话目录可以在用户界面进行导入导出。让用户自己保存对话目录，省的管理员在破坏式更新后，手动一个个的帮用户找回对话信息。
  2.1. 在管理端，单独保存对话的用户指向信息，方便管理员备份，且与cws的主要数据做个区分。

**Comment by moeakwak** [comment]
1. 没有这个打算。
2. 版本中带有alpha的本就是测试版，丢失数据很正常。正式版有自动数据库迁移，不会丢失用户对话分配数据。

建议别建议了

**Comment by DaisyHunter** [comment]
2. 可是，不是所有人都有那么多的测试账号啊...而且，新添加的arkose导致了旧版不能使用，我怎么样也需要做些测试吧。测试过程中造成的丢失，肯定是要想办法避免呀。我只是想能做到备份常态化，避免出现丢失的情况。当然，您是作者，这个取决于您。
