### ISSUE TITLE
bug反馈  代码复制功能无法使用

### ISSUE THREAD

**Issue by emmmnaadada** [moeakwak/chatgpt-web-share#28]
![image](https://user-images.githubusercontent.com/101549560/227088909-09d6ef5d-cf89-4983-bd85-0ef5f091e0fa.png)
代码粘贴无法使用，

**Comment by moeakwak** [comment]
我这里确认是能够使用。请提供你用的版本号

**Comment by emmmnaadada** [comment]
> 我这里确认是能够使用。请提供你用的版本号

docker镜像最新的，浏览器为微软浏览器

**Comment by moeakwak** [comment]
无法复现这个问题。请尝试换浏览器换设备。
