### ISSUE TITLE
能够正常回复，但在回复后会提示未知错误1006

### ISSUE THREAD

**Issue by youtianmeng** [moeakwak/chatgpt-web-share#280]
版本为0.4.0-alpha7.4
![image](https://github.com/moeakwak/chatgpt-web-share/assets/106040493/2b8e2758-a032-4339-99bd-72a0d88e7c9a)
![image](https://github.com/moeakwak/chatgpt-web-share/assets/106040493/81d7dafd-b2d9-493e-bf84-c3a444448062)

**Comment by youtianmeng** [comment]
和 #255 情况类似，但是我的管理员账号也会出现这个错误，并且在尝试取消掉将会话设置/分模型限制后仍未解决

**Comment by youtianmeng** [comment]
已解决

**Comment by Oliverwqcwrw** [comment]
> 已解决

方便说一下是怎么解决的吗
