### ISSUE TITLE
dev分支的前端项目如何在开发环境快速运行调试

### ISSUE THREAD

**Issue by threerog** [moeakwak/chatgpt-web-share#288]
**Version**
v0.4.0-alpha7.5

我想把代码拉取本地用开发调试的形式跑起来，方便自己排查问题或者魔改(保留版权的前提)
我只是单纯把前端vue项目跑起来了，但是卡在登录界面无法使用，无后端服务

想请教一下作者是如何在开发调试环境快速测试运行的

**Comment by moeakwak** [comment]
开发需要同时启动一个后端服务
