### ISSUE TITLE
getting error [1005] on chatgpt reply

### ISSUE THREAD

**Issue by hasansert4** [moeakwak/chatgpt-web-share#289]
**Version**
v0.3.15

**What's your deploying method?**
- [ X] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**

**To Reproduce**
Go to 'chat, start a new conversation, ask a question then this error is display : [1005]
See error
<img width="618" alt="Screenshot 2023-11-15 at 21 03 41" src="https://github.com/moeakwak/chatgpt-web-share/assets/79929514/7ca66497-79b9-462b-90e3-1d0f6f239ce2">

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

print_sql: false
host: "127.0.0.1"
port: 8000
data_dir: /data # <------ added in v0.3.0
database_url: "sqlite+aiosqlite:////data/database.db" # Note: there are four slashes here, indicating that the file is located in the /data directory and using an absolute path.
run_migration: false # whether to run database migration at startup, currently unnecessary

jwt_secret: "your jwt secret please 2123435465" # used for generating jwt token, fill in a random string
jwt_lifetime_seconds: 86400 # jwt token expiration time
cookie_max_age: 86400 # cookie expiration time
user_secret: "your user secret please 1234" # used for generating user passwords, fill in a random string

sync_conversations_on_startup: true # whether to synchronize conversations in ChatGPT on startup, recommended. When enabled, it will automatically synchronize newly added conversations in ChatGPT to the database and mark conversations no longer in ChatGPT as invalid.
create_initial_admin_user: true # whether to create an initial administrator user
initial_admin_username: admin1 # initial administrator username
initial_admin_password: des12345 # initial administrator password
ask_timeout: 600    # used to limit the maximum time of a conversation

chatgpt_access_token: "...." # needs to be obtained from ChatGPT, see below
chatgpt_paid: true # whether it is a ChatGPT Plus user

# Note! If you are a plus user, please uncomment the following and fill in reverse_proxy_puid as explained later in the document.
chatgpt_base_url: http://127.0.0.1:6060/api/
run_reverse_proxy: true
reverse_proxy_port: 6060
reverse_proxy_binary_path: /app/backend/ChatGPT-Proxy-V4
reverse_proxy_puid: "user-..."
auto_refresh_reverse_proxy_puid: true # whether to update puid automatically

log_dir: /app/logs # log storage location, do not modify casually
console_log_level: INFO # log level, set to DEBUG to obtain more information

# Note: the following are added in v0.3.0 for statistics
request_log_counter_time_window: 2592000 # request log time range, default is the last 30 days
request_log_counter_interval: 1800 # request log statistics granularity, default is 30 minutes
ask_log_time_window: 2592000 # conversation log time range, default is the last 7 days
sync_conversations_regularly: yes # whether sync conversations from chatgpt account every 12 hours

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by moeakwak** [comment]
The 0.3.x version is not supported anymore. Please use version 0.4.0-alphaX, documentation for the new version will be available shortly.
