### ISSUE TITLE
疑似bug，GPT4长文本回复中断后无法通过打“继续”恢复中断，提示429错误

### ISSUE THREAD

**Issue by gtgc2005** [moeakwak/chatgpt-web-share#29]
目前发下存在以下问题，疑似有BUG

1、使用GPT4的时候，如果输出长文本（大概600字以上），会有中断，此时输入继续，会提示429错误（ [cws.api.routers.chat] Client error '429 Too Many Requests' for url 'http://127.0.0.1:6062/api/conversation'）。
回到官方，会发现这个提问的回答不存在，仅有问题，显示There was an error generating a response。

2、在以上问题后之后，再这个对话框提出其他问题，会切换成GPT3.5。过一会时间接下去问其他问题，又变成GPT4。官网会有提示（The previous model used in this conversation is unavailable. We've switched you to the latest default model）

3、同样的长文本（大概600字以上），试过直接在官网直接提问GPT4，会在大致一样的地方中断，但是官网在输入继续后在中断处接上去继续回答完了问题。

**Comment by moeakwak** [comment]
使用的是哪个版本？

**Comment by gtgc2005** [comment]
V0.2.15
图1,1个对话两种模型[https://ldbbs.ldmnq.com/bbs/topic/attachment/2023-3/c8fce697-d7b9-47bb-a474-433f0b1a26c3.png](url)
图2，中断后回官网找不到这条回答https://ldbbs.ldmnq.com/bbs/topic/attachment/2023-3/040593fa-b792-49b6-9e6c-8f3c066e5c9e.png

**Comment by moeakwak** [comment]
一般来说，429错误是OpenAI做了访问限制，比如你可能达到了3小时25次的上限。至于切换成3.5这个问题，我没能复现。

**Comment by gtgc2005** [comment]
刚刚重新测试了下，长文本又可以通过继续分段回复了，应该不是BUG，是OpenAI在那个时间段负荷大了做了限制。我后面再观察下，如果有确定可以复现的问题再提交。
