### ISSUE TITLE
v0.4.0-alpha8 API模式报"未知错误"

### ISSUE THREAD

**Issue by threerog** [moeakwak/chatgpt-web-share#290]
**Version**
v0.4.0-alpha8

**What's your deploying method?**
- Docker

**Describe the bug**
v0.4.0-alpha8 API模式报"未知错误"

log
`ERROR: [cws.api.routers.chat]  'OpenaiApiChatManager' object has no attribute 'complete'`

退回v0.4.0-alpha7.5模式正常使用

**Comment by imvmi** [comment]
同有此问题，在api模式使用 gpt-3.5 模型时出现

**Comment by moeakwak** [comment]
此问题已在 0.4.0 解决
