### ISSUE TITLE
无法在一个插件对话中连续对话两次以上

### ISSUE THREAD

**Issue by SayHelloToMe-Xia** [moeakwak/chatgpt-web-share#296]
我不清楚是不是我的操作问题，我创建了一个GPT4插件对话，第一次问答正常，但是第二次对话就会出现报错
![image](https://github.com/moeakwak/chatgpt-web-share/assets/72793056/a2a25e49-ae30-45c2-b20c-aac79ac9e731)

**Comment by xinzhongyouhai** [comment]
你这截图不全啊~用的8090还是6066的？哪一种？
