### ISSUE TITLE
部署文档没了

### ISSUE THREAD

**Issue by CorrectRoadH** [moeakwak/chatgpt-web-share#297]
**Version**
main

**What's your deploying environment?**
- [ ] Docker
- [ ] Caddy
- [x] Other

**Describe the problem**
A clear and concise description of your problem.

README中的部署文档的链接失效了，包括中英文的

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by moeakwak** [comment]
已上线新文档站点
