### ISSUE TITLE
报错~这个不知道怎么回事？

### ISSUE THREAD

**Issue by xinzhongyouhai** [moeakwak/chatgpt-web-share#298]
**Version**
v0.4x

**What's your deploying method?**
- [ ] Docker
- [ ] Caddy
- [ ] Other
![微信截图_20231124225834](https://github.com/moeakwak/chatgpt-web-share/assets/128223360/54fb63a4-debc-4038-b6f3-18facd4a7954)

2023/11/25 15:41:02.416     INFO: [cws.access]	172.18.0.1:0 | GET /conv HTTP/1.1 | 200 OK | 43 ms
2023/11/25 15:41:16.551     INFO: [uvicorn.error]	('172.18.0.1', 0) - "WebSocket /chat" [accepted]
2023/11/25 15:41:16.556     INFO: [uvicorn.error]	connection open
2023/11/25 15:41:16.564     INFO: [cws.api.routers.chat]	badskins connected to websocket
2023/11/25 15:41:16.897    ERROR: [cws.api.routers.chat]	All connection attempts failed
2023/11/25 15:41:16.910    DEBUG: [cws.api.routers.chat]	terminated ask None (gpt_3_5) because of error
2023/11/25 15:41:17.206     INFO: [uvicorn.error]	connection closed
2023/11/25 15:41:17.778     INFO: [cws.access]	172.18.0.1:0 | GET /user/me HTTP/1.1 | 200 OK | 23 ms
2023/11/25 15:41:31.725     INFO: [cws.access]	172.18.0.1:0 | GET /user/me HTTP/1.1 | 200 OK | 24 ms

**Comment by what0o0** [comment]
``chatgpt_base_url``配置成``http://127.0.0.1:8080/chatgpt/backend-api/``也会提示``HTTP错误``，后面把 127.0.0.1 改成外网 ip 就可以了。
config.yaml
```ymal
chatgpt_base_url：http://外网:8080/chatgpt/backend-api/
```

**Comment by xinzhongyouhai** [comment]
ok我试试
