### ISSUE TITLE
对话删除Bug

### ISSUE THREAD

**Issue by UltraSoundX** [moeakwak/chatgpt-web-share#301]
作者你好，如果我在openai中删除了在chatgpt share中创建的对话，返回gptshare后再删除会提示会话无效，无法正常删除，只能通过后台管理页面清空所有会话，而使用该功能会导致openai所有的会话消失（无论是否是gptshare创建的），因此我想提出一个功能改进：在后台点击会话删除后，能否只删除在GPTshare创建的会话而不删除openai中的所有会话呢？

**Comment by moeakwak** [comment]
你使用的是最新版本么？

如果在ChatGPW网页上删除了对话，在CWS上：

- 用户访问时会提示 404 错误，后台自动标记 invalid，用户刷新后该会话会消失
- 管理员在后台随时可以通过彻底删除对话删除该对话（对话管理里多选后出现按钮）
