### ISSUE TITLE
回答显示不完整~

### ISSUE THREAD

**Issue by xinzhongyouhai** [moeakwak/chatgpt-web-share#304]
**Version**
v0.4.1
![微信截图_20231127113156](https://github.com/moeakwak/chatgpt-web-share/assets/128223360/f2f2b178-da46-46e8-b5c3-e3beba2436d5)
实际上已经回答完了~可是显示不完整~这个时候我刷新下页面，回答的答案才会全部显示出来~

**Comment by xinzhongyouhai** [comment]
![22](https://github.com/moeakwak/chatgpt-web-share/assets/128223360/80b99bd5-898b-43a8-817b-175cf5b453a8)
报错弹出的时候~就停止显示了~直到回答完成了我刷新下页面~就显示出来后面的了~

**Comment by moeakwak** [comment]
1006可能是在回复的时候，websocket连接断开了，比如网络断了之类的
