### ISSUE TITLE
使用api发起聊天，第二次发送消息会报错

### ISSUE THREAD

**Issue by huoxingyongren** [moeakwak/chatgpt-web-share#306]
**Version**
v0.4.2

**What's your deploying method?**
Docker

**Describe the bug**
使用api发起聊天，第二次发送消息会报错

**To Reproduce**
![Uploading image.png…]
![chat1](https://github.com/moeakwak/chatgpt-web-share/assets/23090701/720600fc-566c-423a-8131-b16c9515a29c)
![chat2](https://github.com/moeakwak/chatgpt-web-share/assets/23090701/0c36a5ed-1c91-4b66-b0a3-70f45d962ab2)
()

**Comment by spammenotinoz** [comment]
Thanks, I thought it was just me..
First message is always fine.  Does not occur on 0.4.1

**Comment by moeakwak** [comment]
0.4.3 已修复
