### ISSUE TITLE
官网用了GPTs 后，会话同步后，会话管理页面会报错 Request error

### ISSUE THREAD

**Issue by maxduke** [moeakwak/chatgpt-web-share#307]
**Version**
v0.4.2

**What's your deploying method?**
- [X] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
官网用了GPTs 后，会话同步后会报错，日志报gpt-4-gizmo 不在定义的 model 里

**Comment by moeakwak** [comment]
将在 0.4.4 中修复
