### ISSUE TITLE
Can't use GPT-4 All Tools Conversation

### ISSUE THREAD

**Issue by nothing0here** [moeakwak/chatgpt-web-share#308]
**Version**
v0.4.2

**What's your deploying environment?**
- [ √] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
个人使用的Plus账号，部署最新版本到可以直连openai的VPS后，GPT-3.5 (OpenAI Web)使用正常，但是使用GPT-4 All Tools (OpenAI Web)进行会话时提示：
“获取回复失败
OpenAI 服务器错误 (500 错误)，可能是 OpenAI 服务故障或者模型接口发生变更，请告知管理员”

**Screenshots or running logs**
2023/11/29 20:07:38.632    ERROR: [cws.api.routers.chat]	OpenaiWebException: [500] errors.openaiWeb {"code":"500","msg":"No solver available or solver is invalid"}
2023/11/29 20:07:38.658    DEBUG: [cws.api.routers.chat]	terminated ask None (gpt_4) because of error

**Comment by dashug** [comment]
遇到过，应该是要传har

**Comment by moeakwak** [comment]
har 没配好
