### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by xinzhongyouhai** [moeakwak/chatgpt-web-share#310]
**Version**
v0.4.2

今天用的官方网页的教程https://cws-docs.pages.dev/zh/guide/quick-start.html#%E4%BB%8B%E7%BB%8D
因为先前0.4.1用的该教程和https://eavan-dev.notion.site/chatgpt-6274f6cb281e4739a2a31ae98d59fced教程修改后搭建成功

今天想升级0.4.2，所以没有第二个连接的教程修改文件
{因为那个好像是老版本的~怕不兼容}

这次完全按照https://cws-docs.pages.dev/zh/guide/quick-start.html#%E4%BB%8B%E7%BB%8D安装操作

![微信截图_20231130145648](https://github.com/moeakwak/chatgpt-web-share/assets/128223360/db5bfbcb-2cb2-403e-8e6d-52a905391909)
![2](https://github.com/moeakwak/chatgpt-web-share/assets/128223360/fddd157b-8f93-4c7b-b4cb-81670df5e7d3)
![3](https://github.com/moeakwak/chatgpt-web-share/assets/128223360/59bfbd5c-dfdd-4581-9a71-9cb1071cc9b9)

然后报错

**Comment by xinzhongyouhai** [comment]
2023/11/30 15:29:35.821     INFO: [cws.api.routers.chat] admin connected to websocket
2023/11/30 15:29:37.169  WARNING: [cws.api.sources.openai_web] Field missing. Details: {'conversation_id': 'eda98478-bf7e-4a0c-9c9a-15755c828585', 'message_id': '09864634-006b-4101-b85f-11796b3eafcd', 'is_completion': False, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-8QVmKuFY9qPj1ip08HjL59NfIOonW'}}
2023/11/30 15:29:37.630  WARNING: [cws.api.sources.openai_web] Field missing. Details: {'conversation_id': 'eda98478-bf7e-4a0c-9c9a-15755c828585', 'message_id': 'c7b28ebf-b69d-471a-a1de-2185d13a778a', 'is_completion': True, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-8QVmL28vwxphoqBcwc03MgBqWDms6'}}
2023/11/30 15:29:37.663    DEBUG: [cws.api.routers.chat] finished ask eda98478-bf7e-4a0c-9c9a-15755c828585 (gpt_3_5), user: 1, ask: 1.469s, total: 1.469s

**Comment by moeakwak** [comment]
截图来看是因为 ninja 的 har 没配好。

如果还有问题，可以在群里提问。
