### ISSUE TITLE
API-4.0-内容空白

### ISSUE THREAD

**Issue by joey-41** [moeakwak/chatgpt-web-share#318]
**Version**
v0.4.3

**What's your deploying environment?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
使用中转API，3.5 正常使用，4.0 显示空白（Next Web 中转是可以正常使用 4.0 的）。
查看原始消息 content 为空
content:{
content_type:"text"
text:""
}

**Screenshots or running logs**
2023/12/04 23:13:38.703     INFO: [uvicorn.error]	('172.18.0.1', 0) - "WebSocket /chat" [accepted]
2023/12/04 23:13:38.705     INFO: [uvicorn.error]	connection open
2023/12/04 23:13:38.709     INFO: [cws.api.routers.chat]	admin connected to websocket
2023/12/04 23:13:43.645  WARNING: [cws.api.sources.openai_api]	OpenAIChatResponse validate error: 1 validation error for OpenaiChatResponse
choices.0.delta.role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2023/12/04 23:13:43.645  WARNING: [cws.api.sources.openai_api]	OpenAIChatResponse validate error: 1 validation error for OpenaiChatResponse
choices.0.delta.role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2023/12/04 23:13:43.646  WARNING: [cws.api.sources.openai_api]	OpenAIChatResponse validate error: 1 validation error for OpenaiChatResponse
choices.0.delta.role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2023/12/04 23:13:43.646  WARNING: [cws.api.sources.openai_api]	OpenAIChatResponse validate error: 1 validation error for OpenaiChatResponse
choices.0.delta.role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2023/12/04 23:13:43.646  WARNING: [cws.api.sources.openai_api]	OpenAIChatResponse validate error: 1 validation error for OpenaiChatResponse
choices.0.delta.role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2023/12/04 23:13:43.647  WARNING: [cws.api.sources.openai_api]	OpenAIChatResponse validate error: 1 validation error for OpenaiChatResponse
choices.0.delta.role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2023/12/04 23:13:43.647  WARNING: [cws.api.sources.openai_api]	OpenAIChatResponse validate error: 1 validation error for OpenaiChatResponse
choices.0.delta.role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2023/12/04 23:13:43.647  WARNING: [cws.api.sources.openai_api]	OpenAIChatResponse validate error: 1 validation error for OpenaiChatResponse
choices.0.delta.role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2023/12/04 23:13:43.648  WARNING: [cws.api.sources.openai_api]	OpenAIChatResponse validate error: 1 validation error for OpenaiChatResponse
choices.0.delta.role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2023/12/04 23:13:43.648  WARNING: [cws.api.sources.openai_api]	OpenAIChatResponse validate error: 1 validation error for OpenaiChatResponse
choices.0.delta.role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2023/12/04 23:13:43.648  WARNING: [cws.api.sources.openai_api]	OpenAIChatResponse validate error: 1 validation error for OpenaiChatResponse
choices.0.delta.role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2023/12/04 23:13:43.649  WARNING: [cws.api.sources.openai_api]	OpenAIChatResponse validate error: 1 validation error for OpenaiChatResponse
choices.0.delta.role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2023/12/04 23:13:43.649  WARNING: [cws.api.sources.openai_api]	OpenAIChatResponse validate error: 1 validation error for OpenaiChatResponse
choices.0.delta.role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2023/12/04 23:13:43.650    DEBUG: [cws.api.routers.chat]	finished ask fb1e8e06-14f5-4d86-b6d5-ab5838f6784a (gpt_4), user: 1, ask: 4.661s, total: 4.661s
2023/12/04 23:13:43.654    DEBUG: [cws.api.routers.chat]	saved new api conversation history fb1e8e06-14f5-4d86-b6d5-ab5838f6784a to mongodb
2023/12/04 23:13:43.917     INFO: [uvicorn.error]	connection closed

**Comment by moeakwak** [comment]
参考 https://platform.openai.com/docs/api-reference/chat/streaming

delta 中的 role 不可为空，这是中转 api 的实现存在问题。请联系该项目进行修复。
