### ISSUE TITLE
moeakwak/chatgpt-web-share镜像并不存在于docker hub

### ISSUE THREAD

**Issue by Cb1ock** [moeakwak/chatgpt-web-share#320]

**Comment by moeakwak** [comment]
目前项目主体迁移了。稍后会更新文档

**Comment by wwtttt** [comment]
我还是遇到这个问题
➜  ~ docker pull moeakwak/chatgpt-web-share:latest
Error response from daemon: pull access denied for moeakwak/chatgpt-web-share, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
