### ISSUE TITLE
求助，500错误

### ISSUE THREAD

**Issue by wyq282** [moeakwak/chatgpt-web-share#324]
升级到0.4.4，Har文件也重新更新了，怎么报500错误？
![image](https://github.com/chatpire/chatgpt-web-share/assets/57173085/1fa0480c-0d46-4433-99c9-827f1a377b76)

**Comment by wyq282** [comment]
还原到0.4.1后又正常了！

**Comment by moeakwak** [comment]
500一般是openai的问题
