### ISSUE TITLE
 base64 decode failure error

### ISSUE THREAD

**Issue by nekomaido** [moeakwak/chatgpt-web-share#328]
**Version**
v0.4.4

**What's your deploying environment?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
When i use sent out the chat,it has an error of this
2023/12/20 16:56:22.049    ERROR: [cws.api.routers.chat] OpenaiWebException: [403] errors.openaiWeb {"code":"403","msg":"Invalid Input: base64 decode failure"}

**Additional context**
#docker-compose.yml
version: "3"

services:
  chatgpt-web-share:
    image: ghcr.io/chatpire/chatgpt-web-share:latest
    container_name: cws
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./data:/app/backend/data
    environment:
      - TZ=Asia/Shanghai
      - CWS_CONFIG_DIR=/app/backend/data/config
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: groundhog2k/mongo:6.0.9
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  ninja:
    image: ghcr.io/gngpp/ninja:latest
    container_name: ninja
    restart: unless-stopped
    command: run --disable-webui
    ports:
      - "7999:7999"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./har/gpt3:/root/.gpt3"
      - "./har/gpt4:/root/.gpt4"

**Comment by Meowbotz-ll** [comment]
突然又可以了

**Comment by Oliverwqcwrw** [comment]
我也遇到这个错误了，我是用的0.4.5，成功用了两天之后就不能发送消息了 @moeakwak 这个问题关闭了是因为？

@Meowbotz-ll 你好，这个问题你这边解决了吗

**Comment by moeakwak** [comment]
> 我也遇到这个错误了，我是用的0.4.5，成功用了两天之后就不能发送消息了 @moeakwak 这个问题关闭了是因为？
> 
> @Meowbotz-ll 你好，这个问题你这边解决了吗

关闭这个问题是因为提问者没有提供日志和更多的其它信息，无从排查。

错误信息是来自上游请求，如 Ninja，和 cws 也无关。建议尝试及时更换 Access Token，确保 token 填写正确，这个可能是 jwt 解析错误导致的。
