### ISSUE TITLE
绘画无法进行保存Server failed to authenticate the request

### ISSUE THREAD

**Issue by the2ndface** [moeakwak/chatgpt-web-share#338]
**Version**
v0.4.5
**What's your deploying method?**
- [ ✓ ] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
可以正常的对话以及使用dalle进行绘画，但是所绘的画无法下载下来。自行右键保存的时候是弹出来保存xml文件，点击下载按钮则出现
已经更新token和har文件，直接官方登录正常下载
```
<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:9f2b1edd-e01e-0057-2f61-441fbd000000 Time:2024-01-11T07:40:07.2263819Z</Message>
<AuthenticationErrorDetail>Signed expiry time [Thu, 11 Jan 2024 06:50:51 GMT] must be after signed start time [Thu, 11 Jan 2024 07:40:07 GMT]</AuthenticationErrorDetail>
</Error>
```

**Comment by spammenotinoz** [comment]
Suggest it's likely your browser, check the server hosting WebShare and Ninja is correctly syncing time and your Desktop also has the correct time.
