### ISSUE TITLE
gpt_4 突然变成 gpt-4 然后导致无法进行对话，提示user not allow to use mod

### ISSUE THREAD

**Issue by xixi-furry** [moeakwak/chatgpt-web-share#339]
**Version**
v0.4..5

**What's your deploying method?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
`2024/01/12 15:50:47.677  WARNING: [cws.api.schemas.conversation_schemas]	model gpt-4 not in openai_web models: gpt_3_5|gpt_3_5_mobile|gpt_4|gpt_4_mobile|gpt_4_browsing|gpt_4_code_interpreter|gpt_4_plugins|gpt_4_dalle`

**Comment by moeakwak** [comment]
想一下你是不是改了什么设置？

如果确定是代码有问题，请至少提供日志文件，最好提供你的数据库文件、配置文件以供调试

**Comment by xixi-furry** [comment]
就把gpt-4的模型名字改成了gpt-4-mobile，听说这个模型不会触发限制对话次数

**Comment by xixi-furry** [comment]
然后我之前复现比较多的情况是，改了过后，如果在中途因为网络问题断掉了，再次发问，数据库里的字段就变成了gpt-4而不是gpt_4

**Comment by spammenotinoz** [comment]
Validate you have the default mappings as follows, and always update via the GUI not config file.
![image](https://github.com/chatpire/chatgpt-web-share/assets/29272432/d53dc2fa-a967-43f7-a8a2-12ed36b45095)
Then delete any conversations that were made with the invalid mappings, then restart that should fix the issue.

If that doesn't fix your issue, go back to a clean install and DB.
If you want to use the GPT-4-Mobile model, then you can enable it and use that model.
Yes the mobile model doesn't appear to have any limits, it will however seem dumber as it's been heavily modified to give shorter responses.  Many argue it's closer to 3.5 than 4.
GPT-4 is coded to support All-Tools, probably not the best to map Mobile to this.
