### ISSUE TITLE
http://182.92.158.254:5000/api/system/action/sync-openai-web-conv 接口返回错误

### ISSUE THREAD

**Issue by INTKILOW** [moeakwak/chatgpt-web-share#341]
"{\"code\":500,\"msg\":\"error sending request for url (https://ch***): error trying to connect: operation timed out\"}"

**Comment by INTKILOW** [comment]
http://182.92.158.254:5000/api/status/common 500

**Comment by INTKILOW** [comment]
Fetch conversation error (OpenaiWebException) 500: {"code":500,"msg":"error sending request for url (https://chat.openai.com/backend-api/conversations?offset=0&limit=80): error trying to connect: operation timed out"}

**Comment by INTKILOW** [comment]
怎么配合clash 使用国内的服务器

**Comment by ZhangIvan1** [comment]
我也出现了同样的问题，如果你是docker-compose部署的话，官方文档中的ninja的映射路径需要改一下
```diff docker-compose.yml
 ########
   ninja:
     image: ghcr.io/gngpp/ninja:latest
     container_name: ninja
     hostname: cws-ninja
     restart: unless-stopped
     command: run --disable-webui
 #   ports:
 #     - "7999:7999"
     environment:
       - TZ=Asia/Shanghai
     volumes:
+     - "./har/gpt3:/root/.ninja/gpt3"
+     - "./har/gpt4:/root/.ninja/gpt4"
```



> Fetch conversation error (OpenaiWebException) 500: {"code":500,"msg":"error sending request for url (https://chat.openai.com/backend-api/conversations?offset=0&limit=80): error trying to connect: operation timed out"}

**Comment by ZhangIvan1** [comment]
> 怎么配合clash 使用国内的服务器

可以搜索一下docker+clash实现服务器透明代理
