### ISSUE TITLE
官网网页能用 ，这里就显示超数量了怎么回事

### ISSUE THREAD

**Issue by INTKILOW** [moeakwak/chatgpt-web-share#344]
OpenAI 接口请求过于频繁 (429 错误)，可能是超过模型使用限制，请稍后再试

**Comment by INTKILOW** [comment]
OpenaiWebException: [429] errors.openaiWeb {"detail":{"message":"You have sent too many messages to the model. Please try again later.","code":"model_cap_exceeded","clears_in":840}}

**Comment by moeakwak** [comment]
这和 cws 无关。如果确定可以复现，请去 ninja 提问
