### ISSUE TITLE
是否可以配置自动更新token

### ISSUE THREAD

**Issue by Oliverwqcwrw** [moeakwak/chatgpt-web-share#351]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jurieo** [comment]
二开吧，后台加个账号密码的配置，一下子就弄好了。

**Comment by jurieo** [comment]
试试这个 [https://hub.docker.com/r/jurieo/gpt-web-share](https://hub.docker.com/r/jurieo/gpt-web-share)
