### ISSUE TITLE
无法登录，提示10401 errors

### ISSUE THREAD

**Issue by HartleyLau** [moeakwak/chatgpt-web-share#353]
**Version**
v0.4.5

**What's your deploying environment?**
- [ x ] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
按照官网的文档进行部署后，登录提示10401 errors
<img width="426" alt="PixPin_2024-01-26_21-43-49" src="https://github.com/chatpire/chatgpt-web-share/assets/7857624/73c83f99-f909-4bf2-a91b-0308b4aa53b0">

**Comment by axh2018** [comment]
刚同样这个错误，蹲一个

**Comment by moeakwak** [comment]
密码输错了
