### ISSUE TITLE
OpenaiWebException: [-1] errors.openaiWeb Our systems have detected unusual activity from your system. Please try again later.

### ISSUE THREAD

**Issue by Oliverwqcwrw** [moeakwak/chatgpt-web-share#354]
**Version**
v0.4.0

**What's your deploying method?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**

web 的GPT4使用的时候报这个错，3.5没问题

**To Reproduce**
1. 选择Web，选择GPT4

**Expected behavior**
期待Web可以正常使用GPT4

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

> 
              openai_web:
                enabled: true
                is_plus_account: true
                chatgpt_base_url: http://ninja:7999/backend-api/
                proxy:
                common_timeout: 10
                ask_timeout: 600
                sync_conversations_on_startup: true
                sync_conversations_schedule: false
                sync_conversations_schedule_interval_hours: 12
                enabled_models:
                - gpt_3_5
                - gpt_4
                - gpt_4_code_interpreter
                model_code_mapping:
                  gpt_3_5: gpt-3.5-turbo
                  gpt_3_5_mobile: text-davinci-002-render-sha-mobile
                  gpt_4: gpt-4-turbo-preview
                  gpt_4_mobile: gpt-4-mobile
                  gpt_4_browsing: gpt-4-turbo-preview-browsing
                  gpt_4_plugins: gpt-4-turbo-preview-plugins
                  gpt_4_code_interpreter: gpt-4-code-interpreter
                  gpt_4_dalle: gpt-4-turbo-preview-dalle
                file_upload_strategy: browser_upload_only
                enable_uploading_attachments: true
                enable_uploading_multimodal_images: true
              openai_api:
                enabled: true
                openai_base_url: https://api.openai.com/v1/
                proxy:
                connect_timeout: 10
                read_timeout: 20
                enabled_models:
                - gpt_3_5
                - gpt_4
                model_code_mapping:
                  gpt_3_5: gpt-3.5-turbo-1106
                  gpt_4: gpt-4-0125-preview
              common:
                print_sql: false
                create_initial_admin_user: true
                initial_admin_user_username: admin
                initial_admin_user_password: password
              http:
                host: 127.0.0.1
                port: 8000
                cors_allow_origins:
                - http://localhost
                - http://127.0.0.1
              data:
                data_dir: ./data
                database_url: sqlite+aiosqlite:///data/database.db
                mongodb_url: mongodb://cws:password@mongo:27017
                mongodb_db_name: cws
                run_migration: false
                max_file_upload_size: 104857600
              auth:
                jwt_secret: MODIFY_THIS_TO_RANDOM_SECRET
                jwt_lifetime_seconds: 86400
                cookie_max_age: 86400
                user_secret: MODIFY_THIS_TO_RANDOM_SECRET
              stats:
                ask_stats_ttl: 7776000
                request_stats_ttl: 2592000
                request_stats_filter_keywords:
                - /status
              log:
                console_log_level: DEBUG

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

> 
                      INFO: [cws.api.routers.chat]	admin connected to websocket
              2024/01/27 19:30:36.584    ERROR: [cws.api.routers.chat]	OpenaiWebException: [-1] errors.openaiWeb Our systems have detected unusual activity from your system. Please try again later.
              2024/01/27 19:30:36.597    DEBUG: [cws.api.routers.chat]	terminated ask 51c13ad9-ae64-42c2-81da-83e22bd1de4d (gpt_4_code_interpreter) because of error
              2024/01/27 19:30:36.858     INFO: [uvicorn.error]	connection closed
              2024/01/27 19:30:37.164     INFO: [cws.access]	74.48.81.158:0 | GET /user/me HTTP/1.1 | 200 OK | 21 ms

**Additional context**

**Comment by jurieo** [comment]
这跟这个库没关系，跟你用的chatgpt_base_url有关系

**Comment by moeakwak** [comment]
请看 Ninja 文档。这种情况可能是 IP 被 ban 等原因。

**Comment by spammenotinoz** [comment]
HAR expiring can also cause this
