### ISSUE TITLE
运行一次 Docker 容器，创建配置文件 执行报错

### ISSUE THREAD

**Issue by zhoushao2018** [moeakwak/chatgpt-web-share#355]
**Version**
v0.4.5

**What's your deploying environment?**
- [ √] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
按照教程执行第三个步骤时候报错了，完全没看懂咋回事，dokcer已安装

`接下来，运行一次 Docker 容器，创建配置文件：

docker run -it --rm \
  -v $PWD/data/config:/tmp/config \
  moeakwak/chatgpt-web-share:latest \
  python /app/backend/manage.py create_config -O /tmp/config --generate-secrets --mongodb-url "mongodb://cws:${MONGODB_PASSWORD}@mongo:27017" --initial-admin-password "${INITIAL_ADMIN_PASSWORD}" --chatgpt-base-url http://ninja:7999/backend-api/
配`

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

![image](https://github.com/chatpire/chatgpt-web-share/assets/63604074/1103e2dd-acfd-44a2-8d65-3d1cbe14b05d)

**Comment by moeakwak** [comment]
这是因为使用了过时的容器名称。已经更新文档，请重新配置，谢谢反馈
