### ISSUE TITLE
无法收到GPT3/GPT4消息，反复打印：ERROR: [uvicorn.error] ASGI callable returned without starting response.

### ISSUE THREAD

**Issue by tudoujunha** [moeakwak/chatgpt-web-share#359]
**Version**
v0.4.5

**What's your deploying environment?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
前端页面一直报错：Request Error，发送GPT3/GPT4消息无法接收到回复，chatgpt官网上可以看到发送出去的消息，但cws收不到回复，控制台一直在打印（ ERROR: [uvicorn.error] ASGI callable returned without starting response.），貌似原因是（ASGI 在返回响应之前就已经结束了，但并没有正确地启动 HTTP 响应过程）

![image](https://github.com/chatpire/chatgpt-web-share/assets/131859738/3446e87c-eded-4845-a005-12cb2aa9e6b3)

![image](https://github.com/chatpire/chatgpt-web-share/assets/131859738/9a11489e-cac4-4250-8dcf-aed50637b4f5)

![image](https://github.com/chatpire/chatgpt-web-share/assets/131859738/685d651e-db6b-41f3-9734-d1315179476b)
**Expected behavior**
cws不再提示Request Error错误， 不再提示 ERROR: [uvicorn.error] ASGI callable returned without starting response.
cws 发送 GPT3/GPT4消息能正常接收到回复。

**Your config.yaml or other configurations**
openai_web:
  enabled: true
  is_plus_account: true
  chatgpt_base_url: http://192.168.10.210:7999/backend-api/
  proxy:
  common_timeout: 20
  ask_timeout: 600
  sync_conversations_on_startup: false
  sync_conversations_schedule: false
  sync_conversations_schedule_interval_hours: 12
  enabled_models:
  - gpt_3_5
  - gpt_4
  - gpt_4_plugins
  model_code_mapping:
    gpt_3_5: text-davinci-002-render-sha
    gpt_3_5_mobile: text-davinci-002-render-sha-mobile
    gpt_4: gpt-4
    gpt_4_mobile: gpt-4-mobile
    gpt_4_browsing: gpt-4-browsing
    gpt_4_plugins: gpt-4-plugins
    gpt_4_code_interpreter: gpt-4-code-interpreter
    gpt_4_dalle: gpt-4-dalle
  file_upload_strategy: browser_upload_only
  disable_uploading: false
openai_api:
  enabled: true
  openai_base_url: https://api.openai.com/v1/
  proxy:
  connect_timeout: 10
  read_timeout: 20
  enabled_models:
  - gpt_3_5
  - gpt_4
  model_code_mapping:
    gpt_3_5: gpt-3.5-turbo
    gpt_4: gpt-4
common:
  print_sql: false
  create_initial_admin_user: true
  initial_admin_user_username: admin
  initial_admin_user_password: password
http:
  host: 127.0.0.1
  port: 8000
  cors_allow_origins:
  - http://localhost:8000
  - http://localhost:5173
  - http://127.0.0.1:8000
  - http://127.0.0.1:5173
data:
  data_dir: ./data
  database_url: sqlite+aiosqlite:///data/database.db
  mongodb_url: mongodb://cws:password@192.168.10.210:27017
  mongodb_db_name: cws
  run_migration: false
  max_file_upload_size: 104857600
auth:
  jwt_secret: AEkoNSKzlSCNXSHm
  jwt_lifetime_seconds: 259200
  cookie_max_age: 259200
  user_secret: cijBt7QbSRBZsiOU
stats:
  ask_stats_ttl: 7776000
  request_stats_ttl: 2592000
  request_stats_filter_keywords:
  - /status
log:
  console_log_level: INFO

--------
Docker compose:
version: "3"

services:
  chatgpt-web-share:
    image: ghcr.io/chatpire/chatgpt-web-share:latest
    container_name: cws
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./data:/app/backend/data
    environment:
      - TZ=${TZ}
      - CWS_CONFIG_DIR=/app/backend/data/config
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  ninja:
    image: ghcr.io/gngpp/ninja:latest
    container_name: ninja
    restart: unless-stopped
    command: run
    ports:
      - "7999:7999"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./har/gpt3:/root/.ninja/gpt3"
      - "./har/gpt4:/root/.ninja/gpt4"

**Screenshots or running logs**
![image](https://github.com/chatpire/chatgpt-web-share/assets/131859738/6d5c9d82-da83-440d-877a-d4c21800d1e7)

**Additional context**
- 在VPS测试有问题，于是在本地虚拟机测试 / 开放端口，还是一样的报错。
- 一开始怀疑是 ninja 的问题，于是单独运行了 ninja，发现 ninja 是正常的（正常显示对话列表，发送GPT3/GPT4消息），但我把运行的ninja 7999接口接入到cws，发现cws还是一样的报错，但找不到问题根源在哪里。 
![image](https://github.com/chatpire/chatgpt-web-share/assets/131859738/369efa31-6e51-4915-856c-65b691cb9917)

**Comment by tudoujunha** [comment]
补充 database.db 和 config.yaml，按照文档配置的，密码都没改.
[db&config.zip](https://github.com/chatpire/chatgpt-web-share/files/14122670/db.config.zip)

**Comment by shenhuxi92** [comment]
一样的问题，昨天还是正常的，今天就不行了，可能是GPT修改了什么东西，但是没有同步

**Comment by moeakwak** [comment]
更新到最新版本重试一下

**Comment by WarsFeng** [comment]
> 更新到最新版本重试一下

最新版本一样现象
