### ISSUE TITLE
后端无法访问chatgpt接口，请求帮助，配置和操作应该没有问题的

### ISSUE THREAD

**Issue by FerryboatSeranade** [moeakwak/chatgpt-web-share#36]
**Version**
v0.2.19

**What's your deploying environment?**
- Docker部署
- ChatGPT Plus已开通
Docker的宿主机Ubuntu中开启了全局clash，美国节点。curl google.com可以正常访问。

**Describe the problem**
前端页面可以正常访问，一旦发生对openai的请求全部无法访问。
不过昨天有一次启动偶然获取到了的会话集合（开了四个会话窗口），之后就再也无法更新，也无法进行对话。
总体表现说明无法正常访问chatgpt。
**Your config.yaml or other configurations**
docker-compose.yml和您最新的Readme.md（2023.3.24晚）中配置完全一样，只修改了config.yaml中的jwt_secret、user_secret和chatgpt_access_token、reverse_proxy_puid（多次查看和修改保证最新）。

**Screenshots or running logs**
![image](https://user-images.githubusercontent.com/41131303/227674790-60de0947-1757-4de0-8adf-f917cef7a111.png)

**Additional context**
我自己做的尝试： 进入docker容器内部，wget www.baidu.com能正常下载页面，wget www.google.com就无法连接，这是因为docker容器内部不能利用宿主机的美国代理导致无法访问chat.openai.com所致吗？如果是应该怎么做呢？如果这不是无法访问chat.openai.com的原因，那又应该怎么做呢？

**Comment by moeakwak** [comment]
这是因为 docker 容器内部无法使用到你在外部配置的代理。

1. 如果有其它合适ip地址的服务器，可以在上面配置应用，或者在上面启动proxy，宿主机的chatgpt_base_url设置成proxy的地址，这样受网络影响小。
2. 如果你非要在容器内用代理，这个暂时不支持。
3. 如果实在不好配，你可以尝试就不开启proxy了，这样默认会用公共的proxy。因为你是plus用户所以封号风险较低，但是确实存在风险，这个自己考虑。

**Comment by FerryboatSeranade** [comment]
了解了，知道原因后续应该可以自己解决，多谢您的解答
