### ISSUE TITLE
说完话后 上面进度条消失但是没有反应对话？

### ISSUE THREAD

**Issue by INTKILOW** [moeakwak/chatgpt-web-share#360]

**Comment by neroxps** [comment]
是的 一直正在思考。

**Comment by shenhuxi92** [comment]
出现了同样的问题

**Comment by leozvc** [comment]
Field missing. Details: {'wss_url': 'wss://chatgpt-async-webps-prod-eastus-12.webpubsub.azure.com/client/hubs/H_dXNlci1yNjVoSTNCQ2lDVEN5TzEwajhVeXVRaFE_?access_token= 
websocket 连接有问题 缺字段了

**Comment by linqiu919** [comment]
同样的问题+1

**Comment by qianxundeng** [comment]
同样的问题+1

**Comment by qianxundeng** [comment]
WARNING: [cws.api.sources.openai_web]	Field missing. Details: {'wss_url': 'wss://chatgpt-async-webps-prod-eastus-12.webpubsub.azure.com/client/hubs/H_dXNlci02ZmRYbkhkcGE2S1k0Y2JjczFxUjI5VVg_?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2NoYXRncHQtYXN5bmMtd2VicHMtcHJvZC1lYXN0dXMtMTIud2VicHVic3ViLmF6dXJlLmNvbS9jbGllbnQvaHVicy9IX2RYTmxjaTAyWm1SWWJraGtjR0UyUzFrMFkySmpjekZ4VWpJNVZWZ18iLCJpYXQiOjE3MDY4NDM2NjgsImV4cCI6MTcwNjg0NzI2OCwic3ViIjoidXNlci02ZmRYbkhkcGE2S1k0Y2JjczFxUjI5VVgifQ.ba8p6PmK-q333c_-tkdTDlG40hbeR9t7laCD3tRmiOc', 'expires_at': '2024-02-02T04:14:28.683654+00:00', 'conversation_id': '12e004da-4e31-4ee0-9dc1-50e39fbad5de', 'response_id': '84ef439e1c5b83f2-LAX'}

**Comment by wxs315** [comment]
同样的问题+1

**Comment by spammenotinoz** [comment]
Same issue

**Comment by update757** [comment]
同样问题+1，我是因为从plus升级为team导致的。日志为：
2024/02/02 14:27:28.845     INFO: [cws.api.routers.chat]	admin connected to websocket
2024/02/02 14:27:31.784  WARNING: [cws.api.sources.openai_web]	Field missing. Details: {'wss_url': 'wss://chatgpt-async-webps-prod-eastus-14.webpubsub.azure.com/client/hubs/H_dXNlci1nNjY5ZmpuVkVNNjNMc2JEOHZodGMyZWdfXzhmMWZlNmJiLWIwMGQtNDZmMC1hYjg3LWQ4MzgxYmFiZWNkMA__?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2NoYXRncHQtYXN5bmMtd2VicHMtcHJvZC1lYXN0dXMtMTQud2VicHVic3ViLmF6dXJlLmNvbS9jbGllbnQvaHVicy9IX2RYTmxjaTFuTmpZNVptcHVWa1ZOTmpOTWMySkVPSFpvZEdNeVpXZGZYemhtTVdabE5tSmlMV0l3TUdRdE5EWm1NQzFoWWpnM0xXUTRNemd4WW1GaVpXTmtNQV9fIiwiaWF0IjoxNzA2ODU1MjUyLCJleHAiOjE3MDY4NTg4NTIsInN1YiI6InVzZXItZzY2OWZqblZFTTYzTHNiRDh2aHRjMmVnX184ZjFmZTZiYi1iMDBkLTQ2ZjAtYWI4Ny1kODM4MWJhYmVjZDAifQ.jzPJBm0A7DahJKOj8POSy4NfVPsiOVm0cduitiDB-sQ', 'expires_at': '2024-02-02T07:27:32.307363+00:00', 'conversation_id': '618ee3a0-6067-40ef-9aa0-9ac28ce29ae4', 'response_id': '84f05e68482d236e-SJC'}
2024/02/02 14:27:31.828    DEBUG: [cws.api.routers.chat]	finished ask None (gpt_4), user: 1, ask: 2.81s, total: 2.81s

**Comment by moeakwak** [comment]
OpenAI 更新了对话接口，换成了 WebSocket，所以原先的处理方法失效了。请等待我适配

**Comment by tkizm1** [comment]
ninja已经升级到v0.9.20了

**Comment by Yanyutin753** [comment]
> ninja已经升级到v0.9.20了

等待作者更新啊 很难的 慢慢更 ninja更新也没解决这个问题

**Comment by tkizm1** [comment]
```
2024-02-02T13:56:24.624626Z  INFO request{method=POST uri=/backend-api/conversation version=HTTP/1.1}: tower_http::trace::on_request: started processing request
2024-02-02T13:56:24.747922Z  INFO request{method=POST uri=/backend-api/conversation version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=123 ms status=500
2024-02-02T13:56:24.747960Z  WARN request{method=POST uri=/backend-api/conversation version=HTTP/1.1}: tower_http::trace::on_failure: response failed classification=Status code: 500 Internal Server Error latency=123 ms
```
升级之后报错的
需要修改 `docker-compose.yml` 的映射位置
```
  ninja:
    image: ghcr.io/gngpp/ninja:latest
    container_name: ninja
    restart: unless-stopped
    command: run --disable-webui
    ports:
      - "7999:7999"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./har/gpt3:/root/.ninja/gpt3"
      - "./har/gpt4:/root/.ninja/gpt4"
```

**Comment by tkizm1** [comment]
0.4.6-beta1 可以正常使用
遇到数据库报错
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: conversation.source_id
```
`sqlite3 data/database.db` 给sqlite增加这个字段
```
alter table conversation ADD COLUMN source_id int;
```

**Comment by tkizm1** [comment]
0.4.6-beta2
```
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
```

**Comment by linqiu919** [comment]
0.46版本
[cws.api.routers.chat] OpenaiWebException: [500] errors.openaiWeb {"code":500,"msg":"No solver available or solver is invalid"}

**Comment by moeakwak** [comment]
0.4.6已经修复
