### ISSUE TITLE
出现”未知错误 string indices must be integers“

### ISSUE THREAD

**Issue by aprpure** [moeakwak/chatgpt-web-share#364]
**Version**
v0.4.6

**What's your deploying method?**
- [√] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
更新最新版本以后，使用ChatGPT3.5的时候，出现”未知错误 string indices must be integers“。然后刷新又能够显示提问和回答内容。

**Screenshots or running logs**
![image](https://github.com/chatpire/chatgpt-web-share/assets/35722236/5faa99f3-683d-4537-837f-6cc2104b352d)
![image](https://github.com/chatpire/chatgpt-web-share/assets/35722236/b3009d44-8218-4ae7-be08-af4ba7d9dd74)

**Additional context**
日志：
2024/02/04 01:59:12.687     INFO: [uvicorn.error] connection open
2024/02/04 01:59:12.692     INFO: [cws.api.routers.chat] admin connected to websocket
2024/02/04 01:59:14.242    ERROR: [cws.api.routers.chat] string indices must be integers
2024/02/04 01:59:14.358     INFO: [uvicorn.error] connection closed

**Comment by HiderX** [comment]
我也遇到了这个问题

**Comment by ljq29** [comment]
同样遇到这个问题

**Comment by gitwbe** [comment]
你的docker-compose.yml配置是什么呢

**Comment by xuexiaigc** [comment]
同样遇到这个问题，怎么解？
# cat docker-compose.yml
version: "3"

services:
  chatgpt-web-share:
    image: ghcr.io/chatpire/chatgpt-web-share:latest
    container_name: cws
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./data:/app/backend/data
    environment:
      - TZ=${TZ}
      - CWS_CONFIG_DIR=/app/backend/data/config
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:6.0
    restart: always
    # ports:
    #     #   - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  ninja:
    image: ghcr.io/gngpp/ninja:latest
    container_name: ninja
    restart: unless-stopped
    command: run --disable-webui
    ports:
      - "7999:7999"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./har/gpt3:/root/.gpt3"
      - "./har/gpt4:/root/.gpt4"

**Comment by JQJoe** [comment]
遇到同样的问题

**Comment by xuexiaigc** [comment]
换成 image: ghcr.io/chatpire/chatgpt-web-share:0.4.5，就不会报错了😅

**Comment by DponXiaodong** [comment]
ninja版本要回滚吗，cws改完后ninja拉不起来了
> 换成 image: ghcr.io/chatpire/chatgpt-web-share:0.4.5，就不会报错了😅

**Comment by moeakwak** [comment]
Fixed in v0.4.7
