### ISSUE TITLE
How to use users this system same time

### ISSUE THREAD

**Issue by kadirklc** [moeakwak/chatgpt-web-share#37]
Hello,

I need to help. If one user uses chatgpt, another user can't use chatgpt.  How can I implement two users and more using this system same time.

Regards,
Kadir

**Comment by moeakwak** [comment]
Hello Kadir,

Unfortunately, it is not possible to have multiple users use conversations with ChatGPT concurrently. OpenAI limits this intentionally. Therefore, if one user is using a conversation, other users will have to wait in a queue until it is their turn to use.
