### ISSUE TITLE
sqlite3.OperationalError) no such column: conversation.source_id

### ISSUE THREAD

**Issue by fyh1157fyh** [moeakwak/chatgpt-web-share#373]
**Version**
v0.4.6

**What's your deploying environment?**
- [ ] Docker

**Describe the problem**
登录后报错“Request Error”

**Your config.yaml or other configurations**
都是按照文档设置的

**Screenshots or running logs**
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: conversation.source_id
[SQL: SELECT conversation.id, conversation.source, conversation.source_id, conversation.conversation_id, conversation.current_model, conversation.title, conversation.user_id, conversation.is_valid, conversation.create_time, conversation.update_time 
FROM conversation 
WHERE conversation.source IN (?)]
[parameters: ('openai_web',)]

**Additional context**
这个错误信息来自一个尝试在 SQLite 数据库上执行 SQL 查询的 Python 应用程序，使用了 SQLAlchemy 库。错误的具体内容是一个 OperationalError，指出在执行查询时遇到了问题：“no such column: conversation.source_id”，意味着在 conversation 表中找不到名为 source_id 的列。

**Comment by Coinsinical** [comment]
在更新后若出现数据库相关报错，请确保设置中已经打开 run_migration 选项，以便在更新后自动执行数据库迁移。
