### ISSUE TITLE
账号有GPT4但对话会报错“OpenAI 接口不存在 (404 错误)，请联系管理员处理 OpenaiApiException: [404] errors.openaiWeb { "error": { "message": "The model `gpt-4` does not exist or you do not have access to it. Learn more: https://he***", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }”

### ISSUE THREAD

**Issue by Longwt123** [moeakwak/chatgpt-web-share#375]
**Version**
v0.4.6

**What's your deploying environment?**
- [*] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
账号有GPT4但对话会报错
OpenAI 接口不存在 (404 错误)，请联系管理员处理 OpenaiApiException: [404] errors.openaiWeb { "error": { "message": "The model `gpt-4` does not exist or you do not have access to it. Learn more: https://he***", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }

**Expected behavior**
请大佬指点解决 API 访问 GPT4 的问题。
（之前问题解决后，API 的 GPT3 能使用，但 WEB 不能用还是报错，API 的 GPT4 也不能用）

**Your config.yaml or other configurations**
配置与文档一样，除了mongo:6.0-focal（为了解决mongo容器一直重启的问题）

**Screenshots or running logs**
---
2024/02/06 21:59:43.646     INFO: [uvicorn.error] ('112.96.114.133', 0) - "WebSocket /chat" [accepted]
2024/02/06 21:59:43.655     INFO: [uvicorn.error] connection open
2024/02/06 21:59:43.661     INFO: [cws.api.routers.chat] admin connected to websocket
/usr/local/lib/python3.10/site-packages/pydantic/main.py:314: UserWarning: Pydantic serializer warnings:
  Expected `uuid` but got `str` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
2024/02/06 21:59:45.681     INFO: [uvicorn.error] connection closed
2024/02/06 21:59:45.775     INFO: [cws.access] 112.96.114.133:0 | GET /conv HTTP/1.1 | 200 OK | 26 ms
2024/02/06 21:59:45.861     INFO: [cws.access] 112.96.114.133:0 | GET /user/me HTTP/1.1 | 200 OK | 20 ms
2024/02/06 21:59:53.048     INFO: [uvicorn.error] ('112.96.114.133', 0) - "WebSocket /chat" [accepted]
2024/02/06 21:59:53.051     INFO: [uvicorn.error] connection open
2024/02/06 21:59:53.057     INFO: [cws.api.routers.chat] admin connected to websocket
2024/02/06 21:59:56.722     INFO: [uvicorn.error] connection closed
2024/02/06 21:59:56.815     INFO: [cws.access] 112.96.114.133:0 | GET /conv HTTP/1.1 | 200 OK | 24 ms
2024/02/06 21:59:56.907     INFO: [cws.access] 112.96.114.133:0 | GET /user/me HTTP/1.1 | 200 OK | 21 ms
2024/02/06 22:00:07.865     INFO: [uvicorn.error] ('112.96.114.133', 0) - "WebSocket /chat" [accepted]
2024/02/06 22:00:07.869     INFO: [uvicorn.error] connection open
2024/02/06 22:00:07.874     INFO: [cws.api.routers.chat] admin connected to websocket
2024/02/06 22:00:08.153    ERROR: [cws.api.routers.chat] OpenaiApiException: [404] errors.openaiWeb {
    "error": {
        "message": "The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

2024/02/06 22:00:08.202     INFO: [uvicorn.error] connection closed
2024/02/06 22:00:08.310     INFO: [cws.access] 112.96.114.133:0 | GET /user/me HTTP/1.1 | 200 OK | 25 ms
---

**Additional context**
我使用curl测试过 key 应该没问题，accessToken也是新的。
服务器可以ping通官网，应该没有网络问题或IP封锁问题。
还有个小问题，我重新按文档下载docker运行的，但登录后看到版本还是v0.4.6，但我看release已经到
0.4.7了，不知道怎么弄。

除解决API访问GPT4之外，请大佬指点解决WEB访问的问题。

**Comment by moeakwak** [comment]
置顶 issue 为什么不看呢？https://github.com/chatpire/chatgpt-web-share/issues/372

1. 关于报错：你看了报错信息吗？确定你的 api 能正常使用 gpt-4 吗？
2. 关于如何升级：你仔细看过文档了吗？

**Comment by Longwt123** [comment]
> 置顶 issue 为什么不看呢？#372
> 
> 1. 关于报错：你看了报错信息吗？确定你的 api 能正常使用 gpt-4 吗？
> 2. 关于如何升级：你仔细看过文档了吗？

1. 奥，抱歉我忘记说了，但我账号应该可以用gpt4，我测试的curl就是用gpt4写的。获取key和accessToken时也可以，现在也正在用，插件也可以。
2. 我又仔细看了文档，关于升级我疏忽了，我删除docker image和容器后重新弄了，现在是v0.4.7了。但还是报错。
API3.5可以；
API4“OpenAI 接口不存在 (404 错误)，请联系管理员处理 OpenaiApiException: [404] errors.openaiWeb { "error": { "message": "The model `gpt-4` does not exist or you do not have access to it. Learn more: https://he***", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }”；
WEB的每一个“HTTP错误 [Errno -5] Name has no usable address”

**Comment by moeakwak** [comment]
> 1. 奥，抱歉我忘记说了，但我账号应该可以用gpt4，我测试的curl就是用gpt4写的

你是怎么确认你的 API 可以用 gpt-4 的？
