### ISSUE TITLE
v0.4.7 使用自改go-chatgpt-api “未知错误 the JSON object must be str, bytes or bytearray, not dict”

### ISSUE THREAD

**Issue by maxduke** [moeakwak/chatgpt-web-share#376]
**Version**
v0.4.7

**What's your deploying method?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
使用自己魔改版的go-chatgpt-api https://github.com/maxduke/go-chatgpt-api ，把wss转换成event stream达成兼容。
v0.4.5对话正常。
v0.4.7报错

“获取回复失败
未知错误 the JSON object must be str, bytes or bytearray, not dict”

**Expected behavior**
希望能兼容go-chatgpt-api的输出

**Comment by moeakwak** [comment]
你好，我没有精力去做这个兼容了。如果你改好了，欢迎 PR

**Comment by maxduke** [comment]
https://github.com/chatpire/chatgpt-web-share/pull/377
