### ISSUE TITLE
JWT claims invalid: Failed to split JWT into header.claims.signature parts

### ISSUE THREAD

**Issue by wasabilofgu** [moeakwak/chatgpt-web-share#379]
**Version**
v0.x.x

**What's your deploying method?**
- [√ ] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
ask gpt question and got a response "JWT claims invalid: Failed to split JWT into header.claims.signature parts" 
cws logs:

2024/02/08 10:41:38.087     INFO: [cws.api.routers.chat] admin connected to websocket
2024/02/08 10:41:38.331    ERROR: [cws.api.routers.chat] <OpenaiWebException> OpenaiWebException: [403] errors.openaiWeb {"code":403,"msg":"JWT claims invalid: Failed to split JWT into header.claims.signature parts"}
traceback:
/app/backend/api/routers/chat.py:356 in chat
/app/backend/api/sources/openai_web.py:387 in complete
/app/backend/api/sources/openai_web.py:142 in _check_response
2024/02/08 10:41:38.553     INFO: [uvicorn.error] connection closed

not sure this error from cws or ninja

cws docker image id 8145d6f415d5
ninja docker image id 7b4fdfb274a4

i got the latest image update at 2024/02/08 10:00:00(+8)

**Comment by paranoiagu** [comment]
logoff and login again

**Comment by wasabilofgu** [comment]
my mistake 
i update cws and forgot upload accesstoken 
PLZ close this issue
