### ISSUE TITLE
gpt4无法正常使用，报错"Our systems have detected unusual activity from your system. Please try again later."

### ISSUE THREAD

**Issue by gitxws** [moeakwak/chatgpt-web-share#380]
**Version**
v0.4.7

**What's your deploying method?**
- [x ] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
已更新至最新的docker版本，gpt4无法正常使用，报错"Our systems have detected unusual activity from your system. Please try again later."已排除账号和IP问题，基本可以确定是ninja的问题，但是ninja那边已经明确回复要停止更新了，请作者重新适配其他方式访问gpt4。
[ninja will stop service](https://github.com/gngpp/ninja/issues/539#issuecomment-1933315913)

**Screenshots or running logs**

> 2024/02/08 10:37:15.796     INFO: [uvicorn.error]	Started server process [1]
> 2024/02/08 10:37:15.796     INFO: [uvicorn.error]	Waiting for application startup.
> 2024/02/08 10:37:15.801     INFO: [cws.api.database.sqlalchemy]	Database initialized.
> 2024/02/08 10:37:15.836     INFO: [cws.api.database.mongodb]	MongoDB initialized. dataSize: 2.66 MB, objects: 1012
> 2024/02/08 10:37:15.885    DEBUG: [cws.main]	admin already exists, skip creating admin user
> 2024/02/08 10:37:15.893     INFO: [cws.main]	Using http://ninja:7999/backend-api/ as ChatGPT base url
> 2024/02/08 10:37:15.894     INFO: [cws.utils.admin.sync_conv]	Start syncing conversations...
> 2024/02/08 10:37:17.414     INFO: [cws.utils.admin.sync_conv]	Fetched 160 conversations from ChatGPT Personal account.
> 2024/02/08 10:37:17.427     INFO: [cws.utils.admin.sync_conv]	Conversation 377d66ca-b8b6-4c41-9b12-8416bfa9302c create time changed：2024-02-07 08:43:55.492745+00:00
> 2024/02/08 10:37:17.428     INFO: [cws.utils.admin.sync_conv]	Conversation b51dc0a2-f165-46e4-b984-3e06d9e65910 create time changed：2024-02-07 08:46:59.832241+00:00
> 2024/02/08 10:37:17.428     INFO: [cws.utils.admin.sync_conv]	Add new conversation [Normal Work Possible](48142cb5-7f2f-479b-a9d0-56a09aafec75)
> 2024/02/08 10:37:17.428     INFO: [cws.utils.admin.sync_conv]	Add new conversation [GPT-4 RESPONDS TO USER](dbc0b4be-1362-4828-8990-e0748e3f20b6)
> 2024/02/08 10:37:17.439     INFO: [cws.utils.admin.sync_conv]	Sync conversations finished.
> 2024/02/08 10:37:17.440     INFO: [uvicorn.error]	Application startup complete.
> 2024/02/08 10:37:17.440     INFO: [uvicorn.error]	Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
> 2024/02/08 10:37:50.689     INFO: [cws.access]	162.158.118.54:0 | GET /conv HTTP/1.1 | 200 OK | 28 ms
> 2024/02/08 10:37:53.411     INFO: [cws.access]	162.158.118.54:0 | GET /conv/377d66ca-b8b6-4c41-9b12-8416bfa9302c HTTP/1.1 | 200 OK | 287 ms
> 2024/02/08 10:38:03.129     INFO: [uvicorn.error]	('172.68.118.123', 0) - "WebSocket /chat" [accepted]
> 2024/02/08 10:38:03.132     INFO: [uvicorn.error]	connection open
> 2024/02/08 10:38:03.136     INFO: [cws.api.routers.chat]	admin connected to websocket
> 2024/02/08 10:38:04.591    DEBUG: [cws.api.routers.chat]	finished ask 377d66ca-b8b6-4c41-9b12-8416bfa9302c (gpt_3_5_mobile), user: 1, ask: 1.291s, total: 1.291s
> 2024/02/08 10:38:04.724     INFO: [uvicorn.error]	connection closed
> 2024/02/08 10:38:04.896     INFO: [cws.access]	162.158.118.54:0 | GET /conv HTTP/1.1 | 200 OK | 26 ms
> 2024/02/08 10:38:05.099     INFO: [cws.access]	162.158.118.54:0 | GET /user/me HTTP/1.1 | 200 OK | 17 ms
> 2024/02/08 10:38:13.212     INFO: [uvicorn.error]	('172.70.222.153', 0) - "WebSocket /chat" [accepted]
> 2024/02/08 10:38:13.214     INFO: [uvicorn.error]	connection open
> 2024/02/08 10:38:13.218     INFO: [cws.api.routers.chat]	admin connected to websocket
> 2024/02/08 10:38:20.294  WARNING: [cws.api.sources.openai_web]	error in message stream: {"message": null, "conversation_id": "8cd625e1-cfb9-4051-8db3-b33e3698b2d5", "error": "Our systems have detected unusual activity from your system. Please try again later."}
> 2024/02/08 10:38:20.296    ERROR: [cws.api.routers.chat]	<OpenaiWebException> OpenaiWebException: [-1] errors.openaiWeb Our systems have detected unusual activity from your system. Please try again later.
> traceback:
> /app/backend/api/routers/chat.py:356 in chat
> /app/backend/api/sources/openai_web.py:418 in complete
> 2024/02/08 10:38:20.309    DEBUG: [cws.api.routers.chat]	terminated ask 8cd625e1-cfb9-4051-8db3-b33e3698b2d5 (gpt_4) because of error
> 2024/02/08 10:38:20.436     INFO: [uvicorn.error]	connection closed

**Comment by moeakwak** [comment]
尝试启用：https://cws-docs.pages.dev/zh/guide/manual.html#%E4%BD%BF%E7%94%A8-arkose-endpoint

**Comment by Cod1ng** [comment]
> 尝试启用：https://cws-docs.pages.dev/zh/guide/manual.html#%E4%BD%BF%E7%94%A8-arkose-endpoint

请问此时 ninja 本身的 docker-compose 应该怎么设置，目前我是这么设置的：
```
  ninja:
    image: ghcr.io/gngpp/ninja:latest
    container_name: ninja
    restart: unless-stopped
    command: run --enable-webui --arkose-endpoint https://ninjabackend.xxx.xyz --enable-arkose-proxy
    ports:
      - 7999:7999
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./ninja:/root/.ninja"
  ```

然后https://ninjabackend.xxx.xyz设置了到服务器的 7999 端口的反代
然后 cws 里设置的Arkose Endpoint Base 是https://ninjabackend.xxx.xyz/v2/
      
但是老是Failed to get Arkose token，求教

**Comment by moeakwak** [comment]
--enable-arkose-proxy 拿掉

确认一下 `你的域名/v2/35536E1E-65B4-4D96-9D97-6ADB7EFF8147/api.js` 是否正常返回内容
