### ISSUE TITLE
请教0.4.8的安装问题~~~

### ISSUE THREAD

**Issue by xinzhongyouhai** [moeakwak/chatgpt-web-share#387]
**Version**
v0.4.8
创建另一个同级的 ninja 目录，用于存放 Ninja 的配置文件。Ninja 是 ChatGPT 代理，用于跨过 Cloudflare 验证以生成对话时的 Arkose 验证码。这个是不是 理解为cws和ninja在同一级目录？那ninja下也要新建一个 docker-compose.yml文件不？？

还有使用：version: "3"

services:
  chatgpt-web-share:
    image: ghcr.io/chatpire/chatgpt-web-share:latest
    container_name: cws
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./data:/app/backend/data
    environment:
      - TZ=${TZ}
      - CWS_CONFIG_DIR=/app/backend/data/config
    depends_on:
      - mongo
    networks:
      - cwsnetwork

  mongo:
    container_name: mongo
    image: mongo:6.0
    restart: always
    # ports:
    #   - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - cwsnetwork

networks:
  cwsnetwork:
    name: cwsnetwork
    external: true
在ssh中报错 ：Error response from daemon: network cwsnetwork not found

**Comment by BaoziCDR** [comment]
You can solve your problem by following these steps:
1. RTFM
2. STFW
3. ATFAI
☺

**Comment by WarsFeng** [comment]
1. 是的
2. `docker network create cwsnetwork`
