### ISSUE TITLE
实在是搞不定了,请教一下

### ISSUE THREAD

**Issue by wxkeykey** [moeakwak/chatgpt-web-share#390]
这种报错大概率是什么问题?
![1bece806bdc7124cdda9b5bdf089c77](https://github.com/chatpire/chatgpt-web-share/assets/61955165/9724d43e-a679-4ff4-b153-5d4fb727c893)
![6d0ea3f33a9b3300c9b2c107cc00103](https://github.com/chatpire/chatgpt-web-share/assets/61955165/8cf95c5c-6003-4903-a39d-7b4b88cde544)
![ce379bb622f51007644b4545a9b6d6b](https://github.com/chatpire/chatgpt-web-share/assets/61955165/7c8500ca-9572-4bbd-be8e-a406271521d6)

**Comment by wxkeykey** [comment]
Openai Web Access Token  是不是填写错误了?

**Comment by windfall4us** [comment]
我试过几次。check不过。都是token写错了。多个了逗号。

**Comment by windfall4us** [comment]
我试过几次。check不过。都是token写错了。多个了逗号。
