### ISSUE TITLE
选择新对话中的两个下拉框，如果展开过其中一个之后，下拉框就回无法切换

### ISSUE THREAD

**Issue by Oliverwqcwrw** [moeakwak/chatgpt-web-share#392]
**Version**
v0.4.8

**What's your deploying method?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**

附件为测试视频

**To Reproduce**

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

https://github.com/chatpire/chatgpt-web-share/assets/31796988/d2ba4971-58f7-413b-9c8f-c60146c5a99a

**Comment by yongman** [comment]
应该是依赖有问题，我修改了 naive-ui 版本（2.36.0->2.35.0），重新构建了一下没问题了，再改回原来的版本`2.36.0`竟然也正常了。神奇。
