### ISSUE TITLE
提问中反斜杠会消失不显示，但chatgpt官网中有显示

### ISSUE THREAD

**Issue by aldington-david** [moeakwak/chatgpt-web-share#43]
**Version**
v0.2.19

**What's your deploying method?**
- [/ ] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
提问中反斜杠会消失不显示，但chatgpt官网中有显示。且回答中识别到了。

**To Reproduce**
1. 打开对话页面
2. 发送linux命令中-exec sh -c 'cat /dev/null > "$0"' {} \;有什么用
3. 显示的提问中最后分号前反斜杠会消失，无论在命令前后加不加双引号。

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by aldington-david** [comment]
好吧github中也有这个问题。
`-exec sh -c 'cat /dev/null > "$0"' {} \;`

**Comment by moeakwak** [comment]
你得用markdown格式，加上 ` 就好了
