### ISSUE TITLE
前端问题反馈 ios端  无法正常显示对话框

### ISSUE THREAD

**Issue by prideLuv** [moeakwak/chatgpt-web-share#45]
个人设备：ipad air 3
尝试浏览器:Safari/google/夸克
尝试浏览器UA：安卓/ios/pc端 
存在问题:均无法显示对话框，发送内容后要点击全屏才可以显示对话内容，但无法退出和无法继续提问
截图:
![1](https://user-images.githubusercontent.com/72843437/228115358-75796791-a91c-45d6-8adf-171171279c63.png)

**Comment by moeakwak** [comment]
并没能成功复现问题

**Comment by prideLuv** [comment]
> 没能成功复现问题，在 iOS 设备上尝试过了，可以正常显示对话内容。
> 
> 我猜，你可以试试用手指按住工具栏（三个按钮那一行）的白色部分，向上拖一下？
我按照你的方法尝试了，不行，无法拖动...ε=(´ο｀*)))唉 还是只有点击全屏才能看到对话

**Comment by moeakwak** [comment]
用的是最新版本么？

btw，提 issue 请按照模版来……

**Comment by prideLuv** [comment]
@moeakwak  突发奇想更新了下ios版本...然后发现可以正常显示了...估计是旧版本不支持
