### ISSUE TITLE
获取回复失败

### ISSUE THREAD

**Issue by ti4n1993** [moeakwak/chatgpt-web-share#48]
<img width="461" alt="CleanShot 2023-03-29 at 13 24 49@2x" src="https://user-images.githubusercontent.com/11803407/228434724-8253fadf-df2e-4fd4-b91f-01843427be6a.png">
accessToken刚换了

**Comment by moeakwak** [comment]
账号或ip地址被封禁，或者网络问题等。这种提示都和本项目无关，是openai那边的问题。

以后提 issue 还请按照模版来，截个图能有什么用？

**Comment by ti4n1993** [comment]
账号和网络都没问题，我用这个服务器的代理访问https://chat.openai.com/chat是可以正常使用的
