### ISSUE TITLE
自定义proxy返回500 Internal Server Error

### ISSUE THREAD

**Issue by shawnchampion** [moeakwak/chatgpt-web-share#50]
国内的服务器，是chatgpt plus，按文档使用的默认的自定义proxy

启动后，网页输入文字，会在等待4分钟后查看到错误日志
ERROR: [cws.api.routers.chat] Server error '500 Internal Server Error' for url 'http://127.0.0.1:6062/api/conversation'

如果通过docker-compose.yml配置网络代理，已经在宿主机验证过网络代理本身是可用的
```
environment:
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
```
会立刻查看到错误日志
ERROR: [cws.api.routers.chat] Server error '502 Bad Gateway' for url 'http://127.0.0.1:6062/api/conversation'

这个问题该怎么解决

**Comment by moeakwak** [comment]
设置HTTP_PROXY和HTTPS_PROXY并不会对api请求生效。所以当你用本地的proxy时，是没有走HTTP_PROXY的。目前暂时不支持设置HTTP_PROXY。

**Comment by shawnchampion** [comment]
> 设置HTTP_PROXY和HTTPS_PROXY并不会对api请求生效。所以当你用本地的proxy时，是没有走HTTP_PROXY的。目前暂时不支持设置HTTP_PROXY。

我尝试了一下单独启动chatgpt-proxy-v4的容器并配置了代理，也没有生效，可能它也没有使用，就是说目前自建proxy得保证在一个没被openai屏蔽的ip是吗

**Comment by moeakwak** [comment]
> 我尝试了一下单独启动chatgpt-proxy-v4的容器并配置了代理，也没有生效，可能它也没有使用，就是说目前自建proxy得保证在一个没被openai屏蔽的ip是吗

目前是这样

**Comment by hiyoungshen** [comment]
> > 设置HTTP_PROXY和HTTPS_PROXY并不会对api请求生效。所以当你用本地的proxy时，是没有走HTTP_PROXY的。目前暂时不支持设置HTTP_PROXY。
> 
> 我尝试了一下单独启动chatgpt-proxy-v4的容器并配置了代理，也没有生效，可能它也没有使用，就是说目前自建proxy得保证在一个没被openai屏蔽的ip是吗

您最终是如何解决的呢？购买一个vps在上面配置吗？
