### ISSUE TITLE
请问能在Vercel上面部署吗？

### ISSUE THREAD

**Issue by alanjustalan** [moeakwak/chatgpt-web-share#55]
我是个技术小白，不是很懂docker，好像还要花钱搭建服务器？想问作者下能否支持下在Vercel上面一键部署呢？

**Comment by moeakwak** [comment]
vercel不行，因为有后端。render倒是有可能。不过都不推荐，使用这类服务无法保证ip地址的质量，有被封号的风险。

**Comment by SivanLaai** [comment]
我觉得部署一个前端在vercel或者railway到是可行，后端就自己部署在服务器上。
