### ISSUE TITLE
[1014] HTTP错误: All connection attempts failed

### ISSUE THREAD

**Issue by leyiweb** [moeakwak/chatgpt-web-share#56]
非常感谢moeakwak开源该项目，我在使用过程中遇到一些困惑，希望能得到帮助

海外VPS，Plus帐号，docker部署
没有配置ChatGPT-Proxy-V4时（默认使用revChatGPT？）能正常使用GPT
按文档配置ChatGPT-Proxy-V4后（仅修改puid），所有对话显示"[1014] HTTP错误: All connection attempts failed"
<img width="480" alt="image" src="https://user-images.githubusercontent.com/21156870/229343494-732ad389-b1b0-4ad1-aa75-e16c81264b1c.png">

这可能是什么原因？

**Comment by moeakwak** [comment]
更新到 0.3.0-alpha3 版本试一下看还有没有这样的问题

检查你的网络环境，账号是否能正常登录，各种token有没有过期

**Comment by leyiweb** [comment]
update fix
