### ISSUE TITLE
希望支持指定路径前缀

### ISSUE THREAD

**Issue by leemzoon** [moeakwak/chatgpt-web-share#57]
nginx 使用location proxy_pass 到 :8080时，由于部分资源是相对于/路径，导致无法正常工作 

**Describe the solution you'd like**
类似react 的homepage实现，指定一个子路径

**Comment by moeakwak** [comment]
参见 [wiki 部署到子目录的说明](https://github.com/moeakwak/chatgpt-web-share/wiki/%E4%B8%AD%E6%96%87%E6%8C%87%E5%8D%97#%E9%83%A8%E7%BD%B2%E5%88%B0%E5%AD%90%E7%9B%AE%E5%BD%95%E4%B8%8B-v035%E7%89%88%E6%9C%AC%E8%B5%B7%E6%94%AF%E6%8C%81)
