### ISSUE TITLE
httpx.HTTPStatusError: Client error '403 Forbidden'

### ISSUE THREAD

**Issue by markwhitey** [moeakwak/chatgpt-web-share#58]
https://github.com/acheong08/ChatGPT/issues/1239#issue-1648405442  
上游似乎已经修复了，希望更新一下~

**Comment by markwhitey** [comment]
注意升级到4.0.12 以上版本 typing.py 更改为typings.py

**Comment by markwhitey** [comment]
升级到最新的版本提示
Traceback (most recent call last):
  File "/app/backend/main.py", line 26, in <module>
    from api.response import CustomJSONResponse, PrettyJSONResponse, handle_exception_response
  File "/app/backend/api/response.py", line 16, in <module>
    from revChatGPT.typings import Error as revChatGPTError
ModuleNotFoundError: No module named 'revChatGPT.typings'

**Comment by markwhitey** [comment]
我知道了,你的poetry没有用呀,应该改requirements.txt 里的revchatgpt 版本

**Comment by moeakwak** [comment]
还没更新requirements呢，最新版本没更新依赖呢，别急别急

**Comment by moeakwak** [comment]
好吧，是我忘记更新requirements.txt了
