### ISSUE TITLE
The error code [1006] meaning?

### ISSUE THREAD

**Issue by ZYM66** [moeakwak/chatgpt-web-share#59]
**Version**
lastest
**What's your deploying environment?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
When I created a conversation, I send a message to server but I got the error code [1006]

**Expected behavior**
I want to talk with chatGPT

**Your config.yaml or other configurations**
I write as the readme type and only changed the token 

**Screenshots or running logs**
<img width="511" alt="截屏2023-04-03 10 48 22" src="https://user-images.githubusercontent.com/61892155/229400671-041aad67-8bad-4998-9666-1a132fbf0346.png">

**Additional context**
PLZ tell me the meaning of the error code 1006

**Comment by ZYM66** [comment]
I got it, maybe it is wss error!

**Comment by ZYM66** [comment]
I work out! Adding the websocket rules to nginx then it will be ok!

**Comment by moeakwak** [comment]
I'm glad to see that you've resolved the issue. If you have any other questions, feel free to bring them up at any time.

**Comment by Lodour** [comment]
For those who encountered this issue when setting up HTTPS, I added the following configs to nginx.
```nginx
location /api {
    proxy_pass http://192.168.x.x:xxxx/api;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

**Comment by hasansert4** [comment]
@Lodour Hello Lodour,
how did you do that ?
I tried to do that on my synology but i wasn't able to fix this issue.

**Comment by spammenotinoz** [comment]
> ```nginx
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "upgrade";
> ```

Hi, I don't have a Synology but on other devices like reverse proxies\firewalls the feature you should enable is "WebSocket passthrough"
Here is a quick link for Synology, but remember all in-path devices, such as your firewall need to support websocket passthrough.
https://mlohr.com/websockets-for-synology-dsm/

**Comment by Lodour** [comment]
Hi @hasansert4, I didn't use synology. I found this problem when checking nginx or container logs, where I saw invalid requests to `/api`. Hope this debugging is helpful.
