### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by blueagler** [moeakwak/chatgpt-web-share#6]
<img width="813" alt="Screenshot 2023-03-16 at 2 19 00 PM" src="https://user-images.githubusercontent.com/61572188/225531689-88b03f1b-b33e-44e2-b382-1932dfea0afc.png">

**Comment by blueagler** [comment]
[database.db.zip](https://github.com/moeakwak/chatgpt-web-share/files/10987391/database.db.zip)

**Comment by moeakwak** [comment]
```
(sqlite3.OperationalError) duplicate column name: model_name
[SQL: ALTER TABLE conversation ADD COLUMN model_name VARCHAR]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
database migration might fail, please check the database manually!
```

这一段提示是正常的，应该不影响使用。显示 Done! 以后为什么会终止，是使用了 Ctrl-C 手动结束了么？

**Comment by moeakwak** [comment]
目前修正了这种报错。如果还有问题，可以删除数据库重新启动。

**Comment by blueagler** [comment]
新版已无问题
