### ISSUE TITLE
能不能吧请求加入队列穿行处理或者限制并发量

### ISSUE THREAD

**Issue by xsean2020** [moeakwak/chatgpt-web-share#60]
当使用的用户太多会报错, Client error '429 Too Many Requests

**Comment by moeakwak** [comment]
是会排队处理的没错。你是否使用的是GPT-4？

**Comment by xsean2020** [comment]
测试多用户的时候 混合使用了 ，四个人同时使用会出现 Client error '429 Too Many Requests， 请问这个错误是chatgpt返回的还是这个项目返回的

**Comment by moeakwak** [comment]
这个错误是chatgpt返回的。但是多人同时使用，应该会提示排队。请确保是最新版本

**Comment by xsean2020** [comment]
好的多谢， 能不能每个用户请求添加一个频率限制， 不然的话 并发太频繁会不会被分析出来呗封号
