### ISSUE TITLE
大佬们好，今天看到不少人说帐号被openAI封锁了。不知道我们使用这个系统会不会有这个风险？

### ISSUE THREAD

**Issue by chinecc** [moeakwak/chatgpt-web-share#61]
**Version**
v0.x.x

**What's your deploying environment?**
- [ ] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
A clear and concise description of your problem.

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by moeakwak** [comment]
正常使用的情况下，目前没有发现被封禁的情况。

**Comment by chinecc** [comment]
> 正常使用的情况下，目前没有发现被封禁的情况。
> 
> 正常使用的意思是：和你直接登录官方所用的网络环境一致，且账号没有其它问题，并且不要滥用。

我们是使用德国的服务器部署的，帐号使用的是全部欧洲法国的资料和IP，这种情况可以避免吗？
