### ISSUE TITLE
当前用户已有对话等待回复，不能再次请求

### ISSUE THREAD

**Issue by Leexiaobu** [moeakwak/chatgpt-web-share#62]
**Version**
v0.3.1

**What's your deploying method?**
- [✔ ] Docker

**Describe the bug**
![image](https://user-images.githubusercontent.com/20644303/229553306-38717b24-9c54-4774-9274-f42b2d183359.png)
应用状态显示 空闲中，但是该用户提问后显示 在等待回复，其他用户可以正常提问，据使用人说是某次回复后显示错误，刷新页面后就出现该情况，将该用户出错的对话删除后状态也一直在回复中

**Comment by moeakwak** [comment]
版本0.3.2解决了这个问题，请升级看看

**Comment by Leexiaobu** [comment]
👌 升级后状态恢复，已正常使用
