### ISSUE TITLE
请求出现错误

### ISSUE THREAD

**Issue by ZYM66** [moeakwak/chatgpt-web-share#66]
**Version**
最新

**What's your deploying environment?**
- [x] Docker
- [ ] Caddy
- [] Other

我的部署已经进入小规模使用中，今天突然出现这个错误，请告诉我原因和解决办法
![截屏2023-04-05 14 44 48](https://user-images.githubusercontent.com/61892155/230002691-a4d4dd03-95f7-480e-9a8c-7a3a3cc96031.png)

**Comment by ZYM66** [comment]
可能是由于gpt4请求超出次数限制，请加一个提示以防止用户认为是系统出现了问题

**Comment by moeakwak** [comment]
类似错误来自OpenAI。可能发生在：gpt4限流；同账户同时发起多次对话；服务器流控等。无法判断是否是请求超出次数限制，所以不打算更改这个提示。
