### ISSUE TITLE
wiki里的一个小疏漏？

### ISSUE THREAD

**Issue by tjsky** [moeakwak/chatgpt-web-share#70]
[自行部署（使用 Caddy 或 Nginx）](https://github.com/moeakwak/chatgpt-web-share/wiki/%E4%B8%AD%E6%96%87%E6%8C%87%E5%8D%97#%E8%87%AA%E8%A1%8C%E9%83%A8%E7%BD%B2%E4%BD%BF%E7%94%A8-caddy-%E6%88%96-nginx)里

安装 caddy 后，新建 Caddyfile 文件，内容参考 [Caddyfile](https://github.com/moeakwak/chatgpt-web-share/wiki/Caddyfile)。

这个路径指向了wiki的一个404的页面:`https://github.com/moeakwak/chatgpt-web-share/wiki/Caddyfile`
我猜本来是想指向这个的吧: `https://github.com/moeakwak/chatgpt-web-share/blob/main/Caddyfile`

**Comment by moeakwak** [comment]
这个链接原来放在readme里，是相对链接，复制过来以后路径就不对了。谢谢提醒。
