### ISSUE TITLE
建议:1. 会话排序希望添加按最新活动时间倒序选择项 ,2.希望能适配移动客户端,3. 希望能适配“install app”

### ISSUE THREAD

**Issue by tanpengsccd** [moeakwak/chatgpt-web-share#72]
建议: 参考部分ChatGPT Next(该项目只能使用API)的页面功能. https://chat-gpt-next-web.vercel.app/  
1. 会话排序希望添加按最新活动时间倒序选择项 : 一般是是常用的都是在顶部方便查看.
2. 希望能适配移动浏览器: 现在能用,但是滚动有点不方便.输入时会页面自动放大.
3. 希望能适配“install app”
这样安装到桌面端作为APP打开能快很多,如何能配合2.功能,那么 可以直接安装到手机桌面 直接使用,那就倍儿方便了. 一个服务n端通用.
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/13959880/230528628-8b308ddd-d322-4afa-8fa3-42d5a6f0bea5.png">

**Comment by perown** [comment]
修改前端还是需要时间，等作者996吧：）~~

**Comment by moeakwak** [comment]
1. 现在是按创建时间来排序，目前觉得挺好，不打算改成最新活动时间
2. 等待慢慢改进
3. 项目本身不是PWA应用，没有支持install app的必要
