### ISSUE TITLE
消息中的复制按钮没有效果

### ISSUE THREAD

**Issue by BaoziCDR** [moeakwak/chatgpt-web-share#73]
**Version**
v0.3.5

**What's your deploying method?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
消息中以及代码块中的复制按钮没有效果，按下去并不会进行复制。

**Screenshots or running logs**
<img width="756" alt="image" src="https://user-images.githubusercontent.com/44897251/230565083-ef380d96-3eac-45ef-8ae9-735fc01d13b7.png">

**Comment by moeakwak** [comment]
这是你浏览器的设置问题，需要给网站剪贴板权限

**Comment by BaoziCDR** [comment]
> 这是你浏览器的设置问题，需要给网站剪贴板权限

噢噢 确实！谢谢~~
