### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by yyfyyfhhh** [moeakwak/chatgpt-web-share#77]
**Version**
请问docker pull 不下来 是什么情况
![image](https://user-images.githubusercontent.com/130075267/230645528-77841962-6953-4ded-9843-fb2bb32eb560.png)

v0.x.x

**What's your deploying environment?**
- [ ] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
A clear and concise description of your problem.

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by moeakwak** [comment]
https://github.com/moeakwak/chatgpt-web-share/pkgs/container/chatgpt-web-share

试一下直接拉镜像

**Comment by yyfyyfhhh** [comment]
![image](https://user-images.githubusercontent.com/130075267/230647281-86259b0f-9103-46a9-90c3-d4e17bfc069a.png)
还是不太行
