### ISSUE TITLE
请问怎么制作一个适用于win server2022部署的docker镜像呢

### ISSUE THREAD

**Issue by INSIinc** [moeakwak/chatgpt-web-share#82]
请问怎么制作一个适用于win server2022部署的docker镜像呢

**Comment by moeakwak** [comment]
这种情况下，你应该不使用docker，而是直接运行后端程序，并且使用反向代理服务前端静态页面。

**Comment by INSIinc** [comment]
我尝试使用了第二种方法，但是chatgpt proxy v4构建有问题，见https://github.com/acheong08/ChatGPT-Proxy-V4/issues/42
