### ISSUE TITLE
错误地标记为无效对话的Bug

### ISSUE THREAD

**Issue by BaoziCDR** [moeakwak/chatgpt-web-share#85]
**Version**
v0.3.6

在初始化和定时获取对话总数的时候，API似乎做了限制，只能获取50条对话。
`api.chatgpt.chatgpt_manager.get_conversations()`
<img width="640" alt="image" src="https://user-images.githubusercontent.com/44897251/230775573-d91c6603-2c6b-4473-a44a-7855807f4818.png">

这样会导致一个问题：
当我对话总数超过50条时，在每次获取所有对话的时候，50条之后的对话总是会标记为无效
<img width="853" alt="image" src="https://user-images.githubusercontent.com/44897251/230775670-d265a680-f2fa-461e-87bf-fcf9632167d6.png">
会导致一些人的历史对话凭空消失，请问有解决方法吗？

**Comment by BaoziCDR** [comment]
我觉得自动标记为无效这个功能有点鸡肋，可以换成下面这种方案：

1. 在获取所有对话时不要自动标记无效对话
2. 在点击对话框时，返回对话无效的错误的时候，进行手动删除(或标记为无效对话)

**Comment by moeakwak** [comment]
会考虑的，谢谢反馈

**Comment by BaoziCDR** [comment]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/44897251/230921640-6fa6329d-2f7a-4cd2-a8b4-e1fa753d3b44.png">
我自己改的一小部分地方，可以在`api/routers/chat.py`下增加如上的代码，并在前端响应刷新左侧的对话列表

**Comment by moeakwak** [comment]
在请求记录时标记为无效会有很多问题。比如网络不稳定，openai故障或者puid过期时，一旦获取不到就给标记为无效了

**Comment by BaoziCDR** [comment]
> 在请求记录时标记为无效会有很多问题。比如网络不稳定，openai故障或者puid过期时，一旦获取不到就给标记为无效了

大佬回答很有道理，不过这里首先判断了404状态码，返回404状态码应该只会出现在获取不到的情况下吧？还是你说的情况都会返回404状态码，没有深入研究过

**Comment by moeakwak** [comment]
404的话或许是可以判断为不存在，但是不太确定……不过我感觉，一旦用户想看某个对话历史记录，点进去以后报错然后这条对话就消失了，这样确实不太好。其实只要不在openai网站使用chatgpt一般不会有不一致的问题。

**Comment by BaoziCDR** [comment]
我昨天给ChatGPT-Proxy-V4 提了个PR [#47](https://github.com/acheong08/ChatGPT-Proxy-V4/commit/f748e43aafebf361ade2a76f2db19822d3f1d65f)
更新后`api.chatgpt.chatgpt_manager.get_conversations()`若不传参数，默认只会拉20条，可能还会在其他地方影响到

**Comment by moeakwak** [comment]
目前处理策略是，暂时不会标记valid状态，因为go-chatgpt-api本身错误返回不是很明确。
