### ISSUE TITLE
使用过程中突然出现-1内部错误

### ISSUE THREAD

**Issue by ZYM66** [moeakwak/chatgpt-web-share#89]
**What's your deploying environment?**
- [x] Docker
- [ ] Caddy
- [ ] Other

<img width="242" alt="截屏2023-04-11 12 53 30" src="https://user-images.githubusercontent.com/61892155/231059784-3bb36daf-e791-4d40-bf87-9a8b18f82eb0.png">
已经正常上线部署一个星期了，今天突然出现了-1内部错误，检查了token没有问题。请告诉我问题的原因，以便让我排查

**Comment by moeakwak** [comment]
提供前端F12控制台输出日志截图以及后台日志

**Comment by ZYM66** [comment]
> 提供前端F12控制台输出日志截图以及后台日志

<img width="680" alt="截屏2023-04-11 15 24 27" src="https://user-images.githubusercontent.com/61892155/231086732-9143e3bb-ec1f-4101-b7b3-f828d3f0f53f.png">

**Comment by sola97** [comment]
我今天在IP被ban之后出现过这个错

**Comment by ZYM66** [comment]
> 你并没有提供服务器日志。从反代日志来看，403大概率是puid过期。

<img width="682" alt="截屏2023-04-11 21 59 07" src="https://user-images.githubusercontent.com/61892155/231186923-93338c1f-a649-4a65-8925-58c2be4c18a8.png">
您好，这是我的服务器日志，它看起来很正常

**Comment by ZYM66** [comment]
> 你并没有提供服务器日志。从反代日志来看，403大概率是puid过期。
<img width="692" alt="截屏2023-04-11 22 02 21" src="https://user-images.githubusercontent.com/61892155/231188199-d6e16e4a-21c7-464c-a098-c1298e07b86b.png">
上图是我ChatGPT网站中的puid
<img width="533" alt="截屏2023-04-11 22 04 46" src="https://user-images.githubusercontent.com/61892155/231188670-95a264ca-817f-4edd-9269-8e938e7277ae.png">
上图为我服务器中的配置文件
配置文件更新后已经重启docker

**Comment by moeakwak** [comment]
从你给的日志，没法判断是哪里抛出了错误。方便的话可以把服务器日志发到群组里面。

如果反向代理里面都是403，那就考虑是账号或者网络出问题了。试试看同样的网络环境下能否正常登录并使用官网的chatgpt服务。
