### ISSUE TITLE
希望可以在大佬升级的时候增加一些升级内容的说明

### ISSUE THREAD

**Issue by Shydlock** [moeakwak/chatgpt-web-share#90]
虽然作者偶尔会在群里公布升级内容，但是还是有很多的小版本更新没有说明不太清楚升级的内容，并且由于镜像没有发布在dockerhub上，所以也不太清楚具体的功能升级对应的版本号，希望作者有时间可以在升级的时候通过某种方式注明一下~

**Comment by moeakwak** [comment]
目前其实还属于测试阶段，变动频繁，所以没有发布过正式release，也就没有什么更新说明。一般release开头的commit内会简单写一下更新了什么。

**Comment by Shydlock** [comment]
> 目前其实还属于测试阶段，变动频繁，所以没有发布过正式release，也就没有什么更新说明。一般release开头的commit内会简单写一下更新了什么。

好的好的，感谢大佬回复~
