### ISSUE TITLE
打包到子目录后Caddyfile配置

### ISSUE THREAD

**Issue by cmlibo** [moeakwak/chatgpt-web-share#91]
假如打包到gpt4目录，由于前端打包时没有添加子目录路径。按目前的dockerfile，
Caddyfile需要改成

:80 {
	handle_path /gpt4/api/* {
		uri strip_prefix /gpt4
		reverse_proxy :8000
	}
	handle_path /gpt4/* {
		file_server
		uri strip_prefix /gpt4
		root * /app/dist
		try_files {path} /index.html
	}
}

如果没有uri strip_prefix /gpt4，当请求 /gpt4/xx，{path}就会为 /gpt4/xx，由于前端打包后，没有添加子目录路径，没有gpt4目录，肯定是找不到的文件，就直接返回index.html的内容，导致无法正常显示。

还有一个小问题，就是加了子目录后，点击站点左上角的标题，会打开 /，因为没有添加子目录路径，就无法打开了

**Comment by moeakwak** [comment]
目前只能对子目录有限支持，有这方面需求的朋友可能需要自己折腾下
