### ISSUE TITLE
默认代理是churchless的，能否将这个代理作为可配置项

### ISSUE THREAD

**Issue by poctopus** [moeakwak/chatgpt-web-share#92]
默认的代理，启动docker就报错，
Fetch conversation error (httpx.HTTPError): Client error '401 Unauthorized' for url 'https://bypass.churchless.tech/api/conversations?offset=0&limit=20'

是否可以将这个默认代理做可配置项，或者告之如何修改docker中这个代理的配置位置。

**Comment by moeakwak** [comment]
见wiki中“关于反向代理”相关内容。这个地址就是chatgpt_base_url
