### ISSUE TITLE
会话内容审计

### ISSUE THREAD

**Issue by lancelau4** [moeakwak/chatgpt-web-share#95]
希望用户端删除回话是假删除，不然后台进行会话内容审计就查看不到了。

**Comment by moeakwak** [comment]
想问一下审计的需求场景，是公司或者团队内部搭建使用吗？

**Comment by lancelau4** [comment]
对的，小团队使用。

**Comment by lancelau4** [comment]
https://hub.docker.com/r/moeakwak/chatgpt-web-share/tags
这里好像也很久没更新，现在的源有点慢。

**Comment by moeakwak** [comment]
在1.0.0版本中会完善审计功能，目前暂时不打算修改策略了。
会增加dockerhub镜像源
