### ISSUE TITLE
reverse_proxy_http_proxy 变量没有预期工作

### ISSUE THREAD

**Issue by mydaoyuan** [moeakwak/chatgpt-web-share#98]
**Version**
v0.3.8

**What's your deploying method?**
- [ * ] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
我在config.yaml中增加了 reverse_proxy_http_proxy 变量但是没有生效
https://github.com/moeakwak/chatgpt-web-share/pull/88   看起像是 [moeakwak/ChatGPT-Proxy-V4](https://github.com/moeakwak/ChatGPT-Proxy-V4.git)  没有更新

**To Reproduce**

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by sola97** [comment]
![image](https://user-images.githubusercontent.com/17388849/232229679-547414de-605d-4bbc-baa9-1486c21d21a3.png)
我这边测试正常
